// frontend-svelte/src/lib/features/admin-ops/OpsAlertEventsCard.svelte
<script lang="ts">
	/**
	 * OpsAlertEventsCard · admin Ops 告警事件卡片（Phase C M13）
	 *
	 * Vue ref: frontend/src/views/admin/ops/components/OpsAlertEventsCard.vue (05c44218)
	 *
	 * 自洽（self-contained）：
	 *   - 自取 alert-events（listOpsAlertEvents），不依赖父级数据，仅可选 refreshToken 触发重拉。
	 *   - 过滤器：status / severity（NativeSelect + sentinel __all__）、time-range。
	 *   - 游标分页：before_id + before_fired_at（cursor pagination，PAGE_SIZE=10）。
	 *   - 行点击 → 打开内置详情 Drawer（本组件自有，非父级注入）。
	 *   - Drawer 动作：
	 *       Silence  → createOpsAlertSilence(...) → 重拉 detail
	 *       Resolve  → updateOpsAlertEventStatus(id, 'manual_resolved') → 重拉 detail + 首页
	 *   - 详情含同维度历史（同 rule_id + platform + group_id），best-effort 过滤。
	 *
	 * 红线遵循：
	 *   - 仅复用 lib/ui/* primitives（Card / NativeSelect / Button / Badge / StandardDrawer），不手搓。
	 *   - NativeSelect sentinel __all__，绝不空值。
	 *   - Zinc 调色板 + 语义 token（destructive / amber-500 / emerald-500 / muted），无裸 hex。
	 *   - i18n 全走 $_('admin.ops.<key>', { default }) —— 不改 locales。
	 *   - 无 chart（本 section 是纯表格，Vue ref 同样无图），故不引 chart.js。
	 */
	import { _ } from 'svelte-i18n';
	import { RefreshCw, Ban, CheckCircle2, ExternalLink, Loader2 } from '@lucide/svelte';
	import {
		listOpsAlertEvents,
		getOpsAlertEvent,
		updateOpsAlertEventStatus,
		createOpsAlertSilence,
		type AlertEvent,
		type AlertEventsQuery
	} from '$lib/api/admin/ops';
	import { formatDateTime } from '$lib/features/admin-ops/ops';
	import { showError, showSuccess } from '$lib/stores/toast.svelte';
	import Card from '$lib/ui/Card.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Badge from '$lib/ui/Badge.svelte';
	import NativeSelect from '$lib/ui/NativeSelect.svelte';
	import StandardDrawer from '$lib/ui/StandardDrawer.svelte';

	type Props = {
		refreshToken?: number;
	};

	let { refreshToken = 0 }: Props = $props();

	const PAGE_SIZE = 10;
	const ALL = '__all__';

	// ── Filters (sentinel __all__, never empty string) ──────────────────────────
	let timeRange = $state<string>('24h');
	let severity = $state<string>(ALL);
	let status = $state<string>(ALL);

	const timeRangeOptions = $derived([
		{ value: '5m', label: $_('admin.ops.timeRange.5m', { default: '5m' }) },
		{ value: '30m', label: $_('admin.ops.timeRange.30m', { default: '30m' }) },
		{ value: '1h', label: $_('admin.ops.timeRange.1h', { default: '1h' }) },
		{ value: '6h', label: $_('admin.ops.timeRange.6h', { default: '6h' }) },
		{ value: '24h', label: $_('admin.ops.timeRange.24h', { default: '24h' }) },
		{ value: '7d', label: $_('admin.ops.timeRange.7d', { default: '7d' }) },
		{ value: '30d', label: $_('admin.ops.timeRange.30d', { default: '30d' }) }
	]);

	const severityOptions = $derived([
		{ value: ALL, label: $_('common.all', { default: 'All' }) },
		{ value: 'P0', label: 'P0' },
		{ value: 'P1', label: 'P1' },
		{ value: 'P2', label: 'P2' },
		{ value: 'P3', label: 'P3' }
	]);

	const statusOptions = $derived([
		{ value: ALL, label: $_('common.all', { default: 'All' }) },
		{ value: 'firing', label: $_('admin.ops.alertEvents.status.firing', { default: 'Firing' }) },
		{
			value: 'resolved',
			label: $_('admin.ops.alertEvents.status.resolved', { default: 'Resolved' })
		},
		{
			value: 'manual_resolved',
			label: $_('admin.ops.alertEvents.status.manualResolved', { default: 'Manually resolved' })
		}
	]);

	// ── List state ───────────────────────────────────────────────────────────────
	let events = $state<AlertEvent[]>([]);
	let loading = $state(false);
	let loadingMore = $state(false);
	let loadError = $state<string | null>(null);
	let hasMore = $state(true);

	function buildQuery(overrides: Partial<AlertEventsQuery> = {}): AlertEventsQuery {
		const q: AlertEventsQuery = {
			limit: PAGE_SIZE,
			time_range: timeRange
		};
		if (severity !== ALL) q.severity = severity;
		if (status !== ALL) q.status = status;
		return { ...q, ...overrides };
	}

	async function loadFirstPage() {
		loading = true;
		loadError = null;
		try {
			const data = await listOpsAlertEvents(buildQuery());
			events = data;
			hasMore = data.length === PAGE_SIZE;
		} catch (err) {
			loadError =
				(err as Error)?.message ??
				$_('admin.ops.alertEvents.loadFailed', { default: 'Failed to load alert events' });
			events = [];
			hasMore = false;
		} finally {
			loading = false;
		}
	}

	async function loadMore() {
		if (loadingMore || loading || !hasMore) return;
		const last = events[events.length - 1];
		if (!last) return;
		loadingMore = true;
		try {
			const data = await listOpsAlertEvents(
				buildQuery({ before_fired_at: last.fired_at || last.created_at, before_id: last.id })
			);
			if (!data.length) {
				hasMore = false;
				return;
			}
			events = [...events, ...data];
			if (data.length < PAGE_SIZE) hasMore = false;
		} catch {
			hasMore = false;
		} finally {
			loadingMore = false;
		}
	}

	function onScroll(e: Event) {
		const el = e.currentTarget as HTMLElement | null;
		if (!el) return;
		if (el.scrollTop + el.clientHeight >= el.scrollHeight - 120) void loadMore();
	}

	// Filters change → reset + reload. refreshToken (parent) → reload first page.
	let lastFilterKey = $state('');
	let lastRefresh = $state<number>(-1);
	$effect(() => {
		const key = `${timeRange}|${severity}|${status}`;
		const refreshChanged = refreshToken !== lastRefresh;
		if (key !== lastFilterKey || refreshChanged) {
			lastFilterKey = key;
			lastRefresh = refreshToken;
			events = [];
			hasMore = true;
			void loadFirstPage();
		}
	});

	// ── Detail drawer (owned) ─────────────────────────────────────────────────────
	let detailOpen = $state(false);
	let selected = $state<AlertEvent | null>(null);
	let detailLoading = $state(false);
	let actionLoading = $state(false);

	let history = $state<AlertEvent[]>([]);
	let historyLoading = $state(false);
	let historyRange = $state<string>('7d');
	const historyRangeOptions = $derived([
		{ value: '7d', label: $_('admin.ops.timeRange.7d', { default: '7d' }) },
		{ value: '30d', label: $_('admin.ops.timeRange.30d', { default: '30d' }) }
	]);

	let silenceDuration = $state<string>('1h');
	const silenceDurationOptions = $derived([
		{ value: '1h', label: $_('admin.ops.timeRange.1h', { default: '1h' }) },
		{ value: '24h', label: $_('admin.ops.timeRange.24h', { default: '24h' }) },
		{ value: '7d', label: $_('admin.ops.timeRange.7d', { default: '7d' }) }
	]);

	function dimString(event: AlertEvent | null | undefined, key: string): string {
		const v = event?.dimensions?.[key];
		if (v == null) return '';
		if (typeof v === 'string') return v;
		if (typeof v === 'number' || typeof v === 'boolean') return String(v);
		return '';
	}

	function dimGroupId(event: AlertEvent | null | undefined): number | undefined {
		const raw = event?.dimensions?.group_id;
		return typeof raw === 'number' ? raw : undefined;
	}

	function dimensionsSummary(event: AlertEvent): string {
		const parts: string[] = [];
		const platform = dimString(event, 'platform');
		if (platform) parts.push(`platform=${platform}`);
		const groupId = event.dimensions?.group_id;
		if (groupId != null && groupId !== '') parts.push(`group_id=${String(groupId)}`);
		const region = dimString(event, 'region');
		if (region) parts.push(`region=${region}`);
		return parts.length ? parts.join(' ') : '—';
	}

	function formatDurationMs(ms: number): string {
		const safe = Math.max(0, Math.floor(ms));
		const sec = Math.floor(safe / 1000);
		if (sec < 60) return `${sec}s`;
		const min = Math.floor(sec / 60);
		if (min < 60) return `${min}m`;
		const hr = Math.floor(min / 60);
		if (hr < 24) return `${hr}h`;
		return `${Math.floor(hr / 24)}d`;
	}

	function statusLabel(s: string | undefined): string {
		const v = String(s ?? '')
			.trim()
			.toLowerCase();
		if (!v) return '—';
		if (v === 'firing') return $_('admin.ops.alertEvents.status.firing', { default: 'Firing' });
		if (v === 'resolved') return $_('admin.ops.alertEvents.status.resolved', { default: 'Resolved' });
		if (v === 'manual_resolved')
			return $_('admin.ops.alertEvents.status.manualResolved', { default: 'Manually resolved' });
		return v.toUpperCase();
	}

	function durationLabel(event: AlertEvent): string {
		const fired = new Date(event.fired_at || event.created_at);
		if (Number.isNaN(fired.getTime())) return '—';
		const s = String(event.status ?? '')
			.trim()
			.toLowerCase();
		if (event.resolved_at) {
			const resolved = new Date(event.resolved_at);
			if (!Number.isNaN(resolved.getTime())) {
				const prefix =
					s === 'manual_resolved'
						? $_('admin.ops.alertEvents.status.manualResolved', { default: 'Manually resolved' })
						: $_('admin.ops.alertEvents.status.resolved', { default: 'Resolved' });
				return `${prefix} ${formatDurationMs(resolved.getTime() - fired.getTime())}`;
			}
		}
		return `${$_('admin.ops.alertEvents.status.firing', { default: 'Firing' })} ${formatDurationMs(Date.now() - fired.getTime())}`;
	}

	// Severity badge tone (Zinc + semantic tokens, no raw hex)
	function severityTone(sev: string | undefined): string {
		const v = String(sev ?? '').toLowerCase();
		if (v === 'p0' || v === 'critical')
			return 'border-destructive/40 bg-destructive/15 text-destructive';
		if (v === 'p1' || v === 'warning')
			return 'border-amber-500/40 bg-amber-500/15 text-amber-600 dark:text-amber-400';
		if (v === 'p2' || v === 'info')
			return 'border-blue-500/40 bg-blue-500/15 text-blue-600 dark:text-blue-400';
		return 'border-border bg-muted text-muted-foreground';
	}

	function statusTone(s: string | undefined): string {
		const v = String(s ?? '').toLowerCase();
		if (v === 'firing') return 'border-destructive/40 bg-destructive/15 text-destructive';
		if (v === 'resolved')
			return 'border-emerald-500/40 bg-emerald-500/15 text-emerald-600 dark:text-emerald-400';
		return 'border-border bg-muted text-muted-foreground';
	}

	async function openDetail(row: AlertEvent) {
		detailOpen = true;
		selected = row;
		detailLoading = true;
		historyLoading = true;
		try {
			selected = await getOpsAlertEvent(row.id);
		} catch (err) {
			showError(
				(err as Error)?.message ??
					$_('admin.ops.alertEvents.detail.loadFailed', { default: 'Failed to load detail' })
			);
		} finally {
			detailLoading = false;
		}
		await loadHistory();
	}

	function closeDetail() {
		detailOpen = false;
		selected = null;
		history = [];
	}

	async function loadHistory() {
		const ev = selected;
		if (!ev) {
			history = [];
			historyLoading = false;
			return;
		}
		historyLoading = true;
		try {
			const platform = dimString(ev, 'platform');
			const items = await listOpsAlertEvents({
				limit: 20,
				time_range: historyRange,
				platform: platform || undefined,
				group_id: dimGroupId(ev)
			});
			// best-effort: narrow to same rule_id + platform + group_id
			history = items.filter((it) => {
				if (it.rule_id !== ev.rule_id) return false;
				if (dimString(it, 'platform') !== dimString(ev, 'platform')) return false;
				return (it.dimensions?.group_id ?? null) === (ev.dimensions?.group_id ?? null);
			});
		} catch {
			history = [];
		} finally {
			historyLoading = false;
		}
	}

	// historyRange change (while open) → reload history
	let lastHistoryRange = $state('7d');
	$effect(() => {
		const r = historyRange;
		if (detailOpen && r !== lastHistoryRange) {
			lastHistoryRange = r;
			void loadHistory();
		}
		if (!detailOpen) lastHistoryRange = r;
	});

	function untilRfc3339(duration: string): string {
		const now = Date.now();
		const ms =
			duration === '24h'
				? 24 * 60 * 60 * 1000
				: duration === '7d'
					? 7 * 24 * 60 * 60 * 1000
					: 60 * 60 * 1000;
		return new Date(now + ms).toISOString();
	}

	async function silenceAlert() {
		const ev = selected;
		if (!ev || actionLoading) return;
		actionLoading = true;
		try {
			await createOpsAlertSilence({
				rule_id: ev.rule_id,
				platform: dimString(ev, 'platform') || '',
				group_id: dimGroupId(ev),
				region: dimString(ev, 'region') || undefined,
				until: untilRfc3339(silenceDuration),
				reason: `silence from UI (${silenceDuration})`
			});
			showSuccess(
				$_('admin.ops.alertEvents.detail.silenceSuccess', { default: 'Alert silenced' })
			);
		} catch (err) {
			showError(
				(err as Error)?.message ??
					$_('admin.ops.alertEvents.detail.silenceFailed', { default: 'Failed to silence alert' })
			);
		} finally {
			actionLoading = false;
		}
	}

	async function manualResolve() {
		const ev = selected;
		if (!ev || actionLoading) return;
		actionLoading = true;
		try {
			await updateOpsAlertEventStatus(ev.id, 'manual_resolved');
			showSuccess(
				$_('admin.ops.alertEvents.detail.manualResolvedSuccess', { default: 'Alert resolved' })
			);
			// refetch detail + first page to reflect new status
			selected = await getOpsAlertEvent(ev.id);
			await loadFirstPage();
			await loadHistory();
		} catch (err) {
			showError(
				(err as Error)?.message ??
					$_('admin.ops.alertEvents.detail.manualResolvedFailed', {
						default: 'Failed to resolve alert'
					})
			);
		} finally {
			actionLoading = false;
		}
	}

	const isEmpty = $derived(events.length === 0 && !loading && !loadError);
</script>

<Card class="p-6" data-testid="ops-alert-events-card">
	<!-- Header toolbar -->
	<div class="mb-4 flex flex-wrap items-start justify-between gap-3">
		<div>
			<h3 class="text-sm font-bold text-foreground">
				{$_('admin.ops.alertEvents.title', { default: 'Alert events' })}
			</h3>
			<p class="mt-1 text-xs text-muted-foreground">
				{$_('admin.ops.alertEvents.description', {
					default: 'Recent alert firings with silence and manual-resolve actions.'
				})}
			</p>
		</div>
		<div class="flex flex-wrap items-center gap-1.5">
			<NativeSelect
				bind:value={timeRange}
				options={timeRangeOptions}
				class="h-9 w-[110px]"
				aria-label={$_('admin.ops.alertEvents.filter.timeRange', { default: 'Time range' })}
				data-testid="ops-alert-events-filter-time"
			/>
			<NativeSelect
				bind:value={severity}
				options={severityOptions}
				class="h-9 w-[100px]"
				aria-label={$_('admin.ops.alertEvents.filter.severity', { default: 'Severity' })}
				data-testid="ops-alert-events-filter-severity"
			/>
			<NativeSelect
				bind:value={status}
				options={statusOptions}
				class="h-9 w-[140px]"
				aria-label={$_('admin.ops.alertEvents.filter.status', { default: 'Status' })}
				data-testid="ops-alert-events-filter-status"
			/>
			<Button
				variant="outline"
				size="sm"
				disabled={loading}
				onclick={() => loadFirstPage()}
				data-testid="ops-alert-events-refresh"
			>
				<RefreshCw class={`mr-1.5 h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />
				{$_('common.refresh', { default: 'Refresh' })}
			</Button>
		</div>
	</div>

	{#if loading}
		<div
			class="flex items-center gap-2 text-sm text-muted-foreground"
			role="status"
			data-testid="ops-alert-events-loading"
		>
			<Loader2 class="h-4 w-4 animate-spin" />
			{$_('admin.ops.alertEvents.loading', { default: 'Loading…' })}
		</div>
	{:else if loadError}
		<div
			class="rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive"
			role="alert"
			data-testid="ops-alert-events-error"
		>
			{loadError}
		</div>
	{:else if isEmpty}
		<div
			class="rounded-lg border border-dashed border-border p-7 text-center text-sm text-muted-foreground"
			data-testid="ops-alert-events-empty"
		>
			{$_('admin.ops.alertEvents.empty', { default: 'No alert events in this range.' })}
		</div>
	{:else}
		<div class="overflow-hidden rounded-lg border border-border">
			<div class="max-h-[600px] overflow-y-auto" onscroll={onScroll}>
				<table class="w-full border-collapse text-xs">
					<thead class="sticky top-0 z-10 border-b border-border bg-muted">
						<tr>
							<th class="px-3.5 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.time', { default: 'Time' })}
							</th>
							<th class="px-3.5 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.severity', { default: 'Severity' })}
							</th>
							<th class="px-3.5 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.platform', { default: 'Platform' })}
							</th>
							<th class="px-3.5 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.ruleId', { default: 'Rule' })}
							</th>
							<th class="px-3.5 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.title', { default: 'Title' })}
							</th>
							<th class="px-3.5 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.duration', { default: 'Duration' })}
							</th>
							<th class="px-3.5 py-2.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.dimensions', { default: 'Dimensions' })}
							</th>
							<th class="px-3.5 py-2.5 text-right text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
								{$_('admin.ops.alertEvents.table.email', { default: 'Email' })}
							</th>
						</tr>
					</thead>
					<tbody>
						{#each events as row (row.id)}
							<tr
								role="button"
								tabindex="0"
								class="cursor-pointer border-b border-border transition-colors last:border-0 hover:bg-muted/50 focus-visible:bg-muted/50 focus-visible:outline-none"
								title={row.title || ''}
								onclick={() => openDetail(row)}
								onkeydown={(e) => {
									if (e.key === 'Enter' || e.key === ' ') {
										e.preventDefault();
										openDetail(row);
									}
								}}
								data-testid="ops-alert-events-row"
							>
								<td class="whitespace-nowrap px-3.5 py-2.5 text-muted-foreground">
									{formatDateTime(row.fired_at || row.created_at)}
								</td>
								<td class="whitespace-nowrap px-3.5 py-2.5">
									<div class="flex items-center gap-1.5">
										<Badge variant="outline" class={`border ${severityTone(row.severity)}`}>
											{row.severity || '—'}
										</Badge>
										<Badge variant="outline" class={`border ${statusTone(row.status)}`}>
											{statusLabel(row.status)}
										</Badge>
									</div>
								</td>
								<td class="whitespace-nowrap px-3.5 py-2.5 text-muted-foreground">
									{dimString(row, 'platform') || '—'}
								</td>
								<td class="whitespace-nowrap px-3.5 py-2.5 text-muted-foreground">
									<span class="font-mono">#{row.rule_id}</span>
								</td>
								<td class="min-w-[260px] px-3.5 py-2.5">
									<div class="max-w-[360px] truncate font-semibold text-foreground">
										{row.title || '—'}
									</div>
									{#if row.description}
										<div class="mt-0.5 line-clamp-2 text-[11px] text-muted-foreground">
											{row.description}
										</div>
									{/if}
								</td>
								<td class="whitespace-nowrap px-3.5 py-2.5 text-muted-foreground">
									{durationLabel(row)}
								</td>
								<td class="whitespace-nowrap px-3.5 py-2.5 text-[11px] text-muted-foreground">
									{dimensionsSummary(row)}
								</td>
								<td class="whitespace-nowrap px-3.5 py-2.5 text-right">
									<span class="inline-flex items-center justify-end gap-1.5 text-[11px] font-semibold">
										{#if row.email_sent}
											<CheckCircle2 class="h-3.5 w-3.5 text-emerald-500" />
											<span class="text-muted-foreground">
												{$_('admin.ops.alertEvents.table.emailSent', { default: 'Sent' })}
											</span>
										{:else}
											<Ban class="h-3.5 w-3.5 text-muted-foreground" />
											<span class="text-muted-foreground">
												{$_('admin.ops.alertEvents.table.emailIgnored', { default: 'Ignored' })}
											</span>
										{/if}
									</span>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
				{#if loadingMore}
					<div
						class="flex items-center justify-center gap-2 p-2.5 text-[11px] text-muted-foreground"
						role="status"
						data-testid="ops-alert-events-loading-more"
					>
						<Loader2 class="h-3 w-3 animate-spin" />
						{$_('admin.ops.alertEvents.loading', { default: 'Loading…' })}
					</div>
				{:else if !hasMore && events.length > 0}
					<div class="p-2.5 text-center text-[11px] text-muted-foreground">—</div>
				{/if}
			</div>
		</div>
	{/if}
</Card>

<!-- Detail drawer (owned) -->
<StandardDrawer
	bind:open={detailOpen}
	width="lg"
	title={$_('admin.ops.alertEvents.detail.title', { default: 'Alert event' })}
	description={$_('admin.ops.alertEvents.detail.subtitle', {
		default: 'Silence the rule or mark this alert as manually resolved.'
	})}
	data-testid="ops-alert-event-detail-drawer"
>
	<div class="mt-4 flex-1 overflow-y-auto pr-1">
		{#if detailLoading}
			<div
				class="flex items-center justify-center gap-2 py-9 text-sm text-muted-foreground"
				data-testid="ops-alert-event-detail-loading"
			>
				<Loader2 class="h-4 w-4 animate-spin" />
				{$_('admin.ops.alertEvents.detail.loading', { default: 'Loading…' })}
			</div>
		{:else if !selected}
			<div class="py-9 text-center text-sm text-muted-foreground">
				{$_('admin.ops.alertEvents.detail.empty', { default: 'No alert selected.' })}
			</div>
		{:else}
			<div class="flex flex-col gap-4">
				<!-- Summary + actions -->
				<div class="rounded-lg border border-border bg-muted/50 p-3.5">
					<div class="flex flex-wrap items-start justify-between gap-2.5">
						<div>
							<div class="flex flex-wrap items-center gap-1.5">
								<Badge variant="outline" class={`border ${severityTone(selected.severity)}`}>
									{selected.severity || '—'}
								</Badge>
								<Badge variant="outline" class={`border ${statusTone(selected.status)}`}>
									{statusLabel(selected.status)}
								</Badge>
							</div>
							<div class="mt-2 text-sm font-semibold text-foreground">
								{selected.title || '—'}
							</div>
							{#if selected.description}
								<div class="mt-1 whitespace-pre-wrap text-[11.5px] text-muted-foreground">
									{selected.description}
								</div>
							{/if}
						</div>
						<div class="flex flex-wrap items-center gap-1.5">
							<div
								class="flex items-center gap-1.5 rounded-lg border border-border bg-card px-2.5 py-1.5"
							>
								<span class="text-[11px] font-semibold text-muted-foreground">
									{$_('admin.ops.alertEvents.detail.silence', { default: 'Silence' })}
								</span>
								<NativeSelect
									bind:value={silenceDuration}
									options={silenceDurationOptions}
									class="h-8 w-[90px]"
									aria-label={$_('admin.ops.alertEvents.detail.silence', { default: 'Silence' })}
									data-testid="ops-alert-event-silence-duration"
								/>
								<Button
									variant="outline"
									size="sm"
									disabled={actionLoading}
									onclick={silenceAlert}
									data-testid="ops-alert-event-silence-apply"
								>
									<Ban class="mr-1 h-3.5 w-3.5" />
									{$_('common.apply', { default: 'Apply' })}
								</Button>
							</div>
							<Button
								variant="outline"
								size="sm"
								disabled={actionLoading}
								onclick={manualResolve}
								data-testid="ops-alert-event-resolve"
							>
								<CheckCircle2 class="mr-1 h-3.5 w-3.5" />
								{$_('admin.ops.alertEvents.detail.manualResolve', { default: 'Resolve' })}
							</Button>
						</div>
					</div>
				</div>

				<!-- Meta grid -->
				<div class="grid grid-cols-2 gap-2.5">
					<div class="rounded-lg border border-border bg-card p-3">
						<div class="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
							{$_('admin.ops.alertEvents.detail.firedAt', { default: 'Fired at' })}
						</div>
						<div class="mt-1 text-[13px] font-medium text-foreground">
							{formatDateTime(selected.fired_at || selected.created_at)}
						</div>
					</div>
					<div class="rounded-lg border border-border bg-card p-3">
						<div class="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
							{$_('admin.ops.alertEvents.detail.resolvedAt', { default: 'Resolved at' })}
						</div>
						<div class="mt-1 text-[13px] font-medium text-foreground">
							{selected.resolved_at ? formatDateTime(selected.resolved_at) : '—'}
						</div>
					</div>
					<div class="rounded-lg border border-border bg-card p-3">
						<div class="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
							{$_('admin.ops.alertEvents.detail.ruleId', { default: 'Rule' })}
						</div>
						<div class="mt-1 flex flex-wrap items-center gap-1.5">
							<span class="font-mono text-[13px] font-bold text-foreground">#{selected.rule_id}</span>
							<a
								class="inline-flex items-center gap-1 rounded border border-border bg-card px-2 py-0.5 text-[10px] text-muted-foreground no-underline transition-colors hover:text-foreground"
								href={`/admin/ops?open_alert_rules=1&alert_rule_id=${selected.rule_id}`}
							>
								<ExternalLink class="h-3 w-3" />
								{$_('admin.ops.alertEvents.detail.viewRule', { default: 'View rule' })}
							</a>
						</div>
					</div>
					<div class="rounded-lg border border-border bg-card p-3">
						<div class="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
							{$_('admin.ops.alertEvents.detail.dimensions', { default: 'Dimensions' })}
						</div>
						<div class="mt-1 text-xs text-muted-foreground">
							{#if dimString(selected, 'platform')}
								<div>platform={dimString(selected, 'platform')}</div>
							{/if}
							{#if selected.dimensions?.group_id}
								<div>group_id={String(selected.dimensions.group_id)}</div>
							{/if}
							{#if dimString(selected, 'region')}
								<div>region={dimString(selected, 'region')}</div>
							{/if}
						</div>
					</div>
				</div>

				<!-- History -->
				<div class="rounded-lg border border-border bg-card p-3.5">
					<div class="mb-3 flex flex-wrap items-center justify-between gap-2.5">
						<div>
							<div class="text-[13px] font-bold text-foreground">
								{$_('admin.ops.alertEvents.detail.historyTitle', { default: 'Recent history' })}
							</div>
							<div class="mt-0.5 text-[11px] text-muted-foreground">
								{$_('admin.ops.alertEvents.detail.historyHint', {
									default: 'Same rule and dimensions.'
								})}
							</div>
						</div>
						<NativeSelect
							bind:value={historyRange}
							options={historyRangeOptions}
							class="h-8 w-[120px]"
							aria-label={$_('admin.ops.alertEvents.detail.historyTitle', {
								default: 'Recent history'
							})}
							data-testid="ops-alert-event-history-range"
						/>
					</div>
					{#if historyLoading}
						<div class="py-5 text-center text-[11.5px] text-muted-foreground">
							{$_('admin.ops.alertEvents.detail.historyLoading', { default: 'Loading…' })}
						</div>
					{:else if history.length === 0}
						<div class="py-5 text-center text-[11.5px] text-muted-foreground">
							{$_('admin.ops.alertEvents.detail.historyEmpty', { default: 'No history.' })}
						</div>
					{:else}
						<div class="overflow-hidden rounded-lg border border-border">
							<table class="w-full border-collapse text-[11.5px]">
								<thead class="border-b border-border bg-muted">
									<tr>
										<th class="px-3 py-1.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
											{$_('admin.ops.alertEvents.table.time', { default: 'Time' })}
										</th>
										<th class="px-3 py-1.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
											{$_('admin.ops.alertEvents.table.status', { default: 'Status' })}
										</th>
										<th class="px-3 py-1.5 text-left text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
											{$_('admin.ops.alertEvents.table.metric', { default: 'Metric' })}
										</th>
									</tr>
								</thead>
								<tbody>
									{#each history as it (it.id)}
										<tr class="border-b border-border last:border-0">
											<td class="px-3 py-1.5 text-muted-foreground">
												{formatDateTime(it.fired_at || it.created_at)}
											</td>
											<td class="px-3 py-1.5">
												<Badge variant="outline" class={`border ${statusTone(it.status)}`}>
													{statusLabel(it.status)}
												</Badge>
											</td>
											<td class="px-3 py-1.5 text-muted-foreground">
												{#if typeof it.metric_value === 'number' && typeof it.threshold_value === 'number'}
													{it.metric_value.toFixed(2)} / {it.threshold_value.toFixed(2)}
												{:else}
													—
												{/if}
											</td>
										</tr>
									{/each}
								</tbody>
							</table>
						</div>
					{/if}
				</div>
			</div>
		{/if}
	</div>
</StandardDrawer>

// frontend/src/views/admin/ops/components/OpsAlertEventsCard.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useAppStore } from '@/stores/app'
import Select from '@/components/common/Select.vue'
import BaseDialog from '@/components/common/BaseDialog.vue'
import Icon from '@/components/icons/Icon.vue'
import { opsAPI, type AlertEventsQuery } from '@/api/admin/ops'
import type { AlertEvent } from '../types'
import { formatDateTime } from '../utils/opsFormatters'

const { t } = useI18n()
const appStore = useAppStore()

const PAGE_SIZE = 10

const loading = ref(false)
const loadingMore = ref(false)
const events = ref<AlertEvent[]>([])
const hasMore = ref(true)

// Detail modal
const showDetail = ref(false)
const selected = ref<AlertEvent | null>(null)
const detailLoading = ref(false)
const detailActionLoading = ref(false)
const historyLoading = ref(false)
const history = ref<AlertEvent[]>([])
const historyRange = ref('7d')
const historyRangeOptions = computed(() => [
  { value: '7d', label: t('admin.ops.timeRange.7d') },
  { value: '30d', label: t('admin.ops.timeRange.30d') }
])

const silenceDuration = ref('1h')
const silenceDurationOptions = computed(() => [
  { value: '1h', label: t('admin.ops.timeRange.1h') },
  { value: '24h', label: t('admin.ops.timeRange.24h') },
  { value: '7d', label: t('admin.ops.timeRange.7d') }
])

// Filters
const timeRange = ref('24h')
const timeRangeOptions = computed(() => [
  { value: '5m', label: t('admin.ops.timeRange.5m') },
  { value: '30m', label: t('admin.ops.timeRange.30m') },
  { value: '1h', label: t('admin.ops.timeRange.1h') },
  { value: '6h', label: t('admin.ops.timeRange.6h') },
  { value: '24h', label: t('admin.ops.timeRange.24h') },
  { value: '7d', label: t('admin.ops.timeRange.7d') },
  { value: '30d', label: t('admin.ops.timeRange.30d') }
])

const severity = ref<string>('')
const severityOptions = computed(() => [
  { value: '', label: t('common.all') },
  { value: 'P0', label: 'P0' },
  { value: 'P1', label: 'P1' },
  { value: 'P2', label: 'P2' },
  { value: 'P3', label: 'P3' }
])

const status = ref<string>('')
const statusOptions = computed(() => [
  { value: '', label: t('common.all') },
  { value: 'firing', label: t('admin.ops.alertEvents.status.firing') },
  { value: 'resolved', label: t('admin.ops.alertEvents.status.resolved') },
  { value: 'manual_resolved', label: t('admin.ops.alertEvents.status.manualResolved') }
])

const emailSent = ref<string>('')
const emailSentOptions = computed(() => [
  { value: '', label: t('common.all') },
  { value: 'true', label: t('admin.ops.alertEvents.table.emailSent') },
  { value: 'false', label: t('admin.ops.alertEvents.table.emailIgnored') }
])

function buildQuery(overrides: Partial<AlertEventsQuery> = {}): AlertEventsQuery {
  const q: AlertEventsQuery = {
    limit: PAGE_SIZE,
    time_range: timeRange.value
  }
  if (severity.value) q.severity = severity.value
  if (status.value) q.status = status.value
  if (emailSent.value === 'true') q.email_sent = true
  if (emailSent.value === 'false') q.email_sent = false
  return { ...q, ...overrides }
}

async function loadFirstPage() {
  loading.value = true
  try {
    const data = await opsAPI.listAlertEvents(buildQuery())
    events.value = data
    hasMore.value = data.length === PAGE_SIZE
  } catch (err: any) {
    console.error('[OpsAlertEventsCard] Failed to load alert events', err)
    appStore.showError(err?.response?.data?.detail || t('admin.ops.alertEvents.loadFailed'))
    events.value = []
    hasMore.value = false
  } finally {
    loading.value = false
  }
}

async function loadMore() {
  if (loadingMore.value || loading.value) return
  if (!hasMore.value) return
  const last = events.value[events.value.length - 1]
  if (!last) return

  loadingMore.value = true
  try {
    const data = await opsAPI.listAlertEvents(
      buildQuery({ before_fired_at: last.fired_at || last.created_at, before_id: last.id })
    )
    if (!data.length) {
      hasMore.value = false
      return
    }
    events.value = [...events.value, ...data]
    if (data.length < PAGE_SIZE) hasMore.value = false
  } catch (err: any) {
    console.error('[OpsAlertEventsCard] Failed to load more alert events', err)
    hasMore.value = false
  } finally {
    loadingMore.value = false
  }
}

function onScroll(e: Event) {
  const el = e.target as HTMLElement | null
  if (!el) return
  const nearBottom = el.scrollTop + el.clientHeight >= el.scrollHeight - 120
  if (nearBottom) loadMore()
}

function getDimensionString(event: AlertEvent | null | undefined, key: string): string {
  const v = event?.dimensions?.[key]
  if (v == null) return ''
  if (typeof v === 'string') return v
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  return ''
}

function formatDurationMs(ms: number): string {
  const safe = Math.max(0, Math.floor(ms))
  const sec = Math.floor(safe / 1000)
  if (sec < 60) return `${sec}s`
  const min = Math.floor(sec / 60)
  if (min < 60) return `${min}m`
  const hr = Math.floor(min / 60)
  if (hr < 24) return `${hr}h`
  const day = Math.floor(hr / 24)
  return `${day}d`
}

function formatDurationLabel(event: AlertEvent): string {
  const firedAt = new Date(event.fired_at || event.created_at)
  if (Number.isNaN(firedAt.getTime())) return '-'
  const resolvedAtStr = event.resolved_at || null
  const status = String(event.status || '').trim().toLowerCase()

  if (resolvedAtStr) {
    const resolvedAt = new Date(resolvedAtStr)
    if (!Number.isNaN(resolvedAt.getTime())) {
      const ms = resolvedAt.getTime() - firedAt.getTime()
      const prefix = status === 'manual_resolved'
        ? t('admin.ops.alertEvents.status.manualResolved')
        : t('admin.ops.alertEvents.status.resolved')
      return `${prefix} ${formatDurationMs(ms)}`
    }
  }

  const now = Date.now()
  const ms = now - firedAt.getTime()
  return `${t('admin.ops.alertEvents.status.firing')} ${formatDurationMs(ms)}`
}

function formatDimensionsSummary(event: AlertEvent): string {
  const parts: string[] = []
  const platform = getDimensionString(event, 'platform')
  if (platform) parts.push(`platform=${platform}`)
  const groupId = event.dimensions?.group_id
  if (groupId != null && groupId !== '') parts.push(`group_id=${String(groupId)}`)
  const region = getDimensionString(event, 'region')
  if (region) parts.push(`region=${region}`)
  return parts.length ? parts.join(' ') : '-'
}

function closeDetail() {
  showDetail.value = false
  selected.value = null
  history.value = []
}

async function openDetail(row: AlertEvent) {
  showDetail.value = true
  selected.value = row
  detailLoading.value = true
  historyLoading.value = true

  try {
    const detail = await opsAPI.getAlertEvent(row.id)
    selected.value = detail
  } catch (err: any) {
    console.error('[OpsAlertEventsCard] Failed to load alert detail', err)
    appStore.showError(err?.response?.data?.detail || t('admin.ops.alertEvents.detail.loadFailed'))
  } finally {
    detailLoading.value = false
  }

  await loadHistory()
}

async function loadHistory() {
  const ev = selected.value
  if (!ev) {
    history.value = []
    historyLoading.value = false
    return
  }

  historyLoading.value = true
  try {
    const platform = getDimensionString(ev, 'platform')
    const groupIdRaw = ev.dimensions?.group_id
    const groupId = typeof groupIdRaw === 'number' ? groupIdRaw : undefined

    const items = await opsAPI.listAlertEvents({
      limit: 20,
      time_range: historyRange.value,
      platform: platform || undefined,
      group_id: groupId,
      status: ''
    })

    // Best-effort: narrow to same rule_id + dimensions
    history.value = items.filter((it) => {
      if (it.rule_id !== ev.rule_id) return false
      const p1 = getDimensionString(it, 'platform')
      const p2 = getDimensionString(ev, 'platform')
      if ((p1 || '') !== (p2 || '')) return false
      const g1 = it.dimensions?.group_id
      const g2 = ev.dimensions?.group_id
      return (g1 ?? null) === (g2 ?? null)
    })
  } catch (err: any) {
    console.error('[OpsAlertEventsCard] Failed to load alert history', err)
    history.value = []
  } finally {
    historyLoading.value = false
  }
}

function durationToUntilRFC3339(duration: string): string {
  const now = Date.now()
  if (duration === '1h') return new Date(now + 60 * 60 * 1000).toISOString()
  if (duration === '24h') return new Date(now + 24 * 60 * 60 * 1000).toISOString()
  if (duration === '7d') return new Date(now + 7 * 24 * 60 * 60 * 1000).toISOString()
  return new Date(now + 60 * 60 * 1000).toISOString()
}

async function silenceAlert() {
  const ev = selected.value
  if (!ev) return
  if (detailActionLoading.value) return
  detailActionLoading.value = true
  try {
    const platform = getDimensionString(ev, 'platform')
    const groupIdRaw = ev.dimensions?.group_id
    const groupId = typeof groupIdRaw === 'number' ? groupIdRaw : null
    const region = getDimensionString(ev, 'region') || null

    await opsAPI.createAlertSilence({
      rule_id: ev.rule_id,
      platform: platform || '',
      group_id: groupId ?? undefined,
      region: region ?? undefined,
      until: durationToUntilRFC3339(silenceDuration.value),
      reason: `silence from UI (${silenceDuration.value})`
    })

    appStore.showSuccess(t('admin.ops.alertEvents.detail.silenceSuccess'))
  } catch (err: any) {
    console.error('[OpsAlertEventsCard] Failed to silence alert', err)
    appStore.showError(err?.response?.data?.detail || t('admin.ops.alertEvents.detail.silenceFailed'))
  } finally {
    detailActionLoading.value = false
  }
}

async function manualResolve() {
  if (!selected.value) return
  if (detailActionLoading.value) return
  detailActionLoading.value = true
  try {
    await opsAPI.updateAlertEventStatus(selected.value.id, 'manual_resolved')
    appStore.showSuccess(t('admin.ops.alertEvents.detail.manualResolvedSuccess'))

    // Refresh detail + first page to reflect new status
    const detail = await opsAPI.getAlertEvent(selected.value.id)
    selected.value = detail
    await loadFirstPage()
    await loadHistory()
  } catch (err: any) {
    console.error('[OpsAlertEventsCard] Failed to resolve alert', err)
    appStore.showError(err?.response?.data?.detail || t('admin.ops.alertEvents.detail.manualResolvedFailed'))
  } finally {
    detailActionLoading.value = false
  }
}

onMounted(() => {
  loadFirstPage()
})

watch([timeRange, severity, status, emailSent], () => {
  events.value = []
  hasMore.value = true
  loadFirstPage()
})

watch(historyRange, () => {
  if (showDetail.value) loadHistory()
})

function severityBadgeClass(severity: string | undefined): string {
  const s = String(severity || '').trim().toLowerCase()
  if (s === 'p0' || s === 'critical') return 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300'
  if (s === 'p1' || s === 'warning') return 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300'
  if (s === 'p2' || s === 'info') return 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300'
  if (s === 'p3') return 'bg-gray-100 text-gray-700 dark:bg-dark-700 dark:text-gray-300'
  return 'bg-gray-100 text-gray-700 dark:bg-dark-700 dark:text-gray-300'
}

function statusBadgeClass(status: string | undefined): string {
  const s = String(status || '').trim().toLowerCase()
  if (s === 'firing') return 'bg-red-50 text-red-700 ring-red-600/20 dark:bg-red-900/30 dark:text-red-300 dark:ring-red-500/30'
  if (s === 'resolved') return 'bg-green-50 text-green-700 ring-green-600/20 dark:bg-green-900/30 dark:text-green-300 dark:ring-green-500/30'
  if (s === 'manual_resolved') return 'bg-slate-50 text-slate-700 ring-slate-600/20 dark:bg-slate-900/30 dark:text-slate-300 dark:ring-slate-500/30'
  return 'bg-gray-50 text-gray-700 ring-gray-600/20 dark:bg-gray-900/30 dark:text-gray-300 dark:ring-gray-500/30'
}

function formatStatusLabel(status: string | undefined): string {
  const s = String(status || '').trim().toLowerCase()
  if (!s) return '-'
  if (s === 'firing') return t('admin.ops.alertEvents.status.firing')
  if (s === 'resolved') return t('admin.ops.alertEvents.status.resolved')
  if (s === 'manual_resolved') return t('admin.ops.alertEvents.status.manualResolved')
  return s.toUpperCase()
}

const empty = computed(() => events.value.length === 0 && !loading.value)
</script>

<template>
  <div class="rounded-lg bg-card p-6 shadow-metal border border-border">
    <div class="mb-4 flex items-start justify-between gap-4">
      <div>
        <h3 class="text-sm font-bold text-foreground">{{ t('admin.ops.alertEvents.title') }}</h3>
        <p class="mt-1 text-xs text-muted-foreground">{{ t('admin.ops.alertEvents.description') }}</p>
      </div>

      <div class="flex items-center gap-2">
        <Select :model-value="timeRange" :options="timeRangeOptions" class="w-[120px]" @change="timeRange = String($event || '24h')" />
        <Select :model-value="severity" :options="severityOptions" class="w-[88px]" @change="severity = String($event || '')" />
        <Select :model-value="status" :options="statusOptions" class="w-[110px]" @change="status = String($event || '')" />
        <Select :model-value="emailSent" :options="emailSentOptions" class="w-[110px]" @change="emailSent = String($event || '')" />
        <button
          class="flex items-center gap-1.5 rounded-md bg-metal-raised border border-border px-3 py-1.5 text-xs font-bold text-foreground/85 transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-50"
          :disabled="loading"
          @click="loadFirstPage"
        >
          <svg class="h-3.5 w-3.5" :class="{ 'animate-spin': loading }" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          {{ t('common.refresh') }}
        </button>
      </div>
    </div>

    <div v-if="loading" class="flex items-center gap-2 text-sm text-muted-foreground">
      <svg class="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
      {{ t('admin.ops.alertEvents.loading') }}
    </div>

    <div v-else-if="empty" class="rounded-md border border-dashed border-border p-8 text-center text-sm text-muted-foreground">
      {{ t('admin.ops.alertEvents.empty') }}
    </div>

    <div v-else class="overflow-hidden rounded-md border border-border">
      <div class="max-h-[600px] overflow-y-auto" @scroll="onScroll">
        <table class="min-w-full divide-y divide-border">
          <thead class="sticky top-0 z-10 bg-muted">
            <tr>
              <th class="px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.time') }}
              </th>
              <th class="px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.severity') }}
              </th>
              <th class="px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.platform') }}
              </th>
              <th class="px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.ruleId') }}
              </th>
              <th class="px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.title') }}
              </th>
              <th class="px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.duration') }}
              </th>
              <th class="px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.dimensions') }}
              </th>
              <th class="px-4 py-3 text-right text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                {{ t('admin.ops.alertEvents.table.email') }}
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-border bg-card">
            <tr
              v-for="row in events"
              :key="row.id"
              class="cursor-pointer hover:bg-accent"
              @click="openDetail(row)"
              :title="row.title || ''"
            >
              <td class="whitespace-nowrap px-4 py-3 text-xs text-foreground/85">
                {{ formatDateTime(row.fired_at || row.created_at) }}
              </td>
              <td class="whitespace-nowrap px-4 py-3">
                <div class="flex items-center gap-2">
                  <span class="rounded-full px-2 py-1 text-[10px] font-bold" :class="severityBadgeClass(String(row.severity || ''))">
                    {{ row.severity || '-' }}
                  </span>
                  <span class="inline-flex items-center rounded-full px-2 py-1 text-[10px] font-bold ring-1 ring-inset" :class="statusBadgeClass(row.status)">
                    {{ formatStatusLabel(row.status) }}
                  </span>
                </div>
              </td>
              <td class="whitespace-nowrap px-4 py-3 text-xs text-foreground/85">
                {{ getDimensionString(row, 'platform') || '-' }}
              </td>
              <td class="whitespace-nowrap px-4 py-3 text-xs text-foreground/85">
                <span class="font-mono">#{{ row.rule_id }}</span>
              </td>
              <td class="min-w-[260px] px-4 py-3 text-xs text-foreground/85">
                <div class="font-semibold truncate max-w-[360px]">{{ row.title || '-' }}</div>
                <div v-if="row.description" class="mt-0.5 line-clamp-2 text-[11px] text-muted-foreground">
                  {{ row.description }}
                </div>
              </td>
              <td class="whitespace-nowrap px-4 py-3 text-xs text-foreground/85">
                {{ formatDurationLabel(row) }}
              </td>
              <td class="whitespace-nowrap px-4 py-3 text-[11px] text-muted-foreground">
                {{ formatDimensionsSummary(row) }}
              </td>
              <td class="whitespace-nowrap px-4 py-3 text-right text-xs">
                <span
                  class="inline-flex items-center justify-end gap-1.5"
                  :title="row.email_sent ? t('admin.ops.alertEvents.table.emailSent') : t('admin.ops.alertEvents.table.emailIgnored')"
                >
                  <Icon
                    v-if="row.email_sent"
                    name="checkCircle"
                    size="sm"
                    class="text-emerald-400"
                  />
                  <Icon
                    v-else
                    name="ban"
                    size="sm"
                    class="text-muted-foreground"
                  />
                  <span class="text-[11px] font-bold text-foreground/85">
                    {{ row.email_sent ? t('admin.ops.alertEvents.table.emailSent') : t('admin.ops.alertEvents.table.emailIgnored') }}
                  </span>
                </span>
              </td>
            </tr>
          </tbody>
        </table>
        <div v-if="loadingMore" class="flex items-center justify-center gap-2 py-3 text-xs text-muted-foreground">
          <svg class="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          {{ t('admin.ops.alertEvents.loading') }}
        </div>
        <div v-else-if="!hasMore && events.length > 0" class="py-3 text-center text-xs text-muted-foreground">
          -
        </div>
      </div>
    </div>

    <BaseDialog
      :show="showDetail"
      :title="t('admin.ops.alertEvents.detail.title')"
      width="wide"
      :close-on-click-outside="true"
      @close="closeDetail"
    >
      <div v-if="detailLoading" class="flex items-center justify-center py-10 text-sm text-muted-foreground">
        {{ t('admin.ops.alertEvents.detail.loading') }}
      </div>

      <div v-else-if="!selected" class="py-10 text-center text-sm text-muted-foreground">
        {{ t('admin.ops.alertEvents.detail.empty') }}
      </div>

      <div v-else class="space-y-5">
        <div class="rounded-md bg-muted p-4">
          <div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <div class="flex flex-wrap items-center gap-2">
                <span class="inline-flex items-center rounded-full px-2 py-1 text-[10px] font-bold" :class="severityBadgeClass(String(selected.severity || ''))">
                  {{ selected.severity || '-' }}
                </span>
                <span class="inline-flex items-center rounded-full px-2 py-1 text-[10px] font-bold ring-1 ring-inset" :class="statusBadgeClass(selected.status)">
                  {{ formatStatusLabel(selected.status) }}
                </span>
              </div>
              <div class="mt-2 text-sm font-semibold text-foreground">
                {{ selected.title || '-' }}
              </div>
              <div v-if="selected.description" class="mt-1 whitespace-pre-wrap text-xs text-foreground/85">
                {{ selected.description }}
              </div>
            </div>

            <div class="flex flex-wrap gap-2">
              <div class="flex items-center gap-2 rounded-md bg-card px-2 py-1 border border-border">
                <span class="text-[11px] font-bold text-foreground/85">{{ t('admin.ops.alertEvents.detail.silence') }}</span>
                <Select
                  :model-value="silenceDuration"
                  :options="silenceDurationOptions"
                  class="w-[110px]"
                  @change="silenceDuration = String($event || '1h')"
                />
                <button type="button" class="btn btn-secondary btn-sm" :disabled="detailActionLoading" @click="silenceAlert">
                  <Icon name="ban" size="sm" />
                  {{ t('common.apply') }}
                </button>
              </div>

              <button type="button" class="btn btn-secondary btn-sm" :disabled="detailActionLoading" @click="manualResolve">
                <Icon name="checkCircle" size="sm" />
                {{ t('admin.ops.alertEvents.detail.manualResolve') }}
              </button>
            </div>
          </div>
        </div>

          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div class="rounded-md bg-muted p-4">
              <div class="text-xs font-bold uppercase tracking-wider text-muted-foreground">{{ t('admin.ops.alertEvents.detail.firedAt') }}</div>
              <div class="mt-1 text-sm font-medium text-foreground">{{ formatDateTime(selected.fired_at || selected.created_at) }}</div>
            </div>
            <div class="rounded-md bg-muted p-4">
              <div class="text-xs font-bold uppercase tracking-wider text-muted-foreground">{{ t('admin.ops.alertEvents.detail.resolvedAt') }}</div>
              <div class="mt-1 text-sm font-medium text-foreground">{{ selected.resolved_at ? formatDateTime(selected.resolved_at) : '-' }}</div>
            </div>
            <div class="rounded-md bg-muted p-4">
              <div class="text-xs font-bold uppercase tracking-wider text-muted-foreground">{{ t('admin.ops.alertEvents.detail.ruleId') }}</div>
              <div class="mt-1 flex flex-wrap items-center gap-2">
                <div class="font-mono text-sm font-bold text-foreground">#{{ selected.rule_id }}</div>
                <a
                  class="inline-flex items-center gap-1 rounded-md bg-card px-2 py-1 text-[11px] font-bold text-foreground/85 border border-border hover:bg-accent"
                  :href="`/admin/ops?open_alert_rules=1&alert_rule_id=${selected.rule_id}`"
                >
                  <Icon name="externalLink" size="xs" />
                  {{ t('admin.ops.alertEvents.detail.viewRule') }}
                </a>
                <a
                  class="inline-flex items-center gap-1 rounded-md bg-card px-2 py-1 text-[11px] font-bold text-foreground/85 border border-border hover:bg-accent"
                  :href="`/admin/ops?platform=${encodeURIComponent(getDimensionString(selected,'platform')||'')}&group_id=${selected.dimensions?.group_id || ''}&error_type=request&open_error_details=1`"
                >
                  <Icon name="externalLink" size="xs" />
                  {{ t('admin.ops.alertEvents.detail.viewLogs') }}
                </a>
              </div>
            </div>
            <div class="rounded-md bg-muted p-4">
              <div class="text-xs font-bold uppercase tracking-wider text-muted-foreground">{{ t('admin.ops.alertEvents.detail.dimensions') }}</div>
              <div class="mt-1 text-sm text-foreground">
                <div v-if="getDimensionString(selected, 'platform')">platform={{ getDimensionString(selected, 'platform') }}</div>
                <div v-if="selected.dimensions?.group_id">group_id={{ selected.dimensions.group_id }}</div>
                <div v-if="getDimensionString(selected, 'region')">region={{ getDimensionString(selected, 'region') }}</div>
              </div>
            </div>
          </div>


        <div class="rounded-md border border-border bg-card p-4">
          <div class="mb-3 flex flex-wrap items-center justify-between gap-3">
            <div>
              <div class="text-sm font-bold text-foreground">{{ t('admin.ops.alertEvents.detail.historyTitle') }}</div>
              <div class="mt-0.5 text-xs text-muted-foreground">{{ t('admin.ops.alertEvents.detail.historyHint') }}</div>
            </div>
            <Select :model-value="historyRange" :options="historyRangeOptions" class="w-[140px]" @change="historyRange = String($event || '7d')" />
          </div>

          <div v-if="historyLoading" class="py-6 text-center text-xs text-muted-foreground">
            {{ t('admin.ops.alertEvents.detail.historyLoading') }}
          </div>
          <div v-else-if="history.length === 0" class="py-6 text-center text-xs text-muted-foreground">
            {{ t('admin.ops.alertEvents.detail.historyEmpty') }}
          </div>
          <div v-else class="overflow-hidden rounded-md border border-border">
            <table class="min-w-full divide-y divide-border">
              <thead class="bg-muted">
                <tr>
                  <th class="px-3 py-2 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{{ t('admin.ops.alertEvents.table.time') }}</th>
                  <th class="px-3 py-2 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{{ t('admin.ops.alertEvents.table.status') }}</th>
                  <th class="px-3 py-2 text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{{ t('admin.ops.alertEvents.table.metric') }}</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-border">
                <tr v-for="it in history" :key="it.id" class="hover:bg-accent">
                  <td class="px-3 py-2 text-xs text-foreground/85">{{ formatDateTime(it.fired_at || it.created_at) }}</td>
                  <td class="px-3 py-2 text-xs">
                    <span class="inline-flex items-center rounded-full px-2 py-1 text-[10px] font-bold ring-1 ring-inset" :class="statusBadgeClass(it.status)">
                      {{ formatStatusLabel(it.status) }}
                    </span>
                  </td>
                  <td class="px-3 py-2 text-xs text-foreground/85">
                    <span v-if="typeof it.metric_value === 'number' && typeof it.threshold_value === 'number'">
                      {{ it.metric_value.toFixed(2) }} / {{ it.threshold_value.toFixed(2) }}
                    </span>
                    <span v-else>-</span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </BaseDialog>
  </div>
</template>
