// frontend-svelte/src/lib/registry/special/StreamTimeoutSection.svelte
<script lang="ts">
	/**
	 * StreamTimeoutSection · 流式响应超时处理（M10e · gateway tab）
	 *
	 * 端口自 frontend/src/views/admin/settings-registry/special/StreamTimeoutSection.vue。
	 *
	 * 设计：
	 *   - 与 flat-form 解耦 —— onMount GET /api/admin/settings/stream-timeout，
	 *     Save 触发 PUT 整体替换；不进 patchSettings 流水线（同 OverloadCooldown 模式）。
	 *   - enable + action select + 3 number inputs，subfields 仅在 enabled 时露面。
	 *   - temp_unsched_minutes 仅在 action='temp_unsched' 时露面。
	 *   - select 严格 sentinel-safe —— 三个具体值 temp_unsched|error|none，绝无空 value。
	 */
	import { onMount } from 'svelte';
	import { _ } from 'svelte-i18n';
	import {
		settingsApi,
		type StreamTimeoutSettings
	} from '$lib/api/admin/settingsRegistry';
	import { showError, showSuccess } from '$lib/stores/toast.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Input from '$lib/ui/Input.svelte';
	import NativeSelect from '$lib/ui/NativeSelect.svelte';

	type FieldUpdate = { key: string; value: unknown };

	type Props = {
		values?: Record<string, unknown>;
		dirtyKeys?: Set<string>;
		onFieldUpdate?: (e: FieldUpdate) => void;
	};

	// 不消费 props 字段 —— 仅匹配 SectionRenderer 契约。
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	const { values: _v, dirtyKeys: _d, onFieldUpdate: _f }: Props = $props();

	let loading = $state(true);
	let saving = $state(false);
	let form = $state<StreamTimeoutSettings>({
		enabled: true,
		action: 'temp_unsched',
		temp_unsched_minutes: 5,
		threshold_count: 3,
		threshold_window_minutes: 10
	});

	onMount(async () => {
		loading = true;
		try {
			const settings = await settingsApi.getStreamTimeoutSettings();
			form = { ...form, ...settings };
		} catch {
			// 静默：form 留默认值。
		} finally {
			loading = false;
		}
	});

	function toggleEnabled() {
		form = { ...form, enabled: !form.enabled };
	}

	function onActionChange(e: Event) {
		const raw = (e.target as HTMLSelectElement).value as 'temp_unsched' | 'error' | 'none';
		form = { ...form, action: raw };
	}

	function onNumberInput(key: keyof StreamTimeoutSettings, e: Event) {
		const raw = (e.target as HTMLInputElement).value;
		const num = raw === '' ? 0 : Number(raw);
		form = { ...form, [key]: num } as StreamTimeoutSettings;
	}

	async function save() {
		saving = true;
		try {
			const updated = await settingsApi.updateStreamTimeoutSettings({
				enabled: form.enabled,
				action: form.action,
				temp_unsched_minutes: form.temp_unsched_minutes,
				threshold_count: form.threshold_count,
				threshold_window_minutes: form.threshold_window_minutes
			});
			form = { ...form, ...updated };
			showSuccess($_('admin.settings.streamTimeout.saved'));
		} catch (err) {
			showError(
				err instanceof Error ? err.message : $_('admin.settings.streamTimeout.saveFailed')
			);
		} finally {
			saving = false;
		}
	}
</script>

<div class="flex flex-col gap-4" data-special="stream-timeout">
	{#if loading}
		<div
			data-testid="stream-timeout-loading"
			class="flex items-center gap-2 text-sm text-muted-foreground"
		>
			{$_('common.loading')}
		</div>
	{:else}
		<!-- enabled toggle -->
		<div class="flex items-center justify-between gap-4">
			<div class="min-w-0">
				<label
					class="block text-sm font-medium text-foreground"
					for="stream-timeout-enabled"
				>
					{$_('admin.settings.streamTimeout.enabled')}
				</label>
				<p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">
					{$_('admin.settings.streamTimeout.enabledHint')}
				</p>
			</div>
			<Button
				id="stream-timeout-enabled"
				variant="ghost"
				size="icon"
				role="switch"
				aria-checked={form.enabled}
				aria-label={$_('admin.settings.streamTimeout.enabled')}
				data-testid="stream-timeout-enabled"
				data-checked={form.enabled}
				onclick={toggleEnabled}
				class="relative inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full transition-colors {form.enabled
					? 'bg-primary'
					: 'bg-muted'}"
			>
				<span
					class="inline-block h-4 w-4 transform rounded-full bg-white transition-transform {form.enabled
						? 'translate-x-4'
						: 'translate-x-0.5'}"
				></span>
			</Button>
		</div>

		{#if form.enabled}
			<div class="flex flex-col gap-3 border-t border-border pt-4">
				<!-- action select -->
				<div class="flex flex-col gap-1">
					<label
						class="text-xs font-medium text-muted-foreground"
						for="stream-timeout-action"
					>
						{$_('admin.settings.streamTimeout.action')}
					</label>
					<NativeSelect
						id="stream-timeout-action"
						data-testid="stream-timeout-action"
						value={form.action}
						onchange={onActionChange}
						class="h-9 w-64"
					>
						<option value="temp_unsched"
							>{$_('admin.settings.streamTimeout.actionTempUnsched')}</option
						>
						<option value="error">{$_('admin.settings.streamTimeout.actionError')}</option>
						<option value="none">{$_('admin.settings.streamTimeout.actionNone')}</option>
					</NativeSelect>
					<p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">
						{$_('admin.settings.streamTimeout.actionHint')}
					</p>
				</div>

				{#if form.action === 'temp_unsched'}
					<div class="flex flex-col gap-1">
						<label
							class="text-xs font-medium text-muted-foreground"
							for="stream-timeout-temp-unsched-minutes"
						>
							{$_('admin.settings.streamTimeout.tempUnschedMinutes')}
						</label>
						<Input
							id="stream-timeout-temp-unsched-minutes"
							type="number"
							min="1"
							max="60"
							data-testid="stream-timeout-temp-unsched-minutes"
							value={form.temp_unsched_minutes}
							oninput={(e) => onNumberInput('temp_unsched_minutes', e)}
							class="h-9 w-32 font-mono"
						/>
						<p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">
							{$_('admin.settings.streamTimeout.tempUnschedMinutesHint')}
						</p>
					</div>
				{/if}

				<div class="flex flex-col gap-1">
					<label
						class="text-xs font-medium text-muted-foreground"
						for="stream-timeout-threshold-count"
					>
						{$_('admin.settings.streamTimeout.thresholdCount')}
					</label>
					<Input
						id="stream-timeout-threshold-count"
						type="number"
						min="1"
						max="10"
						data-testid="stream-timeout-threshold-count"
						value={form.threshold_count}
						oninput={(e) => onNumberInput('threshold_count', e)}
						class="h-9 w-32 font-mono"
					/>
					<p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">
						{$_('admin.settings.streamTimeout.thresholdCountHint')}
					</p>
				</div>

				<div class="flex flex-col gap-1">
					<label
						class="text-xs font-medium text-muted-foreground"
						for="stream-timeout-threshold-window-minutes"
					>
						{$_('admin.settings.streamTimeout.thresholdWindowMinutes')}
					</label>
					<Input
						id="stream-timeout-threshold-window-minutes"
						type="number"
						min="1"
						max="60"
						data-testid="stream-timeout-threshold-window-minutes"
						value={form.threshold_window_minutes}
						oninput={(e) => onNumberInput('threshold_window_minutes', e)}
						class="h-9 w-32 font-mono"
					/>
					<p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">
						{$_('admin.settings.streamTimeout.thresholdWindowMinutesHint')}
					</p>
				</div>
			</div>
		{/if}

		<div class="flex justify-end border-t border-border pt-4">
			<Button
				variant="outline"
				class="h-9"
				data-testid="stream-timeout-save"
				disabled={saving}
				onclick={save}
			>
				{saving ? $_('common.saving') : $_('common.save')}
			</Button>
		</div>
	{/if}
</div>

// frontend/src/views/admin/settings-registry/special/StreamTimeoutSection.vue
<template>
  <div class="flex flex-col gap-4 px-5 py-4">
    <!-- loading -->
    <div v-if="loading" class="flex items-center gap-2 text-[13px] text-muted-foreground">
      <div class="h-4 w-4 flex-shrink-0 animate-spin rounded-full border-2 border-border border-b-primary" />
      {{ t('common.loading') }}
    </div>

    <template v-else>
      <!-- enabled switch -->
      <div class="flex items-center justify-between gap-4">
        <div>
          <Label class="text-[13px] font-medium text-foreground">{{ t('admin.settings.streamTimeout.enabled') }}</Label>
          <p class="mt-0.5 text-[11.5px] leading-relaxed text-muted-foreground">{{ t('admin.settings.streamTimeout.enabledHint') }}</p>
        </div>
        <Toggle v-model="form.enabled" />
      </div>

      <!-- expanded fields — only when enabled -->
      <div v-if="form.enabled" class="flex flex-col gap-3.5 border-t border-border pt-4">

        <!-- action select -->
        <div class="flex flex-col gap-1">
          <Label class="text-xs font-medium text-muted-foreground">{{ t('admin.settings.streamTimeout.action') }}</Label>
          <Select v-model="form.action">
            <SelectTrigger class="w-64">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="temp_unsched">{{ t('admin.settings.streamTimeout.actionTempUnsched') }}</SelectItem>
              <SelectItem value="error">{{ t('admin.settings.streamTimeout.actionError') }}</SelectItem>
              <SelectItem value="none">{{ t('admin.settings.streamTimeout.actionNone') }}</SelectItem>
            </SelectContent>
          </Select>
          <p class="mt-0.5 text-[11px] leading-relaxed text-muted-foreground">{{ t('admin.settings.streamTimeout.actionHint') }}</p>
        </div>

        <!-- temp_unsched_minutes — gated on action -->
        <div v-if="form.action === 'temp_unsched'" class="flex flex-col gap-1">
          <Label class="text-xs font-medium text-muted-foreground">{{ t('admin.settings.streamTimeout.tempUnschedMinutes') }}</Label>
          <Input
            v-model.number="form.temp_unsched_minutes"
            type="number"
            min="1"
            max="60"
            class="w-32 font-mono"
          />
          <p class="mt-0.5 text-[11px] leading-relaxed text-muted-foreground">{{ t('admin.settings.streamTimeout.tempUnschedMinutesHint') }}</p>
        </div>

        <!-- threshold_count -->
        <div class="flex flex-col gap-1">
          <Label class="text-xs font-medium text-muted-foreground">{{ t('admin.settings.streamTimeout.thresholdCount') }}</Label>
          <Input
            v-model.number="form.threshold_count"
            type="number"
            min="1"
            max="10"
            class="w-32 font-mono"
          />
          <p class="mt-0.5 text-[11px] leading-relaxed text-muted-foreground">{{ t('admin.settings.streamTimeout.thresholdCountHint') }}</p>
        </div>

        <!-- threshold_window_minutes -->
        <div class="flex flex-col gap-1">
          <Label class="text-xs font-medium text-muted-foreground">{{ t('admin.settings.streamTimeout.thresholdWindowMinutes') }}</Label>
          <Input
            v-model.number="form.threshold_window_minutes"
            type="number"
            min="1"
            max="60"
            class="w-32 font-mono"
          />
          <p class="mt-0.5 text-[11px] leading-relaxed text-muted-foreground">{{ t('admin.settings.streamTimeout.thresholdWindowMinutesHint') }}</p>
        </div>
      </div>

      <!-- save -->
      <div class="flex justify-end border-t border-border pt-4">
        <Button
          type="button"
          variant="outline"
          size="sm"
          :disabled="saving"
          @click="save"
        >
          <svg
            v-if="saving"
            class="h-3.5 w-3.5 animate-spin"
            fill="none"
            viewBox="0 0 24 24"
          >
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          {{ saving ? t('common.saving') : t('common.save') }}
        </Button>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import Toggle from '@/components/common/Toggle.vue'
import { adminAPI } from '@/api/admin'
import { useAppStore } from '@/stores'
import { extractApiErrorMessage } from '@/utils/apiError'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

const { t } = useI18n()
const appStore = useAppStore()

const loading = ref(true)
const saving = ref(false)

const form = reactive({
  enabled: true,
  action: 'temp_unsched' as 'temp_unsched' | 'error' | 'none',
  temp_unsched_minutes: 5,
  threshold_count: 3,
  threshold_window_minutes: 10,
})

onMounted(async () => {
  loading.value = true
  try {
    const settings = await adminAPI.settings.getStreamTimeoutSettings()
    Object.assign(form, settings)
  } catch {
    // silent — form stays at defaults
  } finally {
    loading.value = false
  }
})

async function save() {
  saving.value = true
  try {
    const updated = await adminAPI.settings.updateStreamTimeoutSettings({
      enabled: form.enabled,
      action: form.action,
      temp_unsched_minutes: form.temp_unsched_minutes,
      threshold_count: form.threshold_count,
      threshold_window_minutes: form.threshold_window_minutes,
    })
    Object.assign(form, updated)
    appStore.showSuccess(t('admin.settings.streamTimeout.saved'))
  } catch (error: unknown) {
    appStore.showError(
      extractApiErrorMessage(error, t('admin.settings.streamTimeout.saveFailed')),
    )
  } finally {
    saving.value = false
  }
}
</script>
