// frontend/src/views/admin/ops/components/OpsAlertRulesCard.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useAppStore } from '@/stores/app'
import BaseDialog from '@/components/common/BaseDialog.vue'
import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import { adminAPI } from '@/api'
import { opsAPI } from '@/api/admin/ops'
import type { AlertRule, MetricType, Operator } from '../types'
import type { SelectOption } from '@/types'
import type { OpsSeverity } from '@/api/admin/ops'
import { formatDateTime } from '../utils/opsFormatters'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/table'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select'

const { t } = useI18n()
const appStore = useAppStore()

const loading = ref(false)
const rules = ref<AlertRule[]>([])

async function load() {
  loading.value = true
  try {
    rules.value = await opsAPI.listAlertRules()
  } catch (err: any) {
    console.error('[OpsAlertRulesCard] Failed to load rules', err)
    appStore.showError(err?.response?.data?.detail || t('admin.ops.alertRules.loadFailed'))
    rules.value = []
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  load()
  loadGroups()
})

const sortedRules = computed(() => {
  return [...rules.value].sort((a, b) => (b.id || 0) - (a.id || 0))
})

const showEditor = ref(false)
const saving = ref(false)
const editingId = ref<number | null>(null)
const draft = ref<AlertRule | null>(null)

type MetricGroup = 'system' | 'group' | 'account'

interface MetricDefinition {
  type: MetricType
  group: MetricGroup
  label: string
  description: string
  recommendedOperator: Operator
  recommendedThreshold: number
  unit?: string
}

const groupMetricTypes = new Set<MetricType>([
  'group_available_accounts',
  'group_available_ratio',
  'group_rate_limit_ratio'
])

function parsePositiveInt(value: unknown): number | null {
  if (value == null) return null
  if (typeof value === 'boolean') return null
  const n = typeof value === 'number' ? value : Number.parseInt(String(value), 10)
  return Number.isFinite(n) && n > 0 ? n : null
}

const groupOptionsBase = ref<SelectOption[]>([])

async function loadGroups() {
  try {
    const list = await adminAPI.groups.getAll()
    groupOptionsBase.value = list.map((g) => ({ value: g.id, label: g.name }))
  } catch (err) {
    console.error('[OpsAlertRulesCard] Failed to load groups', err)
    groupOptionsBase.value = []
  }
}

const isGroupMetricSelected = computed(() => {
  const metricType = draft.value?.metric_type
  return metricType ? groupMetricTypes.has(metricType) : false
})

const draftGroupId = computed<number | null>({
  get() {
    return parsePositiveInt(draft.value?.filters?.group_id)
  },
  set(value) {
    if (!draft.value) return
    if (value == null) {
      if (!draft.value.filters) return
      delete draft.value.filters.group_id
      if (Object.keys(draft.value.filters).length === 0) {
        delete draft.value.filters
      }
      return
    }
    if (!draft.value.filters) draft.value.filters = {}
    draft.value.filters.group_id = value
  }
})

const groupOptions = computed<SelectOption[]>(() => {
  if (isGroupMetricSelected.value) return groupOptionsBase.value
  return [{ value: null, label: t('admin.ops.alertRules.form.allGroups') }, ...groupOptionsBase.value]
})

const metricDefinitions = computed(() => {
  return [
    // System-level metrics
    {
      type: 'success_rate',
      group: 'system',
      label: t('admin.ops.alertRules.metrics.successRate'),
      description: t('admin.ops.alertRules.metricDescriptions.successRate'),
      recommendedOperator: '<',
      recommendedThreshold: 99,
      unit: '%'
    },
    {
      type: 'error_rate',
      group: 'system',
      label: t('admin.ops.alertRules.metrics.errorRate'),
      description: t('admin.ops.alertRules.metricDescriptions.errorRate'),
      recommendedOperator: '>',
      recommendedThreshold: 1,
      unit: '%'
    },
    {
      type: 'upstream_error_rate',
      group: 'system',
      label: t('admin.ops.alertRules.metrics.upstreamErrorRate'),
      description: t('admin.ops.alertRules.metricDescriptions.upstreamErrorRate'),
      recommendedOperator: '>',
      recommendedThreshold: 1,
      unit: '%'
    },
    {
      type: 'cpu_usage_percent',
      group: 'system',
      label: t('admin.ops.alertRules.metrics.cpu'),
      description: t('admin.ops.alertRules.metricDescriptions.cpu'),
      recommendedOperator: '>',
      recommendedThreshold: 80,
      unit: '%'
    },
    {
      type: 'memory_usage_percent',
      group: 'system',
      label: t('admin.ops.alertRules.metrics.memory'),
      description: t('admin.ops.alertRules.metricDescriptions.memory'),
      recommendedOperator: '>',
      recommendedThreshold: 80,
      unit: '%'
    },
    {
      type: 'concurrency_queue_depth',
      group: 'system',
      label: t('admin.ops.alertRules.metrics.queueDepth'),
      description: t('admin.ops.alertRules.metricDescriptions.queueDepth'),
      recommendedOperator: '>',
      recommendedThreshold: 10
    },

    // Group-level metrics (requires group_id filter)
    {
      type: 'group_available_accounts',
      group: 'group',
      label: t('admin.ops.alertRules.metrics.groupAvailableAccounts'),
      description: t('admin.ops.alertRules.metricDescriptions.groupAvailableAccounts'),
      recommendedOperator: '<',
      recommendedThreshold: 1
    },
    {
      type: 'group_available_ratio',
      group: 'group',
      label: t('admin.ops.alertRules.metrics.groupAvailableRatio'),
      description: t('admin.ops.alertRules.metricDescriptions.groupAvailableRatio'),
      recommendedOperator: '<',
      recommendedThreshold: 50,
      unit: '%'
    },
    {
      type: 'group_rate_limit_ratio',
      group: 'group',
      label: t('admin.ops.alertRules.metrics.groupRateLimitRatio'),
      description: t('admin.ops.alertRules.metricDescriptions.groupRateLimitRatio'),
      recommendedOperator: '>',
      recommendedThreshold: 10,
      unit: '%'
    },

    // Account-level metrics
    {
      type: 'account_rate_limited_count',
      group: 'account',
      label: t('admin.ops.alertRules.metrics.accountRateLimitedCount'),
      description: t('admin.ops.alertRules.metricDescriptions.accountRateLimitedCount'),
      recommendedOperator: '>',
      recommendedThreshold: 0
    },
    {
      type: 'account_error_count',
      group: 'account',
      label: t('admin.ops.alertRules.metrics.accountErrorCount'),
      description: t('admin.ops.alertRules.metricDescriptions.accountErrorCount'),
      recommendedOperator: '>',
      recommendedThreshold: 0
    },
    {
      type: 'account_error_ratio',
      group: 'account',
      label: t('admin.ops.alertRules.metrics.accountErrorRatio'),
      description: t('admin.ops.alertRules.metricDescriptions.accountErrorRatio'),
      recommendedOperator: '>',
      recommendedThreshold: 5,
      unit: '%'
    },
    {
      type: 'account_temp_unscheduled_count',
      group: 'account',
      label: t('admin.ops.alertRules.metrics.accountTempUnscheduledCount'),
      description: t('admin.ops.alertRules.metricDescriptions.accountTempUnscheduledCount'),
      recommendedOperator: '>',
      recommendedThreshold: 0
    },
    {
      type: 'overload_account_count',
      group: 'account',
      label: t('admin.ops.alertRules.metrics.overloadAccountCount'),
      description: t('admin.ops.alertRules.metricDescriptions.overloadAccountCount'),
      recommendedOperator: '>',
      recommendedThreshold: 0
    }
  ] satisfies MetricDefinition[]
})

const selectedMetricDefinition = computed(() => {
  const metricType = draft.value?.metric_type
  if (!metricType) return null
  return metricDefinitions.value.find((m) => m.type === metricType) ?? null
})

const metricOptions = computed(() => {
  const buildGroup = (group: MetricGroup): SelectOption[] => {
    const items = metricDefinitions.value.filter((m) => m.group === group)
    if (items.length === 0) return []
    const headerValue = `__group__${group}`
    return [
      {
        value: headerValue,
        label: t(`admin.ops.alertRules.metricGroups.${group}`),
        disabled: true,
        kind: 'group'
      },
      ...items.map((m) => ({ value: m.type, label: m.label }))
    ]
  }

  return [...buildGroup('system'), ...buildGroup('group'), ...buildGroup('account')]
})

const operatorOptions = computed(() => {
  const ops: Operator[] = ['>', '>=', '<', '<=', '==', '!=']
  return ops.map((o) => ({ value: o, label: o }))
})

const severityOptions = computed(() => {
  const sev: OpsSeverity[] = ['P0', 'P1', 'P2', 'P3']
  return sev.map((s) => ({ value: s, label: s }))
})

const windowOptions = computed(() => {
  const windows = [1, 5, 60]
  return windows.map((m) => ({ value: m, label: `${m}m` }))
})

function newRuleDraft(): AlertRule {
  return {
    name: '',
    description: '',
    enabled: true,
    metric_type: 'error_rate',
    operator: '>',
    threshold: 1,
    window_minutes: 1,
    sustained_minutes: 2,
    severity: 'P1',
    cooldown_minutes: 10,
    notify_email: true
  }
}

function openCreate() {
  editingId.value = null
  draft.value = newRuleDraft()
  showEditor.value = true
}

function openEdit(rule: AlertRule) {
  editingId.value = rule.id ?? null
  draft.value = JSON.parse(JSON.stringify(rule))
  showEditor.value = true
}

const editorValidation = computed(() => {
  const errors: string[] = []
  const r = draft.value
  if (!r) return { valid: true, errors }
  if (!r.name || !r.name.trim()) errors.push(t('admin.ops.alertRules.validation.nameRequired'))
  if (!r.metric_type) errors.push(t('admin.ops.alertRules.validation.metricRequired'))
  if (groupMetricTypes.has(r.metric_type) && !parsePositiveInt(r.filters?.group_id)) {
    errors.push(t('admin.ops.alertRules.validation.groupIdRequired'))
  }
  if (!r.operator) errors.push(t('admin.ops.alertRules.validation.operatorRequired'))
  if (!(typeof r.threshold === 'number' && Number.isFinite(r.threshold)))
    errors.push(t('admin.ops.alertRules.validation.thresholdRequired'))
  if (!(typeof r.window_minutes === 'number' && Number.isFinite(r.window_minutes) && [1, 5, 60].includes(r.window_minutes))) {
    errors.push(t('admin.ops.alertRules.validation.windowRange'))
  }
  if (!(typeof r.sustained_minutes === 'number' && Number.isFinite(r.sustained_minutes) && r.sustained_minutes >= 1 && r.sustained_minutes <= 1440)) {
    errors.push(t('admin.ops.alertRules.validation.sustainedRange'))
  }
  if (!(typeof r.cooldown_minutes === 'number' && Number.isFinite(r.cooldown_minutes) && r.cooldown_minutes >= 0 && r.cooldown_minutes <= 1440)) {
    errors.push(t('admin.ops.alertRules.validation.cooldownRange'))
  }
  return { valid: errors.length === 0, errors }
})

async function save() {
  if (!draft.value) return
  if (!editorValidation.value.valid) {
    appStore.showError(editorValidation.value.errors[0] || t('admin.ops.alertRules.validation.invalid'))
    return
  }
  saving.value = true
  try {
    if (editingId.value) {
      await opsAPI.updateAlertRule(editingId.value, draft.value)
    } else {
      await opsAPI.createAlertRule(draft.value)
    }
    showEditor.value = false
    draft.value = null
    editingId.value = null
    await load()
    appStore.showSuccess(t('admin.ops.alertRules.saveSuccess'))
  } catch (err: any) {
    console.error('[OpsAlertRulesCard] Failed to save rule', err)
    appStore.showError(err?.response?.data?.detail || t('admin.ops.alertRules.saveFailed'))
  } finally {
    saving.value = false
  }
}

const showDeleteConfirm = ref(false)
const pendingDelete = ref<AlertRule | null>(null)

function requestDelete(rule: AlertRule) {
  pendingDelete.value = rule
  showDeleteConfirm.value = true
}

async function confirmDelete() {
  if (!pendingDelete.value?.id) return
  try {
    await opsAPI.deleteAlertRule(pendingDelete.value.id)
    showDeleteConfirm.value = false
    pendingDelete.value = null
    await load()
    appStore.showSuccess(t('admin.ops.alertRules.deleteSuccess'))
  } catch (err: any) {
    console.error('[OpsAlertRulesCard] Failed to delete rule', err)
    appStore.showError(err?.response?.data?.detail || t('admin.ops.alertRules.deleteFailed'))
  }
}

function cancelDelete() {
  showDeleteConfirm.value = false
  pendingDelete.value = null
}
</script>

<template>
  <Card>
    <CardContent class="p-6">
      <div class="mb-3.5 flex items-start justify-between gap-3">
        <div>
          <h3 class="flex items-center gap-2 text-[13px] font-bold text-foreground">{{ t('admin.ops.alertRules.title') }}</h3>
          <p class="mt-0.5 text-[11.5px] text-muted-foreground">{{ t('admin.ops.alertRules.description') }}</p>
        </div>
        <div class="flex items-center gap-1.5">
          <Button variant="outline" size="sm" class="h-7 px-2.5 text-[11px]" :disabled="loading" @click="openCreate">{{ t('admin.ops.alertRules.create') }}</Button>
          <Button variant="outline" size="icon" class="h-7 w-7" :disabled="loading" :aria-label="t('common.refresh')" @click="load">
            <svg width="13" height="13" :class="{ 'animate-spin': loading }" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
            <span class="sr-only">{{ t('common.refresh') }}</span>
          </Button>
        </div>
      </div>

      <div v-if="loading" class="py-7 text-center text-[13px] text-muted-foreground">{{ t('admin.ops.alertRules.loading') }}</div>

      <div v-else-if="sortedRules.length === 0" class="rounded-lg border border-dashed border-border px-7 py-7 text-center text-[13px] text-muted-foreground">{{ t('admin.ops.alertRules.empty') }}</div>

      <div v-else class="overflow-hidden rounded-xl border border-border" style="max-height:520px;">
        <div style="max-height:520px;overflow-y:auto;">
          <Table>
            <TableHeader class="sticky top-0 z-10 bg-muted">
              <TableRow>
                <TableHead class="px-3.5 py-2.5 text-[10px] font-bold uppercase tracking-[.06em] text-muted-foreground">{{ t('admin.ops.alertRules.table.name') }}</TableHead>
                <TableHead class="px-3.5 py-2.5 text-[10px] font-bold uppercase tracking-[.06em] text-muted-foreground">{{ t('admin.ops.alertRules.table.metric') }}</TableHead>
                <TableHead class="px-3.5 py-2.5 text-[10px] font-bold uppercase tracking-[.06em] text-muted-foreground">{{ t('admin.ops.alertRules.table.severity') }}</TableHead>
                <TableHead class="px-3.5 py-2.5 text-[10px] font-bold uppercase tracking-[.06em] text-muted-foreground">{{ t('admin.ops.alertRules.table.enabled') }}</TableHead>
                <TableHead class="px-3.5 py-2.5 text-right text-[10px] font-bold uppercase tracking-[.06em] text-muted-foreground">{{ t('admin.ops.alertRules.table.actions') }}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow v-for="row in sortedRules" :key="row.id">
                <TableCell class="px-3.5 py-2.5">
                  <div class="text-[12px] font-bold text-foreground">{{ row.name }}</div>
                  <div v-if="row.description" class="mt-0.5 line-clamp-2 text-[10.5px] text-muted-foreground">{{ row.description }}</div>
                  <div v-if="row.updated_at" class="mt-0.5 text-[10px] text-muted-foreground">{{ formatDateTime(row.updated_at) }}</div>
                </TableCell>
                <TableCell class="whitespace-nowrap px-3.5 py-2.5 text-muted-foreground">
                  <span class="font-mono tabular-nums">{{ row.metric_type }}</span>
                  <span class="mx-1 text-muted-foreground/60">{{ row.operator }}</span>
                  <span class="font-mono tabular-nums">{{ row.threshold }}</span>
                </TableCell>
                <TableCell class="whitespace-nowrap px-3.5 py-2.5 font-bold text-muted-foreground">{{ row.severity }}</TableCell>
                <TableCell class="whitespace-nowrap px-3.5 py-2.5 text-muted-foreground">{{ row.enabled ? t('common.enabled') : t('common.disabled') }}</TableCell>
                <TableCell class="whitespace-nowrap px-3.5 py-2.5 text-right">
                  <Button variant="outline" size="sm" class="h-6 px-2.5 text-[11px]" @click="openEdit(row)">{{ t('common.edit') }}</Button>
                  <Button variant="outline" size="sm" class="ml-1.5 h-6 px-2.5 text-[11px] text-destructive hover:border-destructive/40 hover:text-destructive" @click="requestDelete(row)">{{ t('common.delete') }}</Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>

      <BaseDialog :show="showEditor" :title="editingId ? t('admin.ops.alertRules.editTitle') : t('admin.ops.alertRules.createTitle')" width="wide" @close="showEditor = false">
        <div class="flex flex-col gap-3.5">
          <div v-if="!editorValidation.valid" class="rounded-lg border border-destructive/35 bg-destructive/10 px-3.5 py-2.5 text-[11.5px] text-destructive">
            <div class="font-bold">{{ t('admin.ops.alertRules.validation.title') }}</div>
            <ul class="mt-1 pl-4">
              <li v-for="e in editorValidation.errors" :key="e">{{ e }}</li>
            </ul>
          </div>
          <div class="grid grid-cols-2 gap-3">
            <div class="col-span-2">
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.name') }}</Label>
              <Input v-model="draft!.name" type="text" />
            </div>
            <div class="col-span-2">
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.description') }}</Label>
              <Input v-model="draft!.description" type="text" />
            </div>
            <div>
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.metric') }}</Label>
              <Select v-model="draft!.metric_type">
                <SelectTrigger class="h-8 text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <template v-for="opt in metricOptions" :key="opt.value">
                    <SelectLabel v-if="(opt as any).kind === 'group'" class="text-[10px] font-bold uppercase tracking-wider">{{ opt.label }}</SelectLabel>
                    <SelectItem v-else :value="String(opt.value)">{{ opt.label }}</SelectItem>
                  </template>
                </SelectContent>
              </Select>
              <div v-if="selectedMetricDefinition" class="mt-1 text-[11px] text-muted-foreground">
                <p>{{ selectedMetricDefinition.description }}</p>
                <p>{{ t('admin.ops.alertRules.hints.recommended', { operator: selectedMetricDefinition.recommendedOperator, threshold: selectedMetricDefinition.recommendedThreshold, unit: selectedMetricDefinition.unit || '' }) }}</p>
              </div>
            </div>
            <div>
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.operator') }}</Label>
              <Select v-model="draft!.operator">
                <SelectTrigger class="h-8 text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem v-for="opt in operatorOptions" :key="opt.value" :value="opt.value">{{ opt.label }}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div class="col-span-2">
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.groupId') }}<span v-if="isGroupMetricSelected" class="ml-1 text-destructive">*</span></Label>
              <Select
                :model-value="draftGroupId == null ? '__null__' : String(draftGroupId)"
                @update:model-value="draftGroupId = $event === '__null__' ? null : Number($event)"
              >
                <SelectTrigger class="h-8 text-xs" :class="{ 'border-destructive': isGroupMetricSelected && !draftGroupId }">
                  <SelectValue :placeholder="t('admin.ops.alertRules.form.groupPlaceholder')" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem v-for="opt in groupOptions" :key="String(opt.value)" :value="opt.value == null ? '__null__' : String(opt.value)">{{ opt.label }}</SelectItem>
                </SelectContent>
              </Select>
              <p class="mt-0.5 text-[11px] text-muted-foreground">{{ isGroupMetricSelected ? t('admin.ops.alertRules.hints.groupRequired') : t('admin.ops.alertRules.hints.groupOptional') }}</p>
            </div>
            <div>
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.threshold') }}</Label>
              <Input v-model.number="draft!.threshold" type="number" />
            </div>
            <div>
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.severity') }}</Label>
              <Select v-model="draft!.severity">
                <SelectTrigger class="h-8 text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem v-for="opt in severityOptions" :key="opt.value" :value="opt.value">{{ opt.label }}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.window') }}</Label>
              <Select
                :model-value="draft!.window_minutes != null ? String(draft!.window_minutes) : undefined"
                @update:model-value="draft!.window_minutes = Number($event)"
              >
                <SelectTrigger class="h-8 text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem v-for="opt in windowOptions" :key="opt.value" :value="String(opt.value)">{{ opt.label }}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.sustained') }}</Label>
              <Input v-model.number="draft!.sustained_minutes" type="number" min="1" max="1440" />
            </div>
            <div>
              <Label class="mb-1 block text-[12.5px] font-medium text-muted-foreground">{{ t('admin.ops.alertRules.form.cooldown') }}</Label>
              <Input v-model.number="draft!.cooldown_minutes" type="number" min="0" max="1440" />
            </div>
            <div class="col-span-2 flex items-center justify-between rounded-[10px] border border-border bg-card p-3">
              <span class="text-[11.5px] font-semibold text-muted-foreground">{{ t('admin.ops.alertRules.form.enabled') }}</span>
              <Checkbox v-model="draft!.enabled" />
            </div>
            <div class="col-span-2 flex items-center justify-between rounded-[10px] border border-border bg-card p-3">
              <span class="text-[11.5px] font-semibold text-muted-foreground">{{ t('admin.ops.alertRules.form.notifyEmail') }}</span>
              <Checkbox v-model="draft!.notify_email" />
            </div>
          </div>
        </div>
        <template #footer>
          <div class="flex items-center justify-end gap-2">
            <Button variant="outline" :disabled="saving" @click="showEditor = false">{{ t('common.cancel') }}</Button>
            <Button :disabled="saving" @click="save">{{ saving ? t('common.saving') : t('common.save') }}</Button>
          </div>
        </template>
      </BaseDialog>

      <ConfirmDialog
        :show="showDeleteConfirm"
        :title="t('admin.ops.alertRules.deleteConfirmTitle')"
        :message="t('admin.ops.alertRules.deleteConfirmMessage')"
        :confirmText="t('common.delete')"
        :cancelText="t('common.cancel')"
        @confirm="confirmDelete"
        @cancel="cancelDelete"
      />
    </CardContent>
  </Card>
</template>

// frontend-svelte/src/lib/features/admin-ops/OpsAlertRulesCard.svelte
<script lang="ts">
	/**
	 * OpsAlertRulesCard · Svelte 5 (runes) · Phase C M13
	 *
	 * Vue ref: frontend/src/views/admin/ops/components/OpsAlertRulesCard.vue (05c44218).
	 *
	 * Self-contained CRUD card for ops alert rules. Rendered INSIDE a StandardDialog
	 * opened from the ops filter bar; the PAGE owns the opsMonitoringEnabled gate
	 * (ops.ts gating note: feature flags are read once by the page, not duplicated
	 * per-component — single source of truth).
	 *
	 * Owns:
	 *   - the rules table (loading / empty / error states),
	 *   - the create/edit flow via the co-located OpsAlertRuleEditDialog component,
	 *   - an inline delete-confirm StandardDialog.
	 *
	 * Props are intentionally empty ({}) so the route can drop it in with zero wiring;
	 * data is self-fetched via listOpsAlertRules.
	 *
	 * Red lines:
	 *   - Zinc-only palette; semantic tokens only (no raw hex).
	 *   - NativeSelect (used by the edit dialog) keeps non-empty sentinels.
	 *   - Reuse lib/ui primitives + the shared edit dialog; no duplicated editor.
	 *   - No top-level chart.js import (this card renders no chart; TDZ trap N/A).
	 */
	import { onMount } from 'svelte';
	import { _ } from 'svelte-i18n';
	import { Pencil, Trash2, RefreshCw, Plus } from '@lucide/svelte';
	import {
		listOpsAlertRules,
		deleteOpsAlertRule,
		updateOpsAlertRule,
		type AlertRule,
		type OpsSeverity
	} from '$lib/api/admin/ops';
	import { showError, showSuccess } from '$lib/stores/toast.svelte';
	import Alert from '$lib/ui/Alert.svelte';
	import Badge from '$lib/ui/Badge.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Card from '$lib/ui/Card.svelte';
	import Checkbox from '$lib/ui/Checkbox.svelte';
	import StandardDialog from '$lib/ui/StandardDialog.svelte';
	import OpsAlertRuleEditDialog, {
		METRIC_DEFINITIONS
	} from './OpsAlertRuleEditDialog.svelte';

	// ── local types ──────────────────────────────────────────────────────
	type LoadState = 'idle' | 'loading' | 'ready' | 'error';

	function metricLabel(type: string): string {
		const def = METRIC_DEFINITIONS.find((m) => m.type === type);
		if (!def) return type;
		return $_(`admin.ops.alertRules.metrics.${def.labelKey}`, { default: def.labelDefault });
	}

	// Self-contained datetime formatter (no cross-feature coupling).
	function formatDateTime(value?: string | null): string {
		if (!value) return '—';
		const date = new Date(value);
		if (Number.isNaN(date.getTime())) return String(value);
		return date.toLocaleString();
	}

	function severityVariant(sev: OpsSeverity): 'destructive' | 'default' | 'secondary' {
		if (sev === 'P0' || sev === 'P1') return 'destructive';
		if (sev === 'P2') return 'default';
		return 'secondary';
	}

	// ── list state ───────────────────────────────────────────────────────
	let loadState = $state<LoadState>('idle');
	let rules = $state<AlertRule[]>([]);
	let loadError = $state('');

	const sortedRules = $derived([...rules].sort((a, b) => (b.id ?? 0) - (a.id ?? 0)));

	async function load() {
		loadState = 'loading';
		loadError = '';
		try {
			rules = await listOpsAlertRules();
			loadState = 'ready';
		} catch (err) {
			rules = [];
			loadState = 'error';
			loadError =
				(err as { message?: string })?.message ??
				$_('admin.ops.alertRules.loadFailed', { default: 'Failed to load alert rules' });
		}
	}

	onMount(load);

	// ── inline enable/disable toggle ────────────────────────────────────
	let togglingIds = $state(new Set<number>());

	async function toggleEnabled(rule: AlertRule) {
		const id = rule.id;
		if (id == null) return;
		togglingIds.add(id);
		togglingIds = new Set(togglingIds);
		const nextEnabled = !rule.enabled;
		try {
			await updateOpsAlertRule(id, { enabled: nextEnabled });
			// Optimistic update in-place.
			rule.enabled = nextEnabled;
			rules = [...rules];
			showSuccess(
				nextEnabled
					? $_('admin.ops.alertRules.enabled', { default: 'Alert rule enabled.' })
					: $_('admin.ops.alertRules.disabled', { default: 'Alert rule disabled.' })
			);
		} catch (err) {
			showError(
				(err as { message?: string })?.message ??
					$_('admin.ops.alertRules.toggleFailed', { default: 'Failed to toggle alert rule.' })
			);
		} finally {
			togglingIds.delete(id);
			togglingIds = new Set(togglingIds);
		}
	}

	// ── editor (delegated to shared OpsAlertRuleEditDialog) ──────────────
	let editorOpen = $state(false);
	let editingRule = $state<AlertRule | null>(null);

	function openCreate() {
		editingRule = null;
		editorOpen = true;
	}

	function openEdit(rule: AlertRule) {
		// Pass a detached copy so the dialog can't mutate the table row in place.
		editingRule = structuredClone($state.snapshot(rule)) as AlertRule;
		editorOpen = true;
	}

	function onEditorClose() {
		editorOpen = false;
		editingRule = null;
	}

	async function onEditorSaved() {
		editorOpen = false;
		editingRule = null;
		await load();
	}

	// ── delete-confirm state ─────────────────────────────────────────────
	let deleteOpen = $state(false);
	let deleting = $state(false);
	let deleteError = $state('');
	let pendingDelete = $state<AlertRule | null>(null);

	function requestDelete(rule: AlertRule) {
		pendingDelete = rule;
		deleteError = '';
		deleteOpen = true;
	}

	async function confirmDelete() {
		const id = pendingDelete?.id;
		if (id == null) return;
		deleting = true;
		deleteError = '';
		try {
			await deleteOpsAlertRule(id);
			deleteOpen = false;
			pendingDelete = null;
			await load();
		} catch (err) {
			deleteError =
				(err as { message?: string })?.message ??
				$_('admin.ops.alertRules.deleteFailed', { default: 'Failed to delete alert rule' });
		} finally {
			deleting = false;
		}
	}
</script>

<Card class="flex flex-col gap-3.5">
	<div class="flex items-start justify-between gap-3">
		<div>
			<h3 class="text-sm font-semibold text-foreground">
				{$_('admin.ops.alertRules.title', { default: 'Alert rules' })}
			</h3>
			<p class="mt-0.5 text-xs text-muted-foreground">
				{$_('admin.ops.alertRules.description', {
					default: 'Define metric thresholds that trigger ops alerts.'
				})}
			</p>
		</div>
		<div class="flex items-center gap-1.5">
			<Button
				variant="outline"
				size="sm"
				disabled={loadState === 'loading'}
				onclick={openCreate}
				data-testid="ops-alert-rule-create"
			>
				<Plus class="h-3.5 w-3.5" />
				{$_('admin.ops.alertRules.create', { default: 'New rule' })}
			</Button>
			<Button
				variant="outline"
				size="icon"
				disabled={loadState === 'loading'}
				onclick={load}
				aria-label={$_('common.refresh', { default: 'Refresh' })}
				data-testid="ops-alert-rule-refresh"
			>
				<RefreshCw class={'h-3.5 w-3.5' + (loadState === 'loading' ? ' animate-spin' : '')} />
			</Button>
		</div>
	</div>

	{#if loadState === 'error'}
		<Alert variant="destructive" data-testid="ops-alert-rule-error">{loadError}</Alert>
	{/if}

	{#if loadState === 'loading' || loadState === 'idle'}
		<div class="py-7 text-center text-sm text-muted-foreground">
			{$_('admin.ops.alertRules.loading', { default: 'Loading…' })}
		</div>
	{:else if sortedRules.length === 0}
		<div
			class="rounded-lg border border-dashed border-border px-7 py-7 text-center text-sm text-muted-foreground"
			data-testid="ops-alert-rule-empty"
		>
			{$_('admin.ops.alertRules.empty', { default: 'No alert rules yet.' })}
		</div>
	{:else}
		<div class="overflow-auto rounded-lg border border-border" style="max-height:520px;">
			<table class="w-full border-collapse text-sm" data-testid="ops-alert-rule-table">
				<thead class="sticky top-0 z-10 bg-muted">
					<tr class="text-left text-[10px] font-bold uppercase tracking-[.06em] text-muted-foreground">
						<th class="px-3.5 py-2.5">{$_('admin.ops.alertRules.table.name', { default: 'Name' })}</th>
						<th class="px-3.5 py-2.5">{$_('admin.ops.alertRules.table.metric', { default: 'Metric' })}</th>
						<th class="px-3.5 py-2.5">{$_('admin.ops.alertRules.table.condition', { default: 'Condition' })}</th>
						<th class="px-3.5 py-2.5">{$_('admin.ops.alertRules.table.window', { default: 'Window / Sustained' })}</th>
						<th class="px-3.5 py-2.5">{$_('admin.ops.alertRules.table.severity', { default: 'Severity' })}</th>
						<th class="px-3.5 py-2.5">{$_('admin.ops.alertRules.table.enabled', { default: 'Enabled' })}</th>
						<th class="px-3.5 py-2.5">{$_('admin.ops.alertRules.table.lastTriggered', { default: 'Last triggered' })}</th>
						<th class="px-3.5 py-2.5 text-right">{$_('admin.ops.alertRules.table.actions', { default: 'Actions' })}</th>
					</tr>
				</thead>
				<tbody>
					{#each sortedRules as row (row.id)}
						<tr class="border-t border-border align-top">
							<td class="px-3.5 py-2.5">
								<div class="font-semibold text-foreground">{row.name}</div>
								{#if row.description}
									<div class="mt-0.5 line-clamp-2 text-[11px] text-muted-foreground">{row.description}</div>
								{/if}
							</td>
							<td class="px-3.5 py-2.5 text-muted-foreground">
								<span class="font-mono tabular-nums text-xs">{metricLabel(row.metric_type)}</span>
							</td>
							<td class="whitespace-nowrap px-3.5 py-2.5 text-muted-foreground">
								<span class="text-muted-foreground/70">{row.operator}</span>
								<span class="ml-1 font-mono tabular-nums text-foreground">{row.threshold}</span>
							</td>
							<td class="whitespace-nowrap px-3.5 py-2.5 text-xs text-muted-foreground tabular-nums">
								{row.window_minutes}m / {row.sustained_minutes}m
							</td>
							<td class="whitespace-nowrap px-3.5 py-2.5">
								<Badge variant={severityVariant(row.severity)}>{row.severity}</Badge>
							</td>
							<td class="whitespace-nowrap px-3.5 py-2.5">
								<Checkbox
									checked={row.enabled}
									disabled={togglingIds.has(row.id ?? -1)}
									aria-label={$_('admin.ops.alertRules.table.enabled', { default: 'Enabled' })}
									data-testid="ops-alert-rule-toggle"
									onchange={() => toggleEnabled(row)}
								/>
							</td>
							<td class="whitespace-nowrap px-3.5 py-2.5 text-xs text-muted-foreground tabular-nums">
								{formatDateTime(row.last_triggered_at)}
							</td>
							<td class="whitespace-nowrap px-3.5 py-2.5 text-right">
								<Button
									variant="outline"
									size="icon"
									class="h-7 w-7"
									onclick={() => openEdit(row)}
									aria-label={$_('common.edit', { default: 'Edit' })}
									data-testid="ops-alert-rule-edit"
								>
									<Pencil class="h-3.5 w-3.5" />
								</Button>
								<Button
									variant="outline"
									size="icon"
									class="ml-1.5 h-7 w-7 text-destructive hover:border-destructive/40 hover:text-destructive"
									onclick={() => requestDelete(row)}
									aria-label={$_('common.delete', { default: 'Delete' })}
									data-testid="ops-alert-rule-delete"
								>
									<Trash2 class="h-3.5 w-3.5" />
								</Button>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</Card>

<!-- Create / edit flow delegated to the shared editor dialog. -->
<OpsAlertRuleEditDialog
	bind:open={editorOpen}
	rule={editingRule}
	onClose={onEditorClose}
	onSaved={onEditorSaved}
/>

<!-- Delete confirmation dialog. -->
<StandardDialog
	bind:open={deleteOpen}
	width="sm"
	title={$_('admin.ops.alertRules.deleteConfirmTitle', { default: 'Delete alert rule' })}
	data-testid="ops-alert-rule-delete-confirm"
>
	<div class="mt-3 flex flex-col gap-3.5">
		<p class="text-sm text-muted-foreground">
			{$_('admin.ops.alertRules.deleteConfirmMessage', {
				default: 'This alert rule will be permanently removed. This action cannot be undone.'
			})}
		</p>
		{#if pendingDelete}
			<div class="rounded-md border border-border bg-muted/40 px-3 py-2 text-sm font-medium text-foreground">
				{pendingDelete.name}
			</div>
		{/if}
		{#if deleteError}
			<Alert variant="destructive" class="text-xs">{deleteError}</Alert>
		{/if}
		<div class="flex items-center justify-end gap-2">
			<Button variant="outline" disabled={deleting} onclick={() => (deleteOpen = false)}>
				{$_('common.cancel', { default: 'Cancel' })}
			</Button>
			<Button
				variant="destructive"
				disabled={deleting}
				onclick={confirmDelete}
				data-testid="ops-alert-rule-delete-confirm-btn"
			>
				{deleting
					? $_('common.deleting', { default: 'Deleting…' })
					: $_('common.delete', { default: 'Delete' })}
			</Button>
		</div>
	</div>
</StandardDialog>
