// frontend/src/views/admin/ops/components/OpsLatencyChart.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { Chart as ChartJS, BarElement, CategoryScale, Legend, LinearScale, Tooltip } from 'chart.js'
import { Bar } from 'vue-chartjs'
import type { OpsLatencyHistogramResponse } from '@/api/admin/ops'
import type { ChartState } from '../types'
import HelpTooltip from '@/components/common/HelpTooltip.vue'
import EmptyState from '@/components/common/EmptyState.vue'

ChartJS.register(BarElement, CategoryScale, LinearScale, Tooltip, Legend)

interface Props {
  latencyData: OpsLatencyHistogramResponse | null
  loading: boolean
}

const props = defineProps<Props>()
const { t } = useI18n()

const colors = computed(() => ({
  blue: '#5CA8FF',   /* od-azure */
  grid: '#20242C',   /* line-0 */
  text: '#5C6470'    /* ink-2 */
}))

const hasData = computed(() => (props.latencyData?.total_requests ?? 0) > 0)

const state = computed<ChartState>(() => {
  if (hasData.value) return 'ready'
  if (props.loading) return 'loading'
  return 'empty'
})

const chartData = computed(() => {
  if (!props.latencyData || !hasData.value) return null
  const c = colors.value
  return {
    labels: props.latencyData.buckets.map((b) => b.range),
    datasets: [
      {
        label: t('admin.ops.requests'),
        data: props.latencyData.buckets.map((b) => b.count),
        backgroundColor: c.blue,
        borderRadius: 4,
        barPercentage: 0.6
      }
    ]
  }
})

const options = computed(() => {
  const c = colors.value
  return {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false }
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: { color: c.text, font: { size: 10 } }
      },
      y: {
        beginAtZero: true,
        grid: { color: c.grid, borderDash: [4, 4] },
        ticks: { color: c.text, font: { size: 10 } }
      }
    }
  }
})
</script>

<template>
  <div class="flex h-full flex-col rounded-xl border border-border bg-card p-5">
    <div class="mb-3.5 flex flex-shrink-0 items-center justify-between">
      <h3 class="flex items-center gap-2 text-sm font-bold text-foreground">
        <svg class="flex-shrink-0 text-primary" width="14" height="14" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        {{ t('admin.ops.latencyHistogram') }}
        <HelpTooltip :content="t('admin.ops.tooltips.latencyHistogram')" />
      </h3>
    </div>

    <div class="min-h-0 flex-1">
      <Bar v-if="state === 'ready' && chartData" :data="chartData" :options="options" />
      <div v-else class="flex h-full items-center justify-center">
        <div v-if="state === 'loading'" class="animate-pulse text-sm text-muted-foreground">{{ t('common.loading') }}</div>
        <EmptyState v-else :title="t('common.noData')" :description="t('admin.ops.charts.emptyRequest')" />
      </div>
    </div>
  </div>
</template>

// frontend-svelte/src/lib/features/admin-ops/OpsLatencyChart.svelte
<script lang="ts">
	/**
	 * OpsLatencyChart · admin Ops 页 lazy bar chart island（延迟直方图）
	 *
	 * Vue 原型：frontend/src/views/admin/ops/components/OpsLatencyChart.vue
	 *   - x 轴：buckets[].range（latency bucket 区间标签）
	 *   - y 轴：buckets[].count（落在该区间的请求数）
	 *   - caption：total_requests（总请求数）
	 *
	 * Lazy island 红线（memory: vendor-chunk-tdz-trap）：
	 *   - chart.js + svelte-chartjs 仅在 onMount 内 `await import()` —— 顶层绝不
	 *     import，否则 rollup 顺着 eager 入口图把它们吸进 vendor，触 check-chunks
	 *     红线 + TDZ 白屏回归。
	 *   - manualChunks 已把 chart.js / svelte-chartjs / @kurkle/color 路由到
	 *     'vendor-chart' lazy chunk；此处 dynamic import 是双保险。
	 *   - SSR 兜底：typeof window 拦截，预渲染期不触发加载。
	 *
	 * 配色红线（Zinc-only，禁 raw hex）：
	 *   - 柱体 / 网格 / 刻度颜色全部从 app.css 的 CSS 变量（HSL 三元组）运行时解析，
	 *     拼成 `hsl(var(...))`；不在组件里写死任何 #hex。
	 */
	import { onMount } from 'svelte';
	import { _ } from 'svelte-i18n';
	import type { OpsLatencyHistogramResponse } from '$lib/api/admin/ops';

	let {
		latencyData,
		loading = false
	}: { latencyData: OpsLatencyHistogramResponse | null; loading?: boolean } = $props();

	let BarCmp: unknown = $state(null);
	let chartReady = $state(false);
	let chartError = $state<string | null>(null);

	// Zinc 调色：运行时从 app.css 的 HSL 三元组变量解析，避免硬编码 hex。
	let palette = $state<{ bar: string; grid: string; text: string }>({
		bar: 'hsl(240 5.9% 10%)',
		grid: 'hsl(240 5.9% 90%)',
		text: 'hsl(240 3.8% 46.1%)'
	});

	function resolvePalette(): void {
		if (typeof window === 'undefined' || typeof document === 'undefined') return;
		const root = document.documentElement;
		const cs = getComputedStyle(root);
		const v = (name: string, fallback: string): string => {
			const raw = cs.getPropertyValue(name).trim();
			return raw ? `hsl(${raw})` : fallback;
		};
		palette = {
			bar: v('--primary', palette.bar),
			grid: v('--border', palette.grid),
			text: v('--muted-foreground', palette.text)
		};
	}

	const buckets = $derived(latencyData?.buckets ?? []);
	const totalRequests = $derived(latencyData?.total_requests ?? 0);

	const chartData = $derived.by(() => ({
		labels: buckets.map((b) => b.range),
		datasets: [
			{
				label: $_('admin.ops.latencyChart.legend', { default: 'Requests' }),
				data: buckets.map((b) => b.count),
				backgroundColor: palette.bar,
				borderRadius: 4,
				barPercentage: 0.6,
				categoryPercentage: 0.7
			}
		]
	}));

	const chartOptions = $derived({
		responsive: true,
		maintainAspectRatio: false,
		plugins: {
			legend: { display: false as const },
			tooltip: { mode: 'index' as const, intersect: false }
		},
		scales: {
			x: {
				grid: { display: false },
				ticks: { color: palette.text, font: { size: 10 } }
			},
			y: {
				beginAtZero: true,
				grid: { color: palette.grid },
				ticks: { color: palette.text, font: { size: 10 }, precision: 0 }
			}
		}
	});

	onMount(() => {
		let cancelled = false;
		if (typeof window === 'undefined') return;

		resolvePalette();

		(async () => {
			try {
				// 两个 await import 都走 dynamic，rollup 切独立 lazy chunk。
				const cjs = await import('chart.js/auto');
				const scjs = await import('svelte-chartjs');
				if (cancelled) return;
				void cjs;
				BarCmp = scjs.Bar;
				chartReady = true;
			} catch (err) {
				if (cancelled) return;
				chartError = (err as Error)?.message ?? 'chart load failed';
			}
		})();

		return () => {
			cancelled = true;
		};
	});
</script>

<div
	class="opslatency-chart flex h-72 w-full flex-col rounded-xl border border-border bg-card p-3"
	data-testid="ops-latency-chart"
>
	<div class="relative min-h-0 flex-1">
		{#if loading}
			<div
				class="absolute inset-0 flex items-center justify-center text-sm text-muted-foreground"
				data-testid="ops-latency-chart-loading"
			>
				{$_('admin.ops.latencyChart.loading', { default: 'Loading chart…' })}
			</div>
		{:else if chartError}
			<div
				class="absolute inset-0 flex items-center justify-center text-sm text-destructive"
				data-testid="ops-latency-chart-error"
			>
				{$_('admin.ops.latencyChart.failed', { default: 'Failed to load chart' })}
			</div>
		{:else if latencyData === null}
			<div
				class="absolute inset-0 flex items-center justify-center text-sm text-destructive"
				data-testid="ops-latency-chart-error"
			>
				{$_('admin.ops.latencyChart.failed', { default: 'Failed to load chart' })}
			</div>
		{:else if buckets.length === 0 || totalRequests === 0}
			<div
				class="absolute inset-0 flex items-center justify-center text-sm text-muted-foreground"
				data-testid="ops-latency-chart-empty"
			>
				{$_('admin.ops.latencyChart.empty', { default: 'No requests in this range' })}
			</div>
		{:else if !chartReady || !BarCmp}
			<div
				class="absolute inset-0 flex items-center justify-center text-sm text-muted-foreground"
				data-testid="ops-latency-chart-loading"
			>
				{$_('admin.ops.latencyChart.loading', { default: 'Loading chart…' })}
			</div>
		{:else}
			{@const BC = BarCmp as unknown as import('svelte').Component<{
				data: typeof chartData;
				options: typeof chartOptions;
			}>}
			<BC data={chartData} options={chartOptions} />
		{/if}
	</div>

	{#if !loading && !chartError && latencyData !== null && buckets.length > 0 && totalRequests > 0}
		<div
			class="mt-2 flex-shrink-0 text-center text-xs text-muted-foreground"
			data-testid="ops-latency-chart-total"
		>
			{$_('admin.ops.latencyChart.totalRequests', {
				default: 'Total requests: {count}',
				values: { count: totalRequests.toLocaleString() }
			})}
		</div>
	{/if}
</div>

<style>
	.opslatency-chart :global(canvas) {
		max-height: 100% !important;
	}
</style>
