// frontend/src/components/auth/EmailOAuthButtons.vue
<template>
  <div v-if="hasProviders" class="space-y-4">
    <div v-if="showDivider" class="flex items-center gap-3">
      <div class="h-px flex-1 bg-border"></div>
      <span class="text-xs text-muted-foreground">
        {{ t('auth.oauthOrContinue') }}
      </span>
      <div class="h-px flex-1 bg-border"></div>
    </div>

    <div :class="providerGridClass">
      <Button
        v-for="provider in visibleProviders"
        :key="provider"
        type="button"
        variant="outline"
        :disabled="disabled"
        class="h-12 w-full justify-center gap-2"
        @click="startLogin(provider)"
      >
        <GitHubMark v-if="provider === 'github'" class="h-5 w-5 text-foreground" />
        <GoogleMark v-else class="h-5 w-5" />
        <span class="font-medium">{{ providerLabel(provider) }}</span>
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Button } from '@/components/ui/button'
import GitHubMark from './GitHubMark.vue'
import GoogleMark from './GoogleMark.vue'
import { resolveAffiliateReferralCode, storeOAuthAffiliateCode } from '@/utils/oauthAffiliate'

type EmailOAuthProvider = 'github' | 'google'
const EMAIL_OAUTH_PENDING_PROVIDER_KEY = 'email_oauth_pending_provider'

const props = withDefaults(defineProps<{
  disabled?: boolean
  affCode?: string
  githubEnabled?: boolean
  googleEnabled?: boolean
  showDivider?: boolean
}>(), {
  showDivider: true
})

const route = useRoute()
const { t } = useI18n()

const visibleProviders = computed<EmailOAuthProvider[]>(() => {
  const providers: EmailOAuthProvider[] = []
  if (props.githubEnabled) providers.push('github')
  if (props.googleEnabled) providers.push('google')
  return providers
})

const hasProviders = computed(() => visibleProviders.value.length > 0)
const hasMultipleProviders = computed(() => visibleProviders.value.length > 1)
const providerGridClass = computed(() => [
  'grid',
  'grid-cols-1',
  'gap-3',
  hasMultipleProviders.value ? 'sm:grid-cols-2' : ''
])

function providerLabel(provider: EmailOAuthProvider): string {
  const name = provider === 'github' ? 'GitHub' : 'Google'
  return hasMultipleProviders.value ? name : t('auth.emailOAuth.signIn', { providerName: name })
}

function startLogin(provider: EmailOAuthProvider): void {
  const redirectTo = (route.query.redirect as string) || '/dashboard'
  const affiliateCode = resolveAffiliateReferralCode(props.affCode, route.query.aff, route.query.aff_code)
  storeOAuthAffiliateCode(affiliateCode)
  window.sessionStorage.setItem(EMAIL_OAUTH_PENDING_PROVIDER_KEY, provider)
  const apiBase = (import.meta.env.VITE_API_BASE_URL as string | undefined) || '/api/v1'
  const normalized = apiBase.replace(/\/$/, '')
  const params = new URLSearchParams({ redirect: redirectTo })
  if (affiliateCode) {
    params.set('aff_code', affiliateCode)
  }
  const startURL = `${normalized}/auth/oauth/${provider}/start?${params.toString()}`
  window.location.href = startURL
}
</script>

// frontend-svelte/src/lib/features/auth/EmailOAuthButtons.svelte
<script lang="ts">
	/**
	 * EmailOAuthButtons · GitHub / Google email OAuth entry row.
	 *
	 * 与 Vue EmailOAuthButtons.vue 同契约：provider 开关来自 public settings，
	 * 点击后写 pending provider + affiliate code，再跳后端 start endpoint。
	 */
	import { onMount } from 'svelte';
	import { _ } from 'svelte-i18n';
	import { GitBranch } from '@lucide/svelte';
	import { authApi, type EmailOAuthProvider, type PublicSettings } from '$lib/api/auth';
	import {
		buildEmailOAuthStartUrl,
		storeOAuthAffiliateCode,
		storePendingEmailOAuthProvider
	} from './email-oauth';
	import Button from '$lib/ui/Button.svelte';

	type Props = {
		affCode?: string;
		disabled?: boolean;
		showDivider?: boolean;
		redirect?: string;
	};

	let {
		affCode = '',
		disabled = false,
		showDivider = true,
		redirect = '/dashboard'
	}: Props = $props();

	let loading = $state(true);
	let providers = $state<EmailOAuthProvider[]>([]);

	const hasProviders = $derived(providers.length > 0);
	const hasMultipleProviders = $derived(providers.length > 1);

	onMount(() => {
		void loadSettings();
	});

	async function loadSettings() {
		loading = true;
		try {
			const settings = await authApi.getPublicSettings();
			providers = visibleProviders(settings);
		} catch {
			providers = [];
		} finally {
			loading = false;
		}
	}

	function visibleProviders(settings: PublicSettings): EmailOAuthProvider[] {
		const result: EmailOAuthProvider[] = [];
		if (settings.github_oauth_enabled) result.push('github');
		if (settings.google_oauth_enabled) result.push('google');
		return result;
	}

	function providerLabel(provider: EmailOAuthProvider): string {
		const name = provider === 'github' ? 'GitHub' : 'Google';
		return hasMultipleProviders
			? name
			: $_('auth.emailOAuth.signIn', {
					default: 'Continue with {providerName}',
					values: { providerName: name }
				});
	}

	function startLogin(provider: EmailOAuthProvider) {
		storePendingEmailOAuthProvider(provider);
		storeOAuthAffiliateCode(affCode);
		const target = buildEmailOAuthStartUrl(provider, { redirect, affCode });
		window.location.href = target;
	}
</script>

{#if !loading && hasProviders}
	<div class="space-y-3" data-testid="email-oauth-buttons">
		{#if showDivider}
			<div class="flex items-center gap-3 text-[11px] uppercase tracking-wide text-muted-foreground">
				<div class="h-px flex-1 bg-border"></div>
				<span>{$_('auth.oauthOrContinue', { default: 'or continue with others' })}</span>
				<div class="h-px flex-1 bg-border"></div>
			</div>
		{/if}

		<div class="grid grid-cols-1 gap-2 {hasMultipleProviders ? 'sm:grid-cols-2' : ''}">
			{#each providers as provider (provider)}
				<Button
					type="button"
					variant="outline"
					class="h-11 w-full justify-center gap-2"
					disabled={disabled}
					onclick={() => startLogin(provider)}
					data-testid={`email-oauth-${provider}`}
				>
					{#if provider === 'github'}
						<GitBranch class="h-4 w-4" />
					{:else}
						<span class="flex h-4 w-4 items-center justify-center rounded-full border border-border text-[10px] font-semibold text-foreground">G</span>
					{/if}
					<span>{providerLabel(provider)}</span>
				</Button>
			{/each}
		</div>
	</div>
{/if}
