// frontend/src/views/admin/settings-registry/special/CustomMenuSection.vue
<template>
  <div class="flex flex-col gap-6 px-5 py-4">
    <!-- ── Custom Endpoints ─────────────────────────────────────────── -->
    <div class="flex flex-col gap-3">
      <p class="m-0 text-[11.5px] leading-[1.55] text-muted-foreground">{{ t('admin.settings.site.customEndpoints.description') }}</p>

      <div v-if="localEndpoints.length > 0" class="flex flex-col gap-2.5">
        <div
          v-for="(ep, index) in localEndpoints"
          :key="index"
          class="overflow-hidden rounded-[10px] border border-border bg-card"
        >
          <div class="flex items-center justify-between gap-2.5 border-b border-border px-3.5 py-2.5">
            <span class="text-[12.5px] font-semibold text-foreground">
              {{ t('admin.settings.site.customEndpoints.itemLabel', { n: index + 1 }) }}
            </span>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              class="h-7 w-7 text-destructive hover:bg-destructive/10 hover:text-destructive"
              @click="removeEndpoint(index)"
            >
              <svg class="h-3.5 w-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            </Button>
          </div>
          <div class="grid grid-cols-2 gap-3 p-3.5 max-[600px]:grid-cols-1">
            <div>
              <Label class="mb-1 block text-[11.5px] font-medium text-muted-foreground">{{ t('admin.settings.site.customEndpoints.name') }}</Label>
              <Input
                v-model="ep.name"
                type="text"
                :placeholder="t('admin.settings.site.customEndpoints.namePlaceholder')"
                @input="emitEndpoints"
              />
            </div>
            <div>
              <Label class="mb-1 block text-[11.5px] font-medium text-muted-foreground">{{ t('admin.settings.site.customEndpoints.endpointUrl') }}</Label>
              <Input
                v-model="ep.endpoint"
                type="url"
                class="font-mono text-xs"
                :placeholder="t('admin.settings.site.customEndpoints.endpointUrlPlaceholder')"
                @input="emitEndpoints"
              />
            </div>
            <div class="col-span-full max-[600px]:col-span-1">
              <Label class="mb-1 block text-[11.5px] font-medium text-muted-foreground">{{ t('admin.settings.site.customEndpoints.descriptionLabel') }}</Label>
              <Input
                v-model="ep.description"
                type="text"
                :placeholder="t('admin.settings.site.customEndpoints.descriptionPlaceholder')"
                @input="emitEndpoints"
              />
            </div>
          </div>
        </div>
      </div>

      <Button
        type="button"
        variant="outline"
        class="w-full border-dashed text-[12.5px] text-muted-foreground hover:border-ring hover:text-foreground"
        @click="addEndpoint"
      >
        <svg class="h-3.5 w-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
        </svg>
        {{ t('admin.settings.site.customEndpoints.add') }}
      </Button>
    </div>

    <!-- ── Custom Menu Items ────────────────────────────────────────── -->
    <div class="flex flex-col gap-3 border-t border-border pt-5">
      <p class="m-0 text-[11.5px] leading-[1.55] text-muted-foreground">{{ t('admin.settings.customMenu.description') }}</p>

      <div v-if="localMenuItems.length > 0" class="flex flex-col gap-2.5">
        <div
          v-for="(item, index) in localMenuItems"
          :key="item.id || index"
          class="overflow-hidden rounded-[10px] border border-border bg-card"
        >
          <div class="flex items-center justify-between gap-2.5 border-b border-border px-3.5 py-2.5">
            <span class="text-[12.5px] font-semibold text-foreground">
              {{ t('admin.settings.customMenu.itemLabel', { n: index + 1 }) }}
            </span>
            <div class="flex items-center gap-1">
              <!-- Move up -->
              <Button
                v-if="index > 0"
                type="button"
                variant="ghost"
                size="icon"
                class="h-7 w-7 text-muted-foreground hover:text-foreground"
                :title="t('admin.settings.customMenu.moveUp')"
                @click="moveMenuItem(index, -1)"
              >
                <svg class="h-3.5 w-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M5 15l7-7 7 7" />
                </svg>
              </Button>
              <!-- Move down -->
              <Button
                v-if="index < localMenuItems.length - 1"
                type="button"
                variant="ghost"
                size="icon"
                class="h-7 w-7 text-muted-foreground hover:text-foreground"
                :title="t('admin.settings.customMenu.moveDown')"
                @click="moveMenuItem(index, 1)"
              >
                <svg class="h-3.5 w-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
                </svg>
              </Button>
              <!-- Delete -->
              <Button
                type="button"
                variant="ghost"
                size="icon"
                class="h-7 w-7 text-destructive hover:bg-destructive/10 hover:text-destructive"
                :title="t('admin.settings.customMenu.remove')"
                @click="removeMenuItem(index)"
              >
                <svg class="h-3.5 w-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
              </Button>
            </div>
          </div>

          <div class="grid grid-cols-2 gap-3 p-3.5 max-[600px]:grid-cols-1">
            <!-- Label -->
            <div>
              <Label class="mb-1 block text-[11.5px] font-medium text-muted-foreground">{{ t('admin.settings.customMenu.name') }}</Label>
              <Input
                v-model="item.label"
                type="text"
                :placeholder="t('admin.settings.customMenu.namePlaceholder')"
                @input="emitMenuItems"
              />
            </div>

            <!-- Visibility -->
            <div>
              <Label class="mb-1 block text-[11.5px] font-medium text-muted-foreground">{{ t('admin.settings.customMenu.visibility') }}</Label>
              <Select :model-value="item.visibility" @update:model-value="(v) => { item.visibility = v as 'user' | 'admin'; emitMenuItems() }">
                <SelectTrigger class="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="user">{{ t('admin.settings.customMenu.visibilityUser') }}</SelectItem>
                  <SelectItem value="admin">{{ t('admin.settings.customMenu.visibilityAdmin') }}</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <!-- URL (full width) -->
            <div class="col-span-full max-[600px]:col-span-1">
              <Label class="mb-1 block text-[11.5px] font-medium text-muted-foreground">{{ t('admin.settings.customMenu.url') }}</Label>
              <Input
                v-model="item.url"
                type="url"
                class="font-mono text-xs"
                :placeholder="t('admin.settings.customMenu.urlPlaceholder')"
                @input="emitMenuItems"
              />
            </div>

            <!-- SVG Icon (full width) -->
            <div class="col-span-full max-[600px]:col-span-1">
              <Label class="mb-1 block text-[11.5px] font-medium text-muted-foreground">{{ t('admin.settings.customMenu.iconSvg') }}</Label>
              <ImageUpload
                :model-value="item.icon_svg"
                mode="svg"
                size="sm"
                :upload-label="t('admin.settings.customMenu.uploadSvg')"
                :remove-label="t('admin.settings.customMenu.removeSvg')"
                @update:model-value="(v: string) => { item.icon_svg = v; emitMenuItems() }"
              />
            </div>
          </div>
        </div>
      </div>

      <Button
        type="button"
        variant="outline"
        class="w-full border-dashed text-[12.5px] text-muted-foreground hover:border-ring hover:text-foreground"
        @click="addMenuItem"
      >
        <svg class="h-3.5 w-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
        </svg>
        {{ t('admin.settings.customMenu.add') }}
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, defineAsyncComponent } from 'vue'
import { useI18n } from 'vue-i18n'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectTrigger, SelectContent, SelectItem, SelectValue } from '@/components/ui/select'

const ImageUpload = defineAsyncComponent(() => import('@/components/common/ImageUpload.vue'))

const { t } = useI18n()

interface MenuItem {
  id: string
  label: string
  icon_svg: string
  url: string
  visibility: 'user' | 'admin'
  sort_order: number
}

interface CustomEndpoint {
  name: string
  endpoint: string
  description: string
}

const props = defineProps<{
  settings: Record<string, unknown>
  formValues?: Record<string, unknown>
}>()

const emit = defineEmits<{
  'update:field': [key: string, value: unknown]
}>()

// Prefer dirty form state over saved settings
const activeSource = computed(() => props.formValues ?? props.settings)

// ── Helpers ────────────────────────────────────────────────────────────────────

function cloneMenuItems(src: Record<string, unknown>): MenuItem[] {
  const raw = src['custom_menu_items']
  if (!Array.isArray(raw)) return []
  return raw.map((item) => ({ ...(item as MenuItem) }))
}

function cloneEndpoints(src: Record<string, unknown>): CustomEndpoint[] {
  const raw = src['custom_endpoints']
  if (!Array.isArray(raw)) return []
  return raw.map((ep) => ({ ...(ep as CustomEndpoint) }))
}

// ── Local state ────────────────────────────────────────────────────────────────

const localMenuItems = ref<MenuItem[]>(cloneMenuItems(activeSource.value))
const localEndpoints = ref<CustomEndpoint[]>(cloneEndpoints(activeSource.value))

// Re-sync when parent resets (discard) or initial load completes
watch(
  () => activeSource.value['custom_menu_items'],
  (incoming) => {
    if (JSON.stringify(incoming) !== JSON.stringify(localMenuItems.value)) {
      localMenuItems.value = cloneMenuItems(activeSource.value)
    }
  },
  { deep: true },
)

watch(
  () => activeSource.value['custom_endpoints'],
  (incoming) => {
    if (JSON.stringify(incoming) !== JSON.stringify(localEndpoints.value)) {
      localEndpoints.value = cloneEndpoints(activeSource.value)
    }
  },
  { deep: true },
)

// ── Emit helpers ───────────────────────────────────────────────────────────────

function emitMenuItems() {
  emit('update:field', 'custom_menu_items', localMenuItems.value.map((item) => ({ ...item })))
}

function emitEndpoints() {
  emit('update:field', 'custom_endpoints', localEndpoints.value.map((ep) => ({ ...ep })))
}

// ── Menu item CRUD + reorder ───────────────────────────────────────────────────

function addMenuItem() {
  localMenuItems.value = [
    ...localMenuItems.value,
    {
      id: '',
      label: '',
      icon_svg: '',
      url: '',
      visibility: 'user',
      sort_order: localMenuItems.value.length,
    },
  ]
  emitMenuItems()
}

function removeMenuItem(index: number) {
  localMenuItems.value = localMenuItems.value
    .filter((_, i) => i !== index)
    .map((item, i) => ({ ...item, sort_order: i }))
  emitMenuItems()
}

function moveMenuItem(index: number, direction: -1 | 1) {
  const targetIndex = index + direction
  if (targetIndex < 0 || targetIndex >= localMenuItems.value.length) return
  const items = localMenuItems.value.map((item) => ({ ...item }))
  const temp = items[index]
  items[index] = items[targetIndex]
  items[targetIndex] = temp
  items.forEach((item, i) => { item.sort_order = i })
  localMenuItems.value = items
  emitMenuItems()
}

// ── Endpoint CRUD ──────────────────────────────────────────────────────────────

function addEndpoint() {
  localEndpoints.value = [...localEndpoints.value, { name: '', endpoint: '', description: '' }]
  emitEndpoints()
}

function removeEndpoint(index: number) {
  localEndpoints.value = localEndpoints.value.filter((_, i) => i !== index)
  emitEndpoints()
}
</script>

// frontend-svelte/src/lib/registry/special/CustomMenuSection.svelte
<script lang="ts">
	/**
	 * CustomMenuSection · 自定义菜单 + custom endpoints 复合 special section（M10）
	 *
	 * 端口自 frontend/src/views/admin/settings-registry/special/CustomMenuSection.vue。
	 *
	 * 两块独立 list（顺次 emit 'custom_endpoints' 与 'custom_menu_items'）：
	 *   - Custom Endpoints：name / endpoint / description
	 *   - Custom Menu Items：id / label / icon_svg / url / visibility / sort_order
	 *
	 * 菜单项支持上移/下移重排，emit 时同步归一化 sort_order，保持 backend 兼容。
	 *
	 * Sentinel：visibility 走 'user' / 'admin'，绝不出 ''。
 */
	import { _ } from 'svelte-i18n';
	import { ChevronDown, ChevronUp, X } from '@lucide/svelte';
	import Button from '$lib/ui/Button.svelte';
	import Input from '$lib/ui/Input.svelte';
	import NativeSelect from '$lib/ui/NativeSelect.svelte';
	import Textarea from '$lib/ui/Textarea.svelte';

	type FieldUpdate = { key: string; value: unknown };

	type MenuItem = {
		id: string;
		label: string;
		icon_svg: string;
		url: string;
		visibility: 'user' | 'admin';
		sort_order: number;
	};

	type CustomEndpoint = {
		name: string;
		endpoint: string;
		description: string;
	};

	type Props = {
		values: Record<string, unknown>;
		dirtyKeys: Set<string>;
		onFieldUpdate?: (e: FieldUpdate) => void;
	};

	const { values, onFieldUpdate }: Props = $props();

	function cloneMenu(raw: unknown): MenuItem[] {
		if (!Array.isArray(raw)) return [];
		return raw.map((it) => ({
			id: String((it as MenuItem)?.id ?? ''),
			label: String((it as MenuItem)?.label ?? ''),
			icon_svg: String((it as MenuItem)?.icon_svg ?? ''),
			url: String((it as MenuItem)?.url ?? ''),
			visibility: ((it as MenuItem)?.visibility === 'admin' ? 'admin' : 'user') as 'user' | 'admin',
			sort_order: Number((it as MenuItem)?.sort_order ?? 0)
		}));
	}

	function cloneEp(raw: unknown): CustomEndpoint[] {
		if (!Array.isArray(raw)) return [];
		return raw.map((it) => ({
			name: String((it as CustomEndpoint)?.name ?? ''),
			endpoint: String((it as CustomEndpoint)?.endpoint ?? ''),
			description: String((it as CustomEndpoint)?.description ?? '')
		}));
	}

	let menuItems = $state<MenuItem[]>([]);
	let endpoints = $state<CustomEndpoint[]>([]);
	let _initMenu = false;
	let _initEp = false;

	$effect(() => {
		const incoming = cloneMenu(values['custom_menu_items']);
		if (!_initMenu) {
			menuItems = incoming;
			_initMenu = true;
			return;
		}
		if (JSON.stringify(incoming) !== JSON.stringify(menuItems)) menuItems = incoming;
	});
	$effect(() => {
		const incoming = cloneEp(values['custom_endpoints']);
		if (!_initEp) {
			endpoints = incoming;
			_initEp = true;
			return;
		}
		if (JSON.stringify(incoming) !== JSON.stringify(endpoints)) endpoints = incoming;
	});

	function emitMenu() {
		onFieldUpdate?.({ key: 'custom_menu_items', value: menuItems.map((m) => ({ ...m })) });
	}
	function emitEndpoints() {
		onFieldUpdate?.({ key: 'custom_endpoints', value: endpoints.map((m) => ({ ...m })) });
	}

	function addMenu() {
		menuItems = [
			...menuItems,
			{ id: '', label: '', icon_svg: '', url: '', visibility: 'user', sort_order: menuItems.length }
		];
		emitMenu();
	}
	function removeMenu(i: number) {
		menuItems = menuItems.filter((_, idx) => idx !== i).map((m, idx) => ({ ...m, sort_order: idx }));
		emitMenu();
	}
	function moveMenu(i: number, direction: -1 | 1) {
		const target = i + direction;
		if (target < 0 || target >= menuItems.length) return;
		const next = [...menuItems];
		[next[i], next[target]] = [next[target], next[i]];
		menuItems = next.map((m, idx) => ({ ...m, sort_order: idx }));
		emitMenu();
	}
	function patchMenu(i: number, key: keyof MenuItem, val: string) {
		const next = menuItems.map((m, idx) => (idx === i ? { ...m, [key]: val } : m));
		menuItems = next;
		emitMenu();
	}

	function addEp() {
		endpoints = [...endpoints, { name: '', endpoint: '', description: '' }];
		emitEndpoints();
	}
	function removeEp(i: number) {
		endpoints = endpoints.filter((_, idx) => idx !== i);
		emitEndpoints();
	}
	function patchEp(i: number, key: keyof CustomEndpoint, val: string) {
		endpoints = endpoints.map((m, idx) => (idx === i ? { ...m, [key]: val } : m));
		emitEndpoints();
	}
</script>

<div class="flex flex-col gap-6" data-special="custom-menu">
	<div class="flex flex-col gap-3">
		<p class="text-[11.5px] leading-snug text-muted-foreground">
			{$_('admin.settings.site.customEndpoints.description')}
		</p>
		{#each endpoints as ep, i (i)}
			<div class="overflow-hidden rounded-md border border-border bg-card" data-testid="custom-endpoint-row">
				<div class="flex items-center justify-between gap-2.5 border-b border-border px-3 py-2">
					<span class="text-xs font-semibold text-foreground">
						{$_('admin.settings.site.customEndpoints.itemLabel', { values: { n: i + 1 } })}
					</span>
					<Button
						variant="ghost"
						size="icon"
						aria-label="remove endpoint"
						class="h-7 w-7 text-destructive hover:bg-destructive/10"
						onclick={() => removeEp(i)}
					>
						<X class="h-3 w-3" />
					</Button>
				</div>
				<div class="grid grid-cols-1 gap-3 p-3 [grid-template-columns:repeat(auto-fit,minmax(200px,1fr))]">
					<label class="block">
						<span class="mb-1 block text-[11.5px] font-medium text-muted-foreground">
							{$_('admin.settings.site.customEndpoints.name')}
						</span>
						<Input
							type="text"
							class="h-9"
							value={ep.name}
							oninput={(e) => patchEp(i, 'name', (e.target as HTMLInputElement).value)}
						/>
					</label>
					<label class="block">
						<span class="mb-1 block text-[11.5px] font-medium text-muted-foreground">
							{$_('admin.settings.site.customEndpoints.endpointUrl')}
						</span>
						<Input
							type="url"
							class="h-9 font-mono text-xs"
							value={ep.endpoint}
							oninput={(e) => patchEp(i, 'endpoint', (e.target as HTMLInputElement).value)}
						/>
					</label>
					<label class="block">
						<span class="mb-1 block text-[11.5px] font-medium text-muted-foreground">
							{$_('admin.settings.site.customEndpoints.descriptionLabel')}
						</span>
						<Input
							type="text"
							class="h-9"
							value={ep.description}
							oninput={(e) => patchEp(i, 'description', (e.target as HTMLInputElement).value)}
						/>
					</label>
				</div>
			</div>
		{/each}
		<Button
			variant="outline"
			data-testid="custom-endpoint-add"
			class="h-9 w-full border-dashed text-xs text-muted-foreground hover:border-ring hover:text-foreground"
			onclick={addEp}
		>
			+ {$_('admin.settings.site.customEndpoints.add')}
		</Button>
	</div>

	<div class="flex flex-col gap-3 border-t border-border pt-5">
		<p class="text-[11.5px] leading-snug text-muted-foreground">
			{$_('admin.settings.customMenu.description')}
		</p>
		{#each menuItems as item, i (i)}
			<div class="overflow-hidden rounded-md border border-border bg-card" data-testid="custom-menu-row">
				<div class="flex items-center justify-between gap-2.5 border-b border-border px-3 py-2">
					<span class="text-xs font-semibold text-foreground">
						{$_('admin.settings.customMenu.itemLabel', { values: { n: i + 1 } })}
					</span>
					<div class="flex items-center gap-1">
						<Button
							variant="ghost"
							size="icon"
							aria-label={$_('admin.settings.customMenu.moveUp')}
							title={$_('admin.settings.customMenu.moveUp')}
							data-testid={`custom-menu-move-up-${i}`}
							disabled={i === 0}
							class="h-7 w-7"
							onclick={() => moveMenu(i, -1)}
						>
							<ChevronUp class="h-3.5 w-3.5" />
						</Button>
						<Button
							variant="ghost"
							size="icon"
							aria-label={$_('admin.settings.customMenu.moveDown')}
							title={$_('admin.settings.customMenu.moveDown')}
							data-testid={`custom-menu-move-down-${i}`}
							disabled={i === menuItems.length - 1}
							class="h-7 w-7"
							onclick={() => moveMenu(i, 1)}
						>
							<ChevronDown class="h-3.5 w-3.5" />
						</Button>
						<Button
							variant="ghost"
							size="icon"
							aria-label={$_('admin.settings.customMenu.remove')}
							title={$_('admin.settings.customMenu.remove')}
							class="h-7 w-7 text-destructive hover:bg-destructive/10"
							onclick={() => removeMenu(i)}
						>
							<X class="h-3 w-3" />
						</Button>
					</div>
				</div>
				<div class="grid gap-3 p-3 [grid-template-columns:repeat(auto-fit,minmax(200px,1fr))]">
					<label class="block">
						<span class="mb-1 block text-[11.5px] font-medium text-muted-foreground">
							{$_('admin.settings.customMenu.name')}
						</span>
						<Input
							type="text"
							class="h-9"
							value={item.label}
							oninput={(e) => patchMenu(i, 'label', (e.target as HTMLInputElement).value)}
						/>
					</label>
					<label class="block">
						<span class="mb-1 block text-[11.5px] font-medium text-muted-foreground">
							{$_('admin.settings.customMenu.url')}
						</span>
						<Input
							type="url"
							class="h-9 font-mono text-xs"
							value={item.url}
							oninput={(e) => patchMenu(i, 'url', (e.target as HTMLInputElement).value)}
						/>
					</label>
					<label class="block">
						<span class="mb-1 block text-[11.5px] font-medium text-muted-foreground">
							{$_('admin.settings.customMenu.visibility')}
						</span>
						<NativeSelect
							class="h-9 w-full"
							value={item.visibility}
							onchange={(e) => patchMenu(i, 'visibility', (e.target as HTMLSelectElement).value)}
						>
							<option value="user">{$_('admin.settings.customMenu.visibilityUser')}</option>
							<option value="admin">{$_('admin.settings.customMenu.visibilityAdmin')}</option>
						</NativeSelect>
					</label>
					<label class="col-span-full block">
						<span class="mb-1 block text-[11.5px] font-medium text-muted-foreground">
							{$_('admin.settings.customMenu.iconSvg')}
						</span>
						<Textarea
							rows={2}
							class="font-mono text-[11px]"
							value={item.icon_svg}
							oninput={(e) => patchMenu(i, 'icon_svg', (e.target as HTMLTextAreaElement).value)}
						/>
					</label>
				</div>
			</div>
		{/each}
		<Button
			variant="outline"
			data-testid="custom-menu-add"
			class="h-9 w-full border-dashed text-xs text-muted-foreground hover:border-ring hover:text-foreground"
			onclick={addMenu}
		>
			+ {$_('admin.settings.customMenu.add')}
		</Button>
	</div>
</div>
