// frontend/src/views/admin/settings-registry/special/RateLimit429Section.vue
<template>
  <div class="flex flex-col gap-4 px-5 py-4">
    <!-- loading -->
    <div v-if="loading" class="flex items-center gap-2 text-xs text-muted-foreground">
      <svg class="h-4 w-4 animate-spin flex-shrink-0" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
      </svg>
      {{ t('common.loading') }}
    </div>

    <template v-else>
      <!-- enabled switch -->
      <div class="flex items-center justify-between gap-4">
        <div>
          <Label class="text-sm font-medium">{{ t('admin.settings.rateLimit429Cooldown.enabled') }}</Label>
          <p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">{{ t('admin.settings.rateLimit429Cooldown.enabledHint') }}</p>
        </div>
        <Toggle v-model="form.enabled" />
      </div>

      <!-- expanded fields -->
      <div v-if="form.enabled" class="flex flex-col gap-3 border-t border-border pt-4">
        <div class="flex flex-col gap-1">
          <Label class="text-xs font-medium text-muted-foreground">{{ t('admin.settings.rateLimit429Cooldown.cooldownSeconds') }}</Label>
          <Input
            v-model.number="form.cooldown_seconds"
            type="number"
            min="1"
            max="7200"
            class="w-32 font-mono"
          />
          <p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">{{ t('admin.settings.rateLimit429Cooldown.cooldownSecondsHint') }}</p>
        </div>
      </div>

      <!-- save -->
      <div class="flex justify-end border-t border-border pt-4">
        <Button
          type="button"
          variant="outline"
          :disabled="saving"
          @click="save"
          class="gap-1.5"
        >
          <svg
            v-if="saving"
            class="h-3.5 w-3.5 animate-spin"
            fill="none"
            viewBox="0 0 24 24"
          >
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          {{ saving ? t('common.saving') : t('common.save') }}
        </Button>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import Toggle from '@/components/common/Toggle.vue'
import { adminAPI } from '@/api/admin'
import { useAppStore } from '@/stores'
import { extractApiErrorMessage } from '@/utils/apiError'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'

const { t } = useI18n()
const appStore = useAppStore()

const loading = ref(true)
const saving = ref(false)

const form = reactive({
  enabled: true,
  cooldown_seconds: 5,
})

onMounted(async () => {
  loading.value = true
  try {
    const settings = await adminAPI.settings.getRateLimit429CooldownSettings()
    Object.assign(form, settings)
  } catch {
    // silent — form stays at defaults
  } finally {
    loading.value = false
  }
})

async function save() {
  saving.value = true
  try {
    const updated = await adminAPI.settings.updateRateLimit429CooldownSettings({
      enabled: form.enabled,
      cooldown_seconds: form.cooldown_seconds,
    })
    Object.assign(form, updated)
    appStore.showSuccess(t('admin.settings.rateLimit429Cooldown.saved'))
  } catch (error: unknown) {
    appStore.showError(
      extractApiErrorMessage(error, t('admin.settings.rateLimit429Cooldown.saveFailed')),
    )
  } finally {
    saving.value = false
  }
}
</script>

// frontend-svelte/src/lib/registry/special/RateLimit429Section.svelte
<script lang="ts">
	/**
	 * RateLimit429Section · 429 default cooldown special section（M11 gateway）
	 *
	 * 端口自 frontend/src/views/admin/settings-registry/special/RateLimit429Section.vue。
	 *
	 * 设计：
	 *   - 与 flat-form 解耦 —— onMount GET /api/admin/settings/rate-limit-429-cooldown，
	 *     Save 触发 PUT 整体替换；不进 patchSettings 流水线。
	 *   - 单一 toggle + 数字输入（1-7200 秒），cooldown_seconds 仅在 enabled 时露面。
	 */
	import { onMount } from 'svelte';
	import { _ } from 'svelte-i18n';
	import {
		settingsApi,
		type RateLimit429CooldownSettings
	} from '$lib/api/admin/settingsRegistry';
	import { showError, showSuccess } from '$lib/stores/toast.svelte';

	type FieldUpdate = { key: string; value: unknown };

	type Props = {
		values?: Record<string, unknown>;
		dirtyKeys?: Set<string>;
		onFieldUpdate?: (e: FieldUpdate) => void;
	};

	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	const { values: _v, dirtyKeys: _d, onFieldUpdate: _f }: Props = $props();

	let loading = $state(true);
	let saving = $state(false);
	let form = $state<RateLimit429CooldownSettings>({ enabled: true, cooldown_seconds: 5 });

	onMount(async () => {
		loading = true;
		try {
			const settings = await settingsApi.getRateLimit429CooldownSettings();
			form = { ...form, ...settings };
		} catch {
			// 静默：form 留默认值。
		} finally {
			loading = false;
		}
	});

	function toggleEnabled() {
		form = { ...form, enabled: !form.enabled };
	}

	function onCooldownInput(e: Event) {
		const raw = (e.target as HTMLInputElement).value;
		form = { ...form, cooldown_seconds: raw === '' ? 0 : Number(raw) };
	}

	async function save() {
		saving = true;
		try {
			const updated = await settingsApi.updateRateLimit429CooldownSettings({
				enabled: form.enabled,
				cooldown_seconds: form.cooldown_seconds
			});
			form = { ...form, ...updated };
			showSuccess($_('admin.settings.rateLimit429Cooldown.saved'));
		} catch (err) {
			showError(
				err instanceof Error
					? err.message
					: $_('admin.settings.rateLimit429Cooldown.saveFailed')
			);
		} finally {
			saving = false;
		}
	}
</script>

<div class="flex flex-col gap-4" data-special="rate-limit-429">
	{#if loading}
		<div
			data-testid="rate-limit-429-loading"
			class="flex items-center gap-2 text-sm text-muted-foreground"
		>
			{$_('common.loading')}
		</div>
	{:else}
		<!-- enabled toggle -->
		<div class="flex items-center justify-between gap-4">
			<div class="min-w-0">
				<label
					class="block text-sm font-medium text-foreground"
					for="rate-limit-429-enabled"
				>
					{$_('admin.settings.rateLimit429Cooldown.enabled')}
				</label>
				<p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">
					{$_('admin.settings.rateLimit429Cooldown.enabledHint')}
				</p>
			</div>
			<button
				id="rate-limit-429-enabled"
				type="button"
				role="switch"
				aria-checked={form.enabled}
				aria-label={$_('admin.settings.rateLimit429Cooldown.enabled')}
				data-testid="rate-limit-429-enabled"
				data-checked={form.enabled}
				onclick={toggleEnabled}
				class="relative inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full transition-colors {form.enabled
					? 'bg-primary'
					: 'bg-muted'}"
			>
				<span
					class="inline-block h-4 w-4 transform rounded-full bg-white transition-transform {form.enabled
						? 'translate-x-4'
						: 'translate-x-0.5'}"
				></span>
			</button>
		</div>

		{#if form.enabled}
			<div class="flex flex-col gap-3 border-t border-border pt-4">
				<div class="flex flex-col gap-1">
					<label
						class="text-xs font-medium text-muted-foreground"
						for="rate-limit-429-seconds"
					>
						{$_('admin.settings.rateLimit429Cooldown.cooldownSeconds')}
					</label>
					<input
						id="rate-limit-429-seconds"
						type="number"
						min="1"
						max="7200"
						data-testid="rate-limit-429-seconds"
						class="h-9 w-32 rounded-md border border-input bg-background px-3 font-mono text-sm focus:outline-none focus:ring-1 focus:ring-ring"
						value={form.cooldown_seconds}
						oninput={onCooldownInput}
					/>
					<p class="mt-0.5 text-xs leading-relaxed text-muted-foreground">
						{$_('admin.settings.rateLimit429Cooldown.cooldownSecondsHint')}
					</p>
				</div>
			</div>
		{/if}

		<div class="flex justify-end border-t border-border pt-4">
			<button
				type="button"
				data-testid="rate-limit-429-save"
				disabled={saving}
				onclick={save}
				class="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-3 text-sm hover:bg-accent disabled:opacity-50"
			>
				{saving ? $_('common.saving') : $_('common.save')}
			</button>
		</div>
	{/if}
</div>
