// frontend-svelte/src/lib/registry/SectionRenderer.svelte
<script lang="ts">
	/**
	 * SectionRenderer · 单 section 卡片（POC 4）
	 *
	 * 端口自 frontend/src/views/admin/settings-registry/SectionRenderer.vue。
	 *
	 * 两态路由：
	 *   1. section.special 命中 → 渲染对应 special 组件，原生字段 grid 不出。
	 *   2. 否则展开 section.fields → 每条字段走 FieldRenderer。
	 *
	 * Callback props（Svelte 5 idiomatic）：
	 *   - onFieldUpdate({ key, value }) —— FieldRenderer onUpdate(value) + key 包装后调用
	 *     上抛父级。Special 组件也走同一 callback。
	 *   - 不再用 createEventDispatcher —— runes 模式下回调 prop 更直观、测试更友好。
	 */
	import { _ } from 'svelte-i18n';
	import FieldRenderer from './FieldRenderer.svelte';
	import SmtpSection from './special/SmtpSection.svelte';
	import TestEmailSection from './special/TestEmailSection.svelte';
	import type { SectionDef } from './types';

	type FieldUpdate = { key: string; value: unknown };

	type Props = {
		section: SectionDef;
		values: Record<string, unknown>;
		dirtyKeys: Set<string>;
		onFieldUpdate?: (e: FieldUpdate) => void;
	};

	const { section, values, dirtyKeys, onFieldUpdate }: Props = $props();

	const title = $derived.by(() => {
		const t = $_(section.titleKey);
		return t === section.titleKey ? section.id : t;
	});

	const description = $derived.by(() => {
		if (!section.descriptionKey) return '';
		const t = $_(section.descriptionKey);
		return t === section.descriptionKey ? '' : t;
	});

	function bubble(key: string, value: unknown) {
		onFieldUpdate?.({ key, value });
	}
</script>

<section
	class="rounded-lg border border-border bg-card p-5"
	data-section-id={section.id}
>
	<header class="mb-4">
		<h2 class="text-base font-semibold text-foreground">{title}</h2>
		{#if description}
			<p class="mt-1 text-xs text-muted-foreground">{description}</p>
		{/if}
	</header>

	{#if section.special === 'smtp'}
		<SmtpSection {values} {dirtyKeys} {onFieldUpdate} />
	{:else if section.special === 'test-email'}
		<TestEmailSection {values} {dirtyKeys} {onFieldUpdate} />
	{:else if section.special}
		<p class="text-xs text-destructive">[unknown special: {section.special}]</p>
	{:else if section.fields && section.fields.length > 0}
		<div class="grid gap-4 [grid-template-columns:repeat(auto-fill,minmax(280px,1fr))]">
			{#each section.fields as field (field.key)}
				<FieldRenderer
					{field}
					value={values[field.key]}
					dirty={dirtyKeys.has(field.key)}
					formValues={values}
					onUpdate={(v) => bubble(field.key, v)}
				/>
			{/each}
		</div>
	{:else}
		<p class="text-xs text-muted-foreground">[empty section]</p>
	{/if}
</section>

// frontend/src/views/admin/settings-registry/SectionRenderer.vue
<template>
  <div :id="`sr-section-${section.id}`" class="overflow-hidden rounded-xl border border-border bg-card shadow-sm scroll-mt-24">
    <!-- card header -->
    <div class="border-b border-border bg-muted/30 px-5 py-3.5">
      <h2 class="mb-0.5 text-[13.5px] font-semibold tracking-tight text-foreground">{{ resolveLabel(section.title) }}</h2>
      <p v-if="section.description" class="text-[11.5px] leading-[1.55] text-muted-foreground">{{ resolveLabel(section.description) }}</p>
    </div>

    <!-- custom component escape hatch -->
    <component
      v-if="section.component"
      :is="section.component"
      :settings="settings"
      :form-values="form"
      @update:field="onFieldUpdate"
    />

    <!-- field grid -->
    <div v-else class="grid gap-5 p-5 [grid-template-columns:repeat(auto-fill,minmax(280px,1fr))]">
      <FieldRenderer
        v-for="field in section.fields"
        :key="field.key"
        :field="field"
        :model-value="form[field.key]"
        :form-values="form"
        @update:model-value="onFieldUpdate(field.key, $event)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import FieldRenderer from './FieldRenderer.vue'
import type { SettingsSection } from './types'

defineProps<{
  section: SettingsSection
  form: Record<string, unknown>
  settings: Record<string, unknown>
}>()

const emit = defineEmits<{
  'update:field': [key: string, value: unknown]
}>()

const { t } = useI18n()

function resolveLabel(key: string): string {
  try {
    const result = t(key)
    return result === key ? key : result
  } catch {
    return key
  }
}

function onFieldUpdate(key: string, value: unknown) {
  emit('update:field', key, value)
}
</script>
