// frontend/src/components/shell/AppTopbar.vue
<template>
  <header
    class="sticky top-0 z-20 flex h-[54px] shrink-0 items-center gap-4 border-b border-border bg-background/80 px-[22px] backdrop-blur-[8px]"
  >
    <!-- Breadcrumb -->
    <div class="flex min-w-0 items-center text-[12.5px]">
      <span v-if="currentGroup" class="text-muted-foreground">
        {{ t(currentGroup.labelKey) }}
      </span>
      <span v-if="currentGroup && currentItem" class="mx-[7px] text-muted-foreground/50">›</span>
      <span v-if="currentItem" class="font-semibold text-foreground">
        {{ t(currentItem.labelKey) }}
      </span>
    </div>

    <!-- ⌘K pill (admin only in v.22) -->
    <Button
      v-if="showCommandPalette"
      variant="outline"
      class="ml-auto flex min-w-[220px] cursor-pointer items-center gap-2 rounded-[9px] bg-muted px-[11px] py-1.5 text-xs text-muted-foreground transition-colors hover:border-ring/40 hover:shadow-[0_0_14px_hsl(var(--ring)/0.12)]"
      data-tour="cmdk"
      @click="emit('openCommandPalette')"
      :title="t('nav.quench.openCommandPalette')"
    >
      <Search class="h-[13px] w-[13px] shrink-0" />
      <span class="flex-1 text-left">{{ t('nav.quench.searchPlaceholder') }}</span>
      <kbd
        class="ml-auto rounded border border-border bg-background px-1.5 py-[2px] font-mono text-[10px] text-muted-foreground"
      >⌘K</kbd>
    </Button>
    <!-- Spacer when palette hidden: keep right cluster anchored to the right -->
    <div v-else class="ml-auto"></div>

    <!-- Right section: theme + locale + user -->
    <div class="flex shrink-0 items-center gap-2">
      <!-- Theme Toggle -->
      <Button
        variant="ghost"
        size="icon"
        @click="toggleTheme"
        :title="isDark ? t('nav.lightMode') : t('nav.darkMode')"
      >
        <Sun v-if="isDark" class="h-[15px] w-[15px]" />
        <Moon v-else class="h-[15px] w-[15px]" />
      </Button>

      <!-- Locale Switcher -->
      <LocaleSwitcher />

      <!-- User avatar + dropdown -->
      <div class="relative" ref="dropdownRef">
        <Button
          variant="ghost"
          class="h-[30px] w-[30px] shrink-0 overflow-hidden rounded-full bg-muted p-0 text-[12px] font-bold text-foreground"
          @click="toggleDropdown"
          :title="displayName"
        >
          <img
            v-if="avatarUrl"
            :src="avatarUrl"
            :alt="displayName"
            class="h-full w-full object-cover"
          />
          <span v-else>{{ userInitials }}</span>
        </Button>

        <transition
          enter-active-class="transition-[opacity,transform] duration-150 ease-out"
          enter-from-class="opacity-0 scale-95 -translate-y-1"
          leave-active-class="transition-[opacity,transform] duration-150 ease-in"
          leave-to-class="opacity-0 scale-95 -translate-y-1"
        >
          <div
            v-if="dropdownOpen"
            class="absolute right-0 top-[calc(100%+6px)] z-50 w-[200px] overflow-hidden rounded-[10px] border border-border bg-popover shadow-[0_16px_48px_hsl(0_0%_0%/0.35)]"
          >
            <div class="border-b border-border px-[14px] pb-2.5 pt-3">
              <div class="truncate text-[13px] font-semibold text-foreground">{{ displayName }}</div>
              <div class="mt-0.5 truncate text-[11px] text-muted-foreground">{{ user?.email }}</div>
            </div>
            <div class="p-[6px_4px]">
              <router-link
                to="/profile"
                class="flex w-full cursor-pointer items-center gap-[9px] rounded-[7px] border-none bg-transparent px-2.5 py-[7px] text-[12.5px] text-muted-foreground no-underline transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-[1.5px] focus-visible:ring-inset focus-visible:ring-ring"
                @click="closeDropdown"
              >
                <UserIcon class="h-[14px] w-[14px] shrink-0 opacity-85" />
                {{ t('nav.profile') }}
              </router-link>
              <router-link
                v-if="showSwitchToUser"
                to="/dashboard"
                data-testid="topbar-switch-to-user"
                class="flex w-full cursor-pointer items-center gap-[9px] rounded-[7px] border-none bg-transparent px-2.5 py-[7px] text-[12.5px] text-muted-foreground no-underline transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-[1.5px] focus-visible:ring-inset focus-visible:ring-ring"
                @click="closeDropdown"
              >
                <LayoutDashboard class="h-[14px] w-[14px] shrink-0 opacity-85" />
                {{ t('nav.switchToUserView') }}
              </router-link>
              <router-link
                v-if="showSwitchToAdmin"
                to="/admin/dashboard"
                data-testid="topbar-switch-to-admin"
                class="flex w-full cursor-pointer items-center gap-[9px] rounded-[7px] border-none bg-transparent px-2.5 py-[7px] text-[12.5px] text-muted-foreground no-underline transition-colors hover:bg-accent hover:text-foreground focus-visible:outline-none focus-visible:ring-[1.5px] focus-visible:ring-inset focus-visible:ring-ring"
                @click="closeDropdown"
              >
                <ShieldCheck class="h-[14px] w-[14px] shrink-0 opacity-85" />
                {{ t('nav.switchToAdminView') }}
              </router-link>
            </div>
            <div class="border-t border-border p-[6px_4px]">
              <Button
                variant="ghost"
                class="flex w-full items-center justify-start gap-[9px] rounded-[7px] px-2.5 py-[7px] text-[12.5px] text-destructive hover:bg-destructive/10 hover:text-destructive"
                @click="handleLogout"
              >
                <LogOut class="h-[14px] w-[14px] shrink-0 opacity-85" />
                {{ t('nav.logout') }}
              </Button>
            </div>
          </div>
        </transition>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Search, Sun, Moon, User as UserIcon, LogOut, LayoutDashboard, ShieldCheck } from 'lucide-vue-next'
import { Button } from '@/components/ui/button'
import { useAuthStore } from '@/stores'
import LocaleSwitcher from '@/components/common/LocaleSwitcher.vue'
import { resolveNavItem, type NavGroup } from './nav'
import { useTheme } from '@/composables/useTheme'

const props = withDefaults(
  defineProps<{
    /** 当前 shell 的 NavGroup 列表，用于面包屑反查 */
    navGroups: NavGroup[]
    /** 是否在 topbar 渲染 ⌘K 按钮（与 AppShell 内部的 CommandPalette 联动） */
    showCommandPalette?: boolean
  }>(),
  { showCommandPalette: false }
)

const emit = defineEmits<{
  openCommandPalette: []
}>()

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const user = computed(() => authStore.user)
const dropdownOpen = ref(false)
const dropdownRef = ref<HTMLElement | null>(null)

const resolved = computed(() => resolveNavItem(route.path, props.navGroups))
const currentGroup = computed(() => resolved.value?.group ?? null)
const currentItem = computed(() => resolved.value?.item ?? null)

// Admin <-> user view cross-link:
// - admin on /admin/*  → show "Switch to user view" → /dashboard
// - admin on user-side → show "Back to admin panel" → /admin/dashboard
const isAdmin = computed(() => authStore.isAdmin)
const isOnAdminRoute = computed(() => route.path.startsWith('/admin'))
const showSwitchToUser = computed(() => isAdmin.value && isOnAdminRoute.value)
const showSwitchToAdmin = computed(() => isAdmin.value && !isOnAdminRoute.value)

const avatarUrl = computed(() => user.value?.avatar_url?.trim() || '')
const userInitials = computed(() => {
  if (!user.value) return ''
  if (user.value.username) return user.value.username.substring(0, 2).toUpperCase()
  if (user.value.email) return user.value.email.split('@')[0].substring(0, 2).toUpperCase()
  return ''
})
const displayName = computed(() => {
  if (!user.value) return ''
  return user.value.username || user.value.email?.split('@')[0] || ''
})

const { isDark, toggle: toggleTheme } = useTheme()

function toggleDropdown() {
  dropdownOpen.value = !dropdownOpen.value
}

function closeDropdown() {
  dropdownOpen.value = false
}

async function handleLogout() {
  closeDropdown()
  try {
    await authStore.logout()
  } catch {
    // ignore logout errors; we still route to /login
  }
  await router.push('/login')
}

function handleClickOutside(event: MouseEvent) {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) {
    closeDropdown()
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onBeforeUnmount(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

// frontend-svelte/src/lib/shell/AppTopbar.svelte
<script lang="ts">
	/**
	 * AppTopbar · 顶栏（Svelte 端口）
	 *
	 * 端口自 frontend/src/components/shell/AppTopbar.vue:1-219，关键差异：
	 *   - 头像下拉用 bits-ui 的 DropdownMenu（替代手写 click-outside + transition）
	 *   - 主题切换托管给上层（用 prop callback）—— shell 层不直接耦合 theme store
	 *   - 语言切换托管给上层 prop callback —— 与现有 LocaleSwitcher 解耦
	 *   - 密度切换：comfortable ↔ compact，state 由上层管理，topbar 仅显示按钮
	 *
	 * 切换跳转：
	 *   variant='admin' → 显示 'Switch to user view' → href="/dashboard"
	 *   variant='user' + role==='admin' → 显示 'Switch to admin view' → href="/admin/orders"
	 *   （Vue tree 默认指向 /admin/dashboard，这里改 /admin/orders 是按 task brief 要求）
	 */
	import { _, locale } from 'svelte-i18n';
	import { DropdownMenu } from 'bits-ui';
	import {
		ChevronDown,
		Languages,
		LayoutGrid,
		Sun,
		Moon,
		User,
		LogOut,
		LayoutDashboard,
		ShieldCheck
	} from '@lucide/svelte';
	import type { NavGroup } from './nav';
	import { resolveNavItem } from './nav';
	import Button from '$lib/ui/Button.svelte';

	type Props = {
		variant: 'user' | 'admin';
		user: { email: string; role: string; username?: string; avatarUrl?: string } | null;
		navGroups?: NavGroup[];
		activePath?: string;
		density?: 'compact' | 'comfortable';
		isDark?: boolean;
		onToggleTheme?: () => void;
		onToggleDensity?: () => void;
		onToggleLocale?: () => void;
		onLogout?: () => void;
	};

	const {
		variant,
		user,
		navGroups = [],
		activePath = '',
		density = 'comfortable',
		isDark = false,
		onToggleTheme,
		onToggleDensity,
		onToggleLocale,
		onLogout
	}: Props = $props();

	/** Breadcrumb：当前 path 命中的 group/item 标签。 */
	const crumb = $derived(activePath ? resolveNavItem(activePath, navGroups) : null);

	/** 头像 2 字母 fallback —— 取 username 首2 字符或 email local-part。 */
	const initials = $derived.by(() => {
		if (!user) return '?';
		const src = user.username || user.email.split('@')[0] || '?';
		return src.slice(0, 2).toUpperCase();
	});

	const displayName = $derived(user?.username || user?.email || '');

	/** locale 当前是否为英文（仅用于按钮上显示 "EN" / "中"，不参与切换逻辑）。 */
	const localeShort = $derived($locale?.startsWith('en') ? 'EN' : '中');
</script>

<header
	class="sticky top-0 z-30 flex items-center gap-3 border-b bg-background/80 px-[22px] backdrop-blur-[8px]"
	style="height: 64px;"
	data-variant={variant}
>
	<!-- 面包屑 / 页面标题 -->
	<div class="flex min-w-0 flex-1 items-center text-sm">
		{#if crumb}
			<span class="text-muted-foreground">{$_(crumb.group.labelKey)}</span>
			<span class="mx-2 text-muted-foreground">›</span>
			<span class="truncate font-semibold">{$_(crumb.item.labelKey)}</span>
		{:else}
			<span class="font-semibold capitalize">{variant}</span>
		{/if}
	</div>

	<!-- 右侧操作簇 -->
	<div class="flex items-center gap-2">
		<!-- 语言切换 -->
		<Button
			variant="outline"
			onclick={onToggleLocale}
			class="gap-1 bg-transparent text-xs text-muted-foreground hover:bg-muted hover:text-foreground"
			style="height: var(--input-h); padding-left: var(--px); padding-right: var(--px);"
			aria-label={$_('topbar.toggleLanguage', { default: 'Toggle language' })}
			data-testid="topbar-locale"
		>
			<Languages class="h-4 w-4" />
			<span>{localeShort}</span>
		</Button>

		<!-- 密度切换 -->
		<Button
			variant="outline"
			size="icon"
			onclick={onToggleDensity}
			class="bg-transparent text-muted-foreground hover:bg-muted hover:text-foreground"
			style="height: var(--input-h); width: var(--input-h);"
			aria-label={$_('topbar.toggleDensity', { default: 'Toggle density' })}
			aria-pressed={density === 'compact'}
			data-testid="topbar-density"
			title={density}
		>
			<LayoutGrid class="h-4 w-4" />
		</Button>

		<!-- 主题切换 -->
		<Button
			variant="outline"
			size="icon"
			onclick={onToggleTheme}
			class="bg-transparent text-muted-foreground hover:bg-muted hover:text-foreground"
			style="height: var(--input-h); width: var(--input-h);"
			aria-label={$_('topbar.toggleTheme', { default: 'Toggle theme' })}
			data-testid="topbar-theme"
		>
			{#if isDark}
				<Sun class="h-4 w-4" />
			{:else}
				<Moon class="h-4 w-4" />
			{/if}
		</Button>

		<!-- 头像 + 下拉 -->
		{#if user}
			<DropdownMenu.Root>
				<DropdownMenu.Trigger
					class="inline-flex items-center gap-1.5 rounded-full border bg-transparent pl-1 pr-2 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
					style="height: var(--input-h);"
					aria-label={$_('topbar.accountMenu', { default: 'Account menu' })}
					data-testid="topbar-avatar"
				>
					{#if user.avatarUrl}
						<img
							src={user.avatarUrl}
							alt=""
							class="h-7 w-7 rounded-full object-cover"
						/>
					{:else}
						<span
							class="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-[11px] font-bold text-primary-foreground"
						>
							{initials}
						</span>
					{/if}
					<ChevronDown class="h-3.5 w-3.5 text-muted-foreground" />
				</DropdownMenu.Trigger>
				<DropdownMenu.Portal>
					<DropdownMenu.Content
						class="z-50 min-w-[220px] rounded-md border bg-popover p-1 text-popover-foreground shadow-md"
						sideOffset={6}
						align="end"
					>
						<div class="px-2 py-1.5">
							<div class="truncate text-sm font-semibold">{displayName}</div>
							{#if user.email && user.email !== displayName}
								<div class="truncate text-xs text-muted-foreground">{user.email}</div>
							{/if}
						</div>
						<DropdownMenu.Separator class="my-1 h-px bg-border" />

						<DropdownMenu.Item
							class="flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none hover:bg-muted focus:bg-muted"
						>
							{#snippet child({ props })}
								<a {...props} href="/profile" data-testid="topbar-profile">
									<User class="h-4 w-4" />
									<span>{$_('nav.profile', { default: 'Profile' })}</span>
								</a>
							{/snippet}
						</DropdownMenu.Item>

						{#if variant === 'admin'}
							<DropdownMenu.Item
								class="flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none hover:bg-muted focus:bg-muted"
							>
								{#snippet child({ props })}
									<a
										{...props}
										href="/dashboard"
										data-testid="topbar-switch-to-user"
									>
										<LayoutDashboard class="h-4 w-4" />
										<span>{$_('nav.switchToUserView', { default: 'Switch to user view' })}</span>
									</a>
								{/snippet}
							</DropdownMenu.Item>
						{:else if variant === 'user' && user.role === 'admin'}
							<DropdownMenu.Item
								class="flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none hover:bg-muted focus:bg-muted"
							>
								{#snippet child({ props })}
									<a
										{...props}
										href="/admin/dashboard"
										data-testid="topbar-switch-to-admin"
									>
										<ShieldCheck class="h-4 w-4" />
										<span>{$_('nav.switchToAdminView', { default: 'Switch to admin view' })}</span>
									</a>
								{/snippet}
							</DropdownMenu.Item>
						{/if}

						<DropdownMenu.Separator class="my-1 h-px bg-border" />

						<DropdownMenu.Item
							onSelect={onLogout}
							class="flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm text-destructive outline-none hover:bg-destructive/10 focus:bg-destructive/10"
							data-testid="topbar-logout"
						>
							<LogOut class="h-4 w-4" />
							<span>{$_('nav.logout', { default: 'Log out' })}</span>
						</DropdownMenu.Item>
					</DropdownMenu.Content>
				</DropdownMenu.Portal>
			</DropdownMenu.Root>
		{/if}
	</div>
</header>
