// frontend-svelte/src/lib/features/channel-monitor/MonitorTemplateManagerDialog.svelte
<script lang="ts">
	/**
	 * MonitorTemplateManagerDialog — provider-tabbed CRUD for monitor request templates.
	 *
	 * Features:
	 *   - Provider tabs (Anthropic / OpenAI / Gemini) with template count badges
	 *   - List view: templates for active provider, with edit / delete / apply actions
	 *   - Create / edit form with AdvancedRequestConfig (headers + body override)
	 *   - Apply picker: propagate template settings to associated monitors
	 *
	 * Ported from Vue MonitorTemplateManagerDialog.vue.
	 */
	import { _ } from 'svelte-i18n';
	import { Plus, RefreshCw, ArrowLeft } from '@lucide/svelte';
	import type { APIMode, BodyOverrideMode, Provider } from '$lib/api/admin/channelMonitor';
	import {
		list as listTemplates,
		create as createTemplate,
		update as updateTemplate,
		del as deleteTemplate,
		type ChannelMonitorTemplate
	} from '$lib/api/admin/channelMonitorTemplate';
	import Badge from '$lib/ui/Badge.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Input from '$lib/ui/Input.svelte';
	import StandardDialog from '$lib/ui/StandardDialog.svelte';
	import { showError, showSuccess } from '$lib/stores/toast.svelte';
	import { providerLabel } from './channel-monitor';
	import AdvancedRequestConfig from './AdvancedRequestConfig.svelte';
	import TemplateApplyPickerDialog from './TemplateApplyPickerDialog.svelte';

	type Props = {
		open: boolean;
		onUpdated?: () => void;
	};

	let { open = $bindable(false), onUpdated }: Props = $props();

	const PROVIDERS: Provider[] = ['anthropic', 'openai', 'gemini'];

	let activeProvider = $state<Provider>('anthropic');
	let templates = $state<ChannelMonitorTemplate[]>([]);
	let loading = $state(false);
	let editing = $state<null | 'new' | number>(null); // null = list; 'new' = create; number = edit
	let submitting = $state(false);

	// ── Form state ───────────────────────────────────────────────────
	let formName = $state('');
	let formProvider = $state<Provider>('anthropic');
	let formApiMode = $state<APIMode>('chat_completions');
	let formDescription = $state('');
	let formExtraHeaders = $state<Record<string, string>>({});
	let formBodyOverrideMode = $state<BodyOverrideMode>('off');
	let formBodyOverride = $state<Record<string, unknown> | null>(null);

	// ── Derived ──────────────────────────────────────────────────────
	const templatesForActiveProvider = $derived(
		templates.filter((t) => t.provider === activeProvider)
	);

	const countByProvider = $derived(() => {
		const out: Record<Provider, number> = { anthropic: 0, openai: 0, gemini: 0 };
		for (const t of templates) {
			if (t.provider in out) out[t.provider as Provider]++;
		}
		return out;
	});

	// ── Apply picker state ───────────────────────────────────────────
	let applyPickerOpen = $state(false);
	let applyPickerTemplateId = $state<number | null>(null);
	let applyPickerTemplateName = $state('');

	// ── Delete confirm state ─────────────────────────────────────────
	let confirmDeleteOpen = $state(false);
	let confirmDeleteTemplate = $state<ChannelMonitorTemplate | null>(null);

	// ── Lifecycle ────────────────────────────────────────────────────
	$effect(() => {
		if (open) {
			editing = null;
			void fetchTemplates();
		}
	});

	// ── Data fetch ───────────────────────────────────────────────────
	async function fetchTemplates() {
		loading = true;
		try {
			templates = await listTemplates();
		} catch (err) {
			showError(err instanceof Error ? err.message : String(err));
		} finally {
			loading = false;
		}
	}

	// ── Form helpers ─────────────────────────────────────────────────
	function resetForm(provider: Provider) {
		formName = '';
		formProvider = provider;
		formApiMode = 'chat_completions';
		formDescription = '';
		formExtraHeaders = {};
		formBodyOverrideMode = 'off';
		formBodyOverride = null;
	}

	function loadForm(tpl: ChannelMonitorTemplate) {
		formName = tpl.name;
		formProvider = tpl.provider;
		formApiMode = tpl.api_mode === 'responses' ? 'responses' : 'chat_completions';
		formDescription = tpl.description || '';
		formExtraHeaders = { ...(tpl.extra_headers || {}) };
		formBodyOverrideMode = (tpl.body_override_mode as BodyOverrideMode) || 'off';
		formBodyOverride = tpl.body_override ? { ...tpl.body_override } : null;
	}

	function openCreateForm() {
		resetForm(activeProvider);
		editing = 'new';
	}

	function openEditForm(tpl: ChannelMonitorTemplate) {
		loadForm(tpl);
		editing = tpl.id;
	}

	function backToList() {
		editing = null;
	}

	// ── Submit ───────────────────────────────────────────────────────
	async function handleSubmit() {
		if (submitting) return;
		if (!formName.trim()) {
			showError(
				$_('admin.channelMonitor.template.missingName', { default: 'Template name is required' })
			);
			return;
		}
		submitting = true;
		try {
			if (editing === 'new') {
				await createTemplate({
					name: formName.trim(),
					provider: formProvider,
					api_mode: formProvider === 'openai' ? formApiMode : 'chat_completions',
					description: formDescription.trim(),
					extra_headers: formExtraHeaders,
					body_override_mode: formBodyOverrideMode,
					body_override: formBodyOverride
				});
				showSuccess(
					$_('admin.channelMonitor.template.createSuccess', {
						default: 'Template created'
					})
				);
			} else if (typeof editing === 'number') {
				await updateTemplate(editing, {
					name: formName.trim(),
					api_mode: formProvider === 'openai' ? formApiMode : 'chat_completions',
					description: formDescription.trim(),
					extra_headers: formExtraHeaders,
					body_override_mode: formBodyOverrideMode,
					body_override: formBodyOverride
				});
				showSuccess(
					$_('admin.channelMonitor.template.updateSuccess', {
						default: 'Template updated'
					})
				);
			}
			await fetchTemplates();
			onUpdated?.();
			editing = null;
		} catch (err) {
			showError(err instanceof Error ? err.message : String(err));
		} finally {
			submitting = false;
		}
	}

	// ── Apply ────────────────────────────────────────────────────────
	function confirmApply(tpl: ChannelMonitorTemplate) {
		applyPickerTemplateId = tpl.id;
		applyPickerTemplateName = tpl.name;
		applyPickerOpen = true;
	}

	async function onApplied(_affected: number) {
		await fetchTemplates();
		onUpdated?.();
	}

	// ── Delete ───────────────────────────────────────────────────────
	function handleDelete(tpl: ChannelMonitorTemplate) {
		confirmDeleteTemplate = tpl;
		confirmDeleteOpen = true;
	}

	async function doDelete() {
		const tpl = confirmDeleteTemplate;
		confirmDeleteOpen = false;
		if (!tpl) return;
		try {
			await deleteTemplate(tpl.id);
			showSuccess(
				$_('admin.channelMonitor.template.deleteSuccess', { default: 'Template deleted' })
			);
			await fetchTemplates();
			onUpdated?.();
		} catch (err) {
			showError(err instanceof Error ? err.message : String(err));
		}
	}

	// ── Style helpers ────────────────────────────────────────────────
	function tabClass(value: Provider): string {
		return activeProvider === value
			? 'border-b-2 border-primary text-primary'
			: 'border-b-2 border-transparent text-muted-foreground hover:text-foreground';
	}

	function modeBadgeClass(mode: string): string {
		switch (mode) {
			case 'merge':
				return 'border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-300';
			case 'replace':
				return 'border-purple-500/30 bg-purple-500/10 text-purple-700 dark:text-purple-300';
			default:
				return 'border-border bg-muted text-muted-foreground';
		}
	}

	function modeLabel(mode: string): string {
		switch (mode) {
			case 'merge':
				return $_('admin.channelMonitor.advanced.bodyModeMerge', { default: 'Merge' });
			case 'replace':
				return $_('admin.channelMonitor.advanced.bodyModeReplace', { default: 'Replace' });
			default:
				return $_('admin.channelMonitor.advanced.bodyModeOff', { default: 'Off' });
		}
	}

	function apiModeBadgeClass(mode: APIMode): string {
		return mode === 'responses'
			? 'border-sky-500/30 bg-sky-500/10 text-sky-700 dark:text-sky-300'
			: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300';
	}

	function apiModeLabel(mode: APIMode): string {
		return mode === 'responses'
			? $_('admin.channelMonitor.form.apiModeResponses', { default: 'Responses' })
			: $_('admin.channelMonitor.form.apiModeChatCompletions', { default: 'Chat completions' });
	}

	const apiModeOptions: { value: APIMode; label: string; hint: string }[] = [
		{
			value: 'chat_completions',
			label: 'Chat completions',
			hint: 'Standard /v1/chat/completions endpoint'
		},
		{
			value: 'responses',
			label: 'Responses',
			hint: 'New /v1/responses endpoint'
		}
	];

	function providerPickerClass(value: Provider, isActive: boolean): string {
		if (!isActive) return 'border-border bg-card text-muted-foreground hover:border-primary/50';
		switch (value) {
			case 'openai':
				return 'border-emerald-500 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300';
			case 'anthropic':
				return 'border-orange-500 bg-orange-500/10 text-orange-700 dark:text-orange-300';
			case 'gemini':
				return 'border-sky-500 bg-sky-500/10 text-sky-700 dark:text-sky-300';
			default:
				return 'border-primary bg-primary/10 text-primary';
		}
	}
</script>

<StandardDialog
	bind:open
	title={$_('admin.channelMonitor.template.managerTitle', { default: 'Template manager' })}
	width="lg"
	data-testid="template-manager-dialog"
>
	<div class="mt-4 space-y-4">
		<!-- Provider tabs -->
		<div class="border-b border-border">
			<div role="tablist" class="flex gap-1">
				{#each PROVIDERS as p (p)}
					<button
						type="button"
						role="tab"
						aria-selected={activeProvider === p}
						class="rounded-none px-4 py-2 text-sm font-medium transition-colors {tabClass(p)}"
						onclick={() => {
							activeProvider = p;
							if (editing !== null) backToList();
						}}
					>
						{providerLabel(p)}
						{#if countByProvider()[p] > 0}
							<Badge variant="secondary" class="ml-1.5">{countByProvider()[p]}</Badge>
						{/if}
					</button>
				{/each}
			</div>
		</div>

		<!-- List view -->
		{#if editing === null}
			<div class="flex justify-end">
				<Button size="sm" onclick={openCreateForm}>
					<Plus class="mr-1 h-4 w-4" />
					{$_('admin.channelMonitor.template.createButton', { default: 'Create template' })}
				</Button>
			</div>

			{#if loading}
				<div class="py-8 text-center text-sm text-muted-foreground">
					{$_('common.loading', { default: 'Loading...' })}
				</div>
			{:else if templatesForActiveProvider.length === 0}
				<div class="py-8 text-center text-sm text-muted-foreground">
					{$_('admin.channelMonitor.template.emptyState', {
						default: 'No templates for this provider yet.'
					})}
				</div>
			{:else}
				{#each templatesForActiveProvider as tpl (tpl.id)}
					<div
						class="rounded-lg border border-border bg-card p-4"
						data-testid="template-card"
						data-template-id={tpl.id}
					>
						<div class="flex items-start justify-between gap-3">
							<div class="min-w-0 flex-1">
								<div class="flex items-center gap-2">
									<span class="font-medium text-foreground">{tpl.name}</span>
									<Badge variant="outline" class={modeBadgeClass(tpl.body_override_mode)}>
										{modeLabel(tpl.body_override_mode)}
									</Badge>
									{#if tpl.provider === 'openai'}
										<Badge variant="outline" class={apiModeBadgeClass(tpl.api_mode)}>
											{apiModeLabel(tpl.api_mode)}
										</Badge>
									{/if}
									{#if tpl.associated_monitors > 0}
										<span class="text-xs text-muted-foreground">
											{$_('admin.channelMonitor.template.associatedCount', {
												default: `${tpl.associated_monitors} monitors`,
												values: { n: tpl.associated_monitors }
											})}
										</span>
									{/if}
								</div>
								{#if tpl.description}
									<p class="mt-0.5 text-xs text-muted-foreground">{tpl.description}</p>
								{/if}
								<p class="mt-1 text-xs text-muted-foreground">
									{$_('admin.channelMonitor.template.headersSummary', {
										default: `${Object.keys(tpl.extra_headers || {}).length} custom headers`,
										values: { n: Object.keys(tpl.extra_headers || {}).length }
									})}
								</p>
							</div>
							<div class="flex flex-shrink-0 gap-2">
								<Button
									variant="outline"
									size="sm"
									disabled={tpl.associated_monitors === 0}
									title={$_('admin.channelMonitor.template.applyTooltip', {
										default: 'Apply template settings to associated monitors'
									})}
									onclick={() => confirmApply(tpl)}
								>
									<RefreshCw class="mr-1 inline h-3.5 w-3.5" />
									{$_('admin.channelMonitor.template.applyButton', { default: 'Apply' })}
								</Button>
								<Button variant="outline" size="sm" onclick={() => openEditForm(tpl)}>
									{$_('common.edit', { default: 'Edit' })}
								</Button>
								<Button
									variant="outline"
									size="sm"
									class="text-destructive hover:text-destructive"
									onclick={() => handleDelete(tpl)}
								>
									{$_('common.delete', { default: 'Delete' })}
								</Button>
							</div>
						</div>
					</div>
				{/each}
			{/if}
		{:else}
			<!-- Create / Edit form -->
			<div class="space-y-4">
				<div>
					<p class="mb-1.5 text-sm font-medium text-foreground">
						{$_('admin.channelMonitor.template.form.name', { default: 'Name' })}
						<span class="text-destructive">*</span>
					</p>
					<Input
						bind:value={formName}
						placeholder={$_('admin.channelMonitor.template.form.namePlaceholder', {
							default: 'e.g. Official client headers'
						})}
					/>
				</div>

				{#if editing === 'new'}
					<div>
						<p class="mb-1.5 text-sm font-medium text-foreground">
							{$_('admin.channelMonitor.form.provider', { default: 'Provider' })}
							<span class="text-destructive">*</span>
						</p>
						<div class="grid grid-cols-3 gap-3">
							{#each PROVIDERS as p (p)}
								<Button
									variant="outline"
									class="rounded-lg border-2 px-3 py-2 text-sm font-medium transition-colors {providerPickerClass(p, formProvider === p)}"
									onclick={() => {
										formProvider = p;
										if (p !== 'openai') formApiMode = 'chat_completions';
									}}
								>
									{providerLabel(p)}
								</Button>
							{/each}
						</div>
					</div>
				{/if}

				{#if formProvider === 'openai'}
					<div class="rounded-lg border border-border bg-accent p-3">
						<p class="mb-1.5 text-sm font-medium text-foreground">
							{$_('admin.channelMonitor.form.apiMode', { default: 'API mode' })}
						</p>
						<div class="grid gap-3 sm:grid-cols-2">
							{#each apiModeOptions as opt (opt.value)}
								<Button
									variant="outline"
									class="h-auto flex-col items-start rounded-lg border-2 px-3 py-2 text-left transition-colors {formApiMode === opt.value
										? 'border-primary bg-primary/15 text-primary shadow-sm'
										: 'border-border bg-card text-muted-foreground hover:border-primary/50'}"
									onclick={() => (formApiMode = opt.value)}
								>
									<span class="block text-sm font-semibold">{opt.label}</span>
									<span class="mt-0.5 block text-xs opacity-80">{opt.hint}</span>
								</Button>
							{/each}
						</div>
					</div>
				{/if}

				<div>
					<p class="mb-1.5 text-sm font-medium text-foreground">
						{$_('admin.channelMonitor.template.form.description', { default: 'Description' })}
					</p>
					<Input
						bind:value={formDescription}
						placeholder={$_('admin.channelMonitor.template.form.descriptionPlaceholder', {
							default: 'Optional description'
						})}
					/>
				</div>

				<AdvancedRequestConfig
					provider={formProvider}
					apiMode={formApiMode}
					extraHeaders={formExtraHeaders}
					bodyOverrideMode={formBodyOverrideMode}
					bodyOverride={formBodyOverride}
					onHeadersChange={(h) => (formExtraHeaders = h)}
					onBodyModeChange={(m) => (formBodyOverrideMode = m)}
					onBodyChange={(b) => (formBodyOverride = b)}
				/>
			</div>
		{/if}

		<!-- Footer actions -->
		<div class="flex items-center justify-between border-t border-border pt-3">
			<div>
				{#if editing !== null}
					<Button variant="outline" onclick={backToList}>
						<ArrowLeft class="mr-1 h-4 w-4" />
						{$_('common.back', { default: 'Back' })}
					</Button>
				{/if}
			</div>
			<div class="flex gap-2">
				<Button variant="outline" onclick={() => (open = false)}>
					{$_('common.close', { default: 'Close' })}
				</Button>
				{#if editing !== null}
					<Button disabled={submitting} onclick={handleSubmit}>
						{#if submitting}
							{$_('common.submitting', { default: 'Saving...' })}
						{:else if editing === 'new'}
							{$_('common.create', { default: 'Create' })}
						{:else}
							{$_('common.update', { default: 'Update' })}
						{/if}
					</Button>
				{/if}
			</div>
		</div>
	</div>
</StandardDialog>

<!-- Apply picker sub-dialog -->
<TemplateApplyPickerDialog
	bind:open={applyPickerOpen}
	templateId={applyPickerTemplateId}
	templateName={applyPickerTemplateName}
	onApplied={onApplied}
/>

<!-- Delete confirmation dialog -->
<StandardDialog
	bind:open={confirmDeleteOpen}
	title={$_('common.delete', { default: 'Delete' })}
	width="sm"
	data-testid="template-delete-confirm-dialog"
>
	<div class="mt-3 space-y-4">
		<p class="text-sm text-muted-foreground">
			{#if confirmDeleteTemplate}
				{$_('admin.channelMonitor.template.deleteConfirm', {
					default: `Delete template "${confirmDeleteTemplate.name}"? ${confirmDeleteTemplate.associated_monitors} monitors will lose their template association.`,
					values: {
						name: confirmDeleteTemplate.name,
						n: confirmDeleteTemplate.associated_monitors
					}
				})}
			{/if}
		</p>
		<div class="flex justify-end gap-2">
			<Button variant="outline" size="sm" onclick={() => (confirmDeleteOpen = false)}>
				{$_('common.cancel', { default: 'Cancel' })}
			</Button>
			<Button variant="destructive" size="sm" onclick={doDelete}>
				{$_('common.delete', { default: 'Delete' })}
			</Button>
		</div>
	</div>
</StandardDialog>

// frontend/src/components/admin/monitor/MonitorTemplateManagerDialog.vue
<template>
  <BaseDialog
    :show="show"
    :title="t('admin.channelMonitor.template.managerTitle')"
    width="wide"
    @close="$emit('close')"
  >
    <!-- provider tabs -->
    <div class="mb-4 border-b border-border">
      <div role="tablist" class="flex gap-1">
        <Button
          v-for="tab in providerTabs"
          :key="tab.value"
          type="button"
          variant="ghost"
          role="tab"
          :aria-selected="activeProvider === tab.value"
          class="px-4 py-2 text-sm font-medium transition-colors rounded-none"
          :class="tabClass(tab.value)"
          @click="activeProvider = tab.value"
        >
          {{ tab.label }}
          <Badge
            v-if="countByProvider[tab.value] > 0"
            variant="secondary"
            class="ml-1.5"
          >
            {{ countByProvider[tab.value] }}
          </Badge>
        </Button>
      </div>
    </div>

    <!-- active provider list -->
    <div v-if="!editing" class="space-y-2">
      <div class="flex justify-end">
        <Button size="sm" @click="openCreateForm">
          <Icon name="plus" size="sm" class="mr-1" />
          {{ t('admin.channelMonitor.template.createButton') }}
        </Button>
      </div>

      <div v-if="loading" class="py-8 text-center text-sm text-muted-foreground">
        {{ t('common.loading') }}
      </div>

      <div
        v-else-if="templatesForActiveProvider.length === 0"
        class="py-8 text-center text-sm text-muted-foreground"
      >
        {{ t('admin.channelMonitor.template.emptyState') }}
      </div>

      <div
        v-for="tpl in templatesForActiveProvider"
        v-else
        :key="tpl.id"
        class="rounded-lg border border-border bg-card p-4"
      >
        <div class="flex items-start justify-between gap-3">
          <div class="min-w-0 flex-1">
            <div class="flex items-center gap-2">
              <span class="font-medium text-foreground">{{ tpl.name }}</span>
              <Badge
                variant="outline"
                :class="modeBadgeClass(tpl.body_override_mode)"
              >
                {{ modeLabel(tpl.body_override_mode) }}
              </Badge>
              <Badge
                v-if="tpl.provider === PROVIDER_OPENAI"
                variant="outline"
                :class="apiModeBadgeClass(tpl.api_mode)"
              >
                {{ apiModeLabel(tpl.api_mode) }}
              </Badge>
              <span
                v-if="tpl.associated_monitors > 0"
                class="text-xs text-muted-foreground"
              >
                {{ t('admin.channelMonitor.template.associatedCount', { n: tpl.associated_monitors }) }}
              </span>
            </div>
            <p v-if="tpl.description" class="mt-0.5 text-xs text-muted-foreground">
              {{ tpl.description }}
            </p>
            <p class="mt-1 text-xs text-muted-foreground">
              {{ t('admin.channelMonitor.template.headersSummary', {
                n: Object.keys(tpl.extra_headers || {}).length,
              }) }}
            </p>
          </div>
          <div class="flex flex-shrink-0 gap-2">
            <Button
              variant="outline"
              size="sm"
              :disabled="tpl.associated_monitors === 0"
              :title="t('admin.channelMonitor.template.applyTooltip')"
              @click="confirmApply(tpl)"
            >
              <Icon name="refresh" size="sm" class="mr-1" />
              {{ t('admin.channelMonitor.template.applyButton') }}
            </Button>
            <Button variant="outline" size="sm" @click="openEditForm(tpl)">
              {{ t('common.edit') }}
            </Button>
            <Button variant="outline" size="sm" class="text-destructive hover:text-destructive" @click="handleDelete(tpl)">
              {{ t('common.delete') }}
            </Button>
          </div>
        </div>
      </div>
    </div>

    <!-- edit / create form -->
    <div v-else class="space-y-4">
      <div>
        <Label class="mb-1.5 block">
          {{ t('admin.channelMonitor.template.form.name') }}
          <span class="text-destructive">*</span>
        </Label>
        <Input
          v-model="form.name"
          type="text"
          required
          :placeholder="t('admin.channelMonitor.template.form.namePlaceholder')"
        />
      </div>

      <div v-if="editing === 'new'">
        <Label class="mb-1.5 block">
          {{ t('admin.channelMonitor.form.provider') }}
          <span class="text-destructive">*</span>
        </Label>
        <div class="grid grid-cols-3 gap-3">
          <Button
            v-for="opt in providerTabs"
            :key="opt.value"
            type="button"
            variant="outline"
            class="rounded-lg border-2 px-3 py-2 text-sm font-medium transition-colors"
            :class="providerPickerClass(opt.value, form.provider === opt.value)"
            @click="form.provider = opt.value"
          >
            {{ opt.label }}
          </Button>
        </div>
      </div>

      <div v-if="form.provider === PROVIDER_OPENAI" class="rounded-lg border border-border bg-accent p-3">
        <Label class="mb-1.5 block">{{ t('admin.channelMonitor.form.apiMode') }}</Label>
        <div class="grid gap-3 sm:grid-cols-2">
          <Button
            v-for="opt in apiModeOptions"
            :key="opt.value"
            type="button"
            variant="outline"
            class="h-auto rounded-lg border-2 px-3 py-2 text-left transition-colors flex-col items-start"
            :class="apiModeButtonClass(opt.value)"
            @click="form.api_mode = opt.value"
          >
            <span class="block text-sm font-semibold">{{ opt.label }}</span>
            <span class="mt-0.5 block text-xs opacity-80">{{ opt.hint }}</span>
          </Button>
        </div>
      </div>

      <div>
        <Label class="mb-1.5 block">
          {{ t('admin.channelMonitor.template.form.description') }}
        </Label>
        <Input
          v-model="form.description"
          type="text"
          :placeholder="t('admin.channelMonitor.template.form.descriptionPlaceholder')"
        />
      </div>

      <MonitorAdvancedRequestConfig
        :provider="form.provider"
        :api-mode="form.api_mode"
        :extra-headers="form.extra_headers"
        :body-override-mode="form.body_override_mode"
        :body-override="form.body_override"
        @update:extra-headers="form.extra_headers = $event"
        @update:body-override-mode="form.body_override_mode = $event"
        @update:body-override="form.body_override = $event"
      />
    </div>

    <template #footer>
      <div class="flex w-full items-center justify-between">
        <!-- Left: back to list / nothing -->
        <div>
          <Button v-if="editing" variant="outline" @click="backToList">
            {{ t('common.back') }}
          </Button>
        </div>
        <!-- Right: save or close -->
        <div class="flex gap-2">
          <Button variant="outline" @click="$emit('close')">
            {{ t('common.close') }}
          </Button>
          <Button v-if="editing" :disabled="submitting" @click="handleSubmit">
            {{ submitting ? t('common.submitting') : editing === 'new' ? t('common.create') : t('common.update') }}
          </Button>
        </div>
      </div>
    </template>
  </BaseDialog>

  <MonitorTemplateApplyPickerDialog
    :show="applyPicker.show"
    :template-id="applyPicker.tpl ? applyPicker.tpl.id : null"
    :template-name="applyPicker.tpl ? applyPicker.tpl.name : ''"
    @close="applyPicker.show = false"
    @applied="onApplied"
  />

  <ConfirmDialog
    :show="confirmDelete.show"
    :title="t('common.delete')"
    :message="confirmDeleteMessage"
    :confirm-text="t('common.delete')"
    :cancel-text="t('common.cancel')"
    :danger="true"
    @confirm="doDelete"
    @cancel="confirmDelete.show = false"
  />
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useAppStore } from '@/stores/app'
import { extractApiErrorMessage } from '@/utils/apiError'
import { adminAPI } from '@/api/admin'
import type {
  APIMode,
  BodyOverrideMode,
  Provider,
} from '@/api/admin/channelMonitor'
import type { ChannelMonitorTemplate } from '@/api/admin/channelMonitorTemplate'
import BaseDialog from '@/components/common/BaseDialog.vue'
import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import Icon from '@/components/icons/Icon.vue'
import MonitorAdvancedRequestConfig from '@/components/admin/monitor/MonitorAdvancedRequestConfig.vue'
import MonitorTemplateApplyPickerDialog from '@/components/admin/monitor/MonitorTemplateApplyPickerDialog.vue'
import { useChannelMonitorFormat } from '@/composables/useChannelMonitorFormat'
import {
  PROVIDER_ANTHROPIC,
  PROVIDER_OPENAI,
  PROVIDER_GEMINI,
  API_MODE_CHAT_COMPLETIONS,
  API_MODE_RESPONSES,
} from '@/constants/channelMonitor'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'

const props = defineProps<{ show: boolean }>()
const emit = defineEmits<{
  (e: 'close'): void
  /** Fired when any template changed (create / update / delete / apply). */
  (e: 'updated'): void
}>()

const { t } = useI18n()
const appStore = useAppStore()
const { providerPickerClass } = useChannelMonitorFormat()

const providerTabs = computed<{ value: Provider; label: string }[]>(() => [
  { value: PROVIDER_ANTHROPIC, label: t('monitorCommon.providers.anthropic') },
  { value: PROVIDER_OPENAI, label: t('monitorCommon.providers.openai') },
  { value: PROVIDER_GEMINI, label: t('monitorCommon.providers.gemini') },
])

const activeProvider = ref<Provider>(PROVIDER_ANTHROPIC)
const templates = ref<ChannelMonitorTemplate[]>([])
const loading = ref(false)

const templatesForActiveProvider = computed(() =>
  templates.value.filter((t) => t.provider === activeProvider.value),
)

const countByProvider = computed<Record<Provider, number>>(() => {
  const out: Record<Provider, number> = {
    anthropic: 0,
    openai: 0,
    gemini: 0,
  }
  for (const t of templates.value) out[t.provider]++
  return out
})

// --- form state ---
interface TemplateForm {
  id: number | null
  name: string
  provider: Provider
  api_mode: APIMode
  description: string
  extra_headers: Record<string, string>
  body_override_mode: BodyOverrideMode
  body_override: Record<string, unknown> | null
}

const editing = ref<null | 'new' | number>(null) // null = list view; 'new' = create; <id> = edit
const submitting = ref(false)
const form = reactive<TemplateForm>(emptyForm(PROVIDER_ANTHROPIC))

function emptyForm(provider: Provider): TemplateForm {
  return {
    id: null,
    name: '',
    provider,
    api_mode: API_MODE_CHAT_COMPLETIONS,
    description: '',
    extra_headers: {},
    body_override_mode: 'off',
    body_override: null,
  }
}

function loadForm(tpl: ChannelMonitorTemplate) {
  form.id = tpl.id
  form.name = tpl.name
  form.provider = tpl.provider
  form.api_mode = normalizeAPIMode(tpl.api_mode)
  form.description = tpl.description
  form.extra_headers = { ...(tpl.extra_headers || {}) }
  form.body_override_mode = tpl.body_override_mode
  form.body_override = tpl.body_override ? { ...tpl.body_override } : null
}

function openCreateForm() {
  Object.assign(form, emptyForm(activeProvider.value))
  editing.value = 'new'
}

function openEditForm(tpl: ChannelMonitorTemplate) {
  loadForm(tpl)
  editing.value = tpl.id
}

function backToList() {
  editing.value = null
}

// --- data fetch ---
async function fetchTemplates() {
  loading.value = true
  try {
    const { items } = await adminAPI.channelMonitorTemplate.list()
    templates.value = items
  } catch (err: unknown) {
    appStore.showError(extractApiErrorMessage(err, t('common.error')))
  } finally {
    loading.value = false
  }
}

watch(
  () => props.show,
  (show) => {
    if (show) {
      editing.value = null
      fetchTemplates()
    }
  },
  { immediate: true },
)

// --- submit ---
async function handleSubmit() {
  if (submitting.value) return
  if (!form.name.trim()) {
    appStore.showError(t('admin.channelMonitor.template.missingName'))
    return
  }
  submitting.value = true
  try {
    if (editing.value === 'new') {
      await adminAPI.channelMonitorTemplate.create({
        name: form.name.trim(),
        provider: form.provider,
        api_mode: form.provider === PROVIDER_OPENAI ? form.api_mode : API_MODE_CHAT_COMPLETIONS,
        description: form.description.trim(),
        extra_headers: form.extra_headers,
        body_override_mode: form.body_override_mode,
        body_override: form.body_override,
      })
      appStore.showSuccess(t('admin.channelMonitor.template.createSuccess'))
    } else if (typeof editing.value === 'number') {
      await adminAPI.channelMonitorTemplate.update(editing.value, {
        name: form.name.trim(),
        api_mode: form.provider === PROVIDER_OPENAI ? form.api_mode : API_MODE_CHAT_COMPLETIONS,
        description: form.description.trim(),
        extra_headers: form.extra_headers,
        body_override_mode: form.body_override_mode,
        body_override: form.body_override,
      })
      appStore.showSuccess(t('admin.channelMonitor.template.updateSuccess'))
    }
    await fetchTemplates()
    emit('updated')
    editing.value = null
  } catch (err: unknown) {
    appStore.showError(extractApiErrorMessage(err, t('common.error')))
  } finally {
    submitting.value = false
  }
}

// --- apply to monitors (picker 流程) ---
const applyPicker = reactive<{ show: boolean; tpl: ChannelMonitorTemplate | null }>({
  show: false,
  tpl: null,
})

function confirmApply(tpl: ChannelMonitorTemplate) {
  applyPicker.tpl = tpl
  applyPicker.show = true
}

// picker 提交后触发：刷新模板列表（拿最新 associated_monitors）+ 通知父组件
async function onApplied(_affected: number) {
  await fetchTemplates()
  emit('updated')
}

// --- delete ---
const confirmDelete = reactive<{ show: boolean; tpl: ChannelMonitorTemplate | null }>({
  show: false,
  tpl: null,
})

function handleDelete(tpl: ChannelMonitorTemplate) {
  confirmDelete.tpl = tpl
  confirmDelete.show = true
}

const confirmDeleteMessage = computed(() => {
  const tpl = confirmDelete.tpl
  if (!tpl) return ''
  return t('admin.channelMonitor.template.deleteConfirm', {
    name: tpl.name,
    n: tpl.associated_monitors,
  })
})

async function doDelete() {
  const tpl = confirmDelete.tpl
  confirmDelete.show = false
  if (!tpl) return
  try {
    await adminAPI.channelMonitorTemplate.del(tpl.id)
    appStore.showSuccess(t('admin.channelMonitor.template.deleteSuccess'))
    await fetchTemplates()
    emit('updated')
  } catch (err: unknown) {
    appStore.showError(extractApiErrorMessage(err, t('common.error')))
  }
}

// --- misc ---
function tabClass(value: Provider): string {
  return activeProvider.value === value
    ? 'border-b-2 border-primary text-primary'
    : 'border-b-2 border-transparent text-muted-foreground hover:text-foreground'
}

function modeBadgeClass(mode: BodyOverrideMode): string {
  switch (mode) {
    case 'merge':
      return 'bg-amber-500/15 text-amber-400 '
    case 'replace':
      return 'bg-purple-500/15 text-purple-300 '
    default:
      return 'bg-accent text-muted-foreground'
  }
}

function modeLabel(mode: BodyOverrideMode): string {
  return t(`admin.channelMonitor.advanced.bodyMode${mode.charAt(0).toUpperCase()}${mode.slice(1)}`)
}

const apiModeOptions = computed<{ value: APIMode; label: string; hint: string }[]>(() => [
  {
    value: API_MODE_CHAT_COMPLETIONS,
    label: t('admin.channelMonitor.form.apiModeChatCompletions'),
    hint: t('admin.channelMonitor.form.apiModeChatCompletionsHint'),
  },
  {
    value: API_MODE_RESPONSES,
    label: t('admin.channelMonitor.form.apiModeResponses'),
    hint: t('admin.channelMonitor.form.apiModeResponsesHint'),
  },
])

watch(() => form.provider, (provider) => {
  if (provider !== PROVIDER_OPENAI) {
    form.api_mode = API_MODE_CHAT_COMPLETIONS
  }
})

function normalizeAPIMode(mode: APIMode | undefined | null): APIMode {
  return mode === API_MODE_RESPONSES ? API_MODE_RESPONSES : API_MODE_CHAT_COMPLETIONS
}

function apiModeButtonClass(mode: APIMode): string {
  const active = form.api_mode === mode
  if (active) {
    return 'border-primary bg-primary/15 text-primary shadow-sm  '
  }
  return 'border-border bg-card text-muted-foreground hover:border-primary/50'
}

function apiModeLabel(mode: APIMode): string {
  return normalizeAPIMode(mode) === API_MODE_RESPONSES
    ? t('admin.channelMonitor.form.apiModeResponses')
    : t('admin.channelMonitor.form.apiModeChatCompletions')
}

function apiModeBadgeClass(mode: APIMode): string {
  if (normalizeAPIMode(mode) === API_MODE_RESPONSES) {
    return 'bg-blue-500/15 text-sky-400 '
  }
  return 'bg-emerald-500/15 text-emerald-400 '
}
</script>
