// frontend-svelte/src/lib/features/users/UserFormDrawer.svelte
<script lang="ts">
	import { _ } from 'svelte-i18n';
	import { createUser, updateUser, type AdminUser, type CreateAdminUserRequest, type UpdateAdminUserRequest } from '$lib/api/admin/users';
	import { listGroups } from '$lib/api/admin/groups';
	import { showError, showSuccess } from '$lib/stores/toast.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Input from '$lib/ui/Input.svelte';
	import NativeSelect from '$lib/ui/NativeSelect.svelte';
	import Checkbox from '$lib/ui/Checkbox.svelte';
	import StandardDrawer from '$lib/ui/StandardDrawer.svelte';

	type Props = {
		open: boolean;
		user?: AdminUser | null;
		onClose: () => void;
		onSaved: () => void;
	};

	let { open = $bindable(false), user = null, onClose, onSaved }: Props = $props();

	const isEdit = $derived(!!user);

	let email = $state('');
	let password = $state('');
	let username = $state('');
	let balance = $state(0);
	let concurrency = $state(5);
	let rpmLimit = $state(0);
	let role = $state<'admin' | 'user'>('user');
	let status = $state<'active' | 'disabled'>('active');
	let notes = $state('');
	let selectedGroups = $state<number[]>([]);
	let submitting = $state(false);
	let allGroups = $state<Array<{ id: number; name: string }>>([]);

	async function loadGroups() {
		try {
			const res = await listGroups();
			allGroups = res?.items ?? [];
		} catch { /* ignore */ }
	}

	function populate(u: AdminUser | null) {
		if (u) {
			email = u.email; username = u.username ?? ''; concurrency = u.concurrency ?? 5;
			rpmLimit = u.rpm_limit ?? 0; role = u.role as 'admin' | 'user'; status = u.status as 'active' | 'disabled';
			notes = u.notes ?? '';
			selectedGroups = u.allowed_groups?.slice() ?? u.groups?.map(g => g.id) ?? [];
			password = ''; balance = 0;
		} else {
			email = ''; password = ''; username = ''; balance = 0; concurrency = 5;
			rpmLimit = 0; role = 'user'; status = 'active'; notes = ''; selectedGroups = [];
		}
	}

	function generatePassword() {
		const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%';
		password = Array.from({ length: 16 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
	}

	$effect(() => { if (open) { populate(user ?? null); loadGroups(); } });

	function toggleGroup(id: number) {
		if (selectedGroups.includes(id)) selectedGroups = selectedGroups.filter(g => g !== id);
		else selectedGroups = [...selectedGroups, id];
	}

	async function submit() {
		if (!email.trim()) { showError($_('admin.users.emailRequired', { default: 'Email is required' })); return; }
		if (!isEdit && !password.trim()) { showError($_('admin.users.passwordRequired', { default: 'Password is required for new users' })); return; }
		submitting = true;
		try {
			if (isEdit && user) {
				const payload: UpdateAdminUserRequest = {
					email: email.trim(), username: username.trim() || undefined,
					notes: notes.trim() || undefined, role, status,
					concurrency, allowed_groups: selectedGroups.length ? selectedGroups : null
				};
				if (password.trim()) payload.password = password.trim();
				if (rpmLimit > 0) (payload as unknown as Record<string, unknown>).rpm_limit = rpmLimit;
				await updateUser(user.id, payload);
				showSuccess($_('admin.users.updated', { default: 'User updated' }));
			} else {
				const payload: CreateAdminUserRequest = {
					email: email.trim(), password: password.trim(),
					username: username.trim() || undefined, notes: notes.trim() || undefined,
					balance: balance || undefined, concurrency,
					allowed_groups: selectedGroups.length ? selectedGroups : null
				};
				if (rpmLimit > 0) (payload as unknown as Record<string, unknown>).rpm_limit = rpmLimit;
				await createUser(payload);
				showSuccess($_('admin.users.created', { default: 'User created' }));
			}
			onSaved();
			onClose();
		} catch (e: unknown) {
			showError((e as Error)?.message || $_('admin.users.saveFailed', { default: 'Save failed' }));
		} finally {
			submitting = false;
		}
	}
</script>

<StandardDrawer bind:open
	title={isEdit ? $_('admin.users.editUser', { default: 'Edit User' }) : $_('admin.users.createUser', { default: 'Create User' })}
	data-testid="user-form-drawer">
	<form class="flex flex-col gap-4 p-1" onsubmit={(e) => { e.preventDefault(); submit(); }}>
		<div class="flex flex-col gap-1.5">
			<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
				{$_('admin.users.email', { default: 'Email' })} <span class="text-destructive">*</span>
			</span>
			<Input type="email" required autocomplete="off" placeholder="user@example.com"
				bind:value={email} data-testid="user-form-email" />
		</div>

		<div class="flex flex-col gap-1.5">
			<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
				{isEdit ? $_('admin.users.passwordEdit', { default: 'New Password (optional)' }) : $_('admin.users.password', { default: 'Password' })}
			</span>
			<div class="flex gap-2">
				<Input type="text" autocomplete="new-password" class="flex-1"
					placeholder={$_('admin.users.passwordPlaceholder', { default: 'Enter password' })}
					required={!isEdit} bind:value={password} data-testid="user-form-password" />
				<Button type="button" variant="outline" size="sm" onclick={generatePassword}
					title={$_('admin.users.generatePassword', { default: 'Generate' })}>
					↻
				</Button>
			</div>
		</div>

		<div class="flex flex-col gap-1.5">
			<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
				{$_('admin.users.username', { default: 'Username' })}
			</span>
			<Input type="text" autocomplete="off" bind:value={username}
				placeholder={$_('admin.users.usernamePlaceholder', { default: 'Optional display name' })}
				data-testid="user-form-username" />
		</div>

		{#if !isEdit}
			<div class="flex flex-col gap-1.5">
				<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
					{$_('admin.users.initialBalance', { default: 'Initial Balance' })}
				</span>
				<Input type="number" step="0.01" min="0" placeholder="0.00"
					bind:value={balance} data-testid="user-form-balance" />
			</div>
		{/if}

		<div class="grid grid-cols-2 gap-3">
			<div class="flex flex-col gap-1.5">
				<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
					{$_('admin.users.concurrency', { default: 'Concurrency' })}
				</span>
				<Input type="number" min="1" bind:value={concurrency} data-testid="user-form-concurrency" />
			</div>
			<div class="flex flex-col gap-1.5">
				<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
					{$_('admin.users.rpmLimit', { default: 'RPM Limit (0 = unlimited)' })}
				</span>
				<Input type="number" min="0" bind:value={rpmLimit} data-testid="user-form-rpm" />
			</div>
		</div>

		{#if isEdit}
			<div class="grid grid-cols-2 gap-3">
				<div class="flex flex-col gap-1.5">
					<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
						{$_('admin.users.role', { default: 'Role' })}
					</span>
					<NativeSelect bind:value={role} data-testid="user-form-role">
						<option value="user">{$_('admin.users.roleUser', { default: 'User' })}</option>
						<option value="admin">{$_('admin.users.roleAdmin', { default: 'Admin' })}</option>
					</NativeSelect>
				</div>
				<div class="flex flex-col gap-1.5">
					<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
						{$_('admin.users.status', { default: 'Status' })}
					</span>
					<NativeSelect bind:value={status} data-testid="user-form-status">
						<option value="active">{$_('admin.users.statusActive', { default: 'Active' })}</option>
						<option value="disabled">{$_('admin.users.statusDisabled', { default: 'Disabled' })}</option>
					</NativeSelect>
				</div>
			</div>
		{/if}

		{#if allGroups.length}
			<div class="flex flex-col gap-1.5">
				<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
					{$_('admin.users.groups', { default: 'Groups' })}
				</span>
				<div class="flex max-h-40 flex-col gap-1 overflow-y-auto rounded-md border border-border p-2">
					{#each allGroups as g}
						<label class="flex cursor-pointer items-center gap-2 rounded px-1.5 py-1 text-sm hover:bg-muted/50">
							<Checkbox checked={selectedGroups.includes(g.id)}
								onchange={() => toggleGroup(g.id)} />
							{g.name}
						</label>
					{/each}
				</div>
			</div>
		{/if}

		<div class="flex flex-col gap-1.5">
			<span class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
				{$_('admin.users.notes', { default: 'Notes' })}
			</span>
			<Input type="text" bind:value={notes}
				placeholder={$_('admin.users.notesPlaceholder', { default: 'Optional notes' })}
				data-testid="user-form-notes" />
		</div>

		<div class="flex justify-end gap-2 border-t border-border pt-4">
			<Button type="button" variant="outline" size="sm" onclick={onClose}>
				{$_('common.cancel', { default: 'Cancel' })}
			</Button>
			<Button type="submit" size="sm" disabled={submitting} data-testid="user-form-submit">
				{submitting ? $_('common.saving', { default: 'Saving...' }) : $_('common.save', { default: 'Save' })}
			</Button>
		</div>
	</form>
</StandardDrawer>

// frontend/src/views/admin/users/UserFormDrawer.vue
<template>
  <Sheet :open="open" @update:open="(v) => { if (!v) $emit('close') }">
    <SheetContent side="right" class="w-[400px] max-w-full p-0 flex flex-col" :aria-label="isEdit ? t('admin.userFormDrawer.titleEdit') : t('admin.userFormDrawer.titleCreate')">
      <!-- 头部 -->
      <SheetHeader class="px-6 py-4 border-b border-border flex-shrink-0">
        <SheetTitle class="text-[15px] font-bold text-foreground">
          {{ isEdit ? t('admin.userFormDrawer.titleEdit') : t('admin.userFormDrawer.titleCreate') }}
        </SheetTitle>
      </SheetHeader>

      <!-- 表单主体 -->
      <ScrollArea class="flex-1">
        <form class="flex flex-col gap-4 p-6" @submit.prevent="handleSubmit">
          <!-- 邮箱 -->
          <div class="flex flex-col gap-1.5">
            <Label class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              {{ t('admin.userFormDrawer.emailLabel') }}
              <span class="text-destructive ml-0.5">*</span>
            </Label>
            <Input
              v-model="form.email"
              type="email"
              required
              placeholder="user@example.com"
              autocomplete="off"
            />
          </div>

          <!-- 密码 -->
          <div class="flex flex-col gap-1.5">
            <Label class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              {{ isEdit ? t('admin.userFormDrawer.passwordEditLabel') : t('admin.userFormDrawer.passwordLabel') }}
            </Label>
            <div class="flex gap-2">
              <Input
                v-model="form.password"
                type="text"
                :required="!isEdit"
                :placeholder="t('admin.userFormDrawer.passwordPlaceholder')"
                autocomplete="new-password"
                class="flex-1"
              />
              <Button
                type="button"
                variant="outline"
                size="icon"
                :title="t('admin.userFormDrawer.passwordGenTitle')"
                @click="generatePassword"
                class="shrink-0"
              >
                <svg width="13" height="13" viewBox="0 0 13 13" fill="none" aria-hidden="true">
                  <path d="M11.5 6.5A5 5 0 1 1 6.5 1.5" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>
                  <path d="M9 1.5v3h-3" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
              </Button>
            </div>
          </div>

          <!-- 用户名 -->
          <div class="flex flex-col gap-1.5">
            <Label class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              {{ t('admin.userFormDrawer.usernameLabel') }}
            </Label>
            <Input
              v-model="form.username"
              type="text"
              :placeholder="t('admin.userFormDrawer.usernamePlaceholder')"
              autocomplete="off"
            />
          </div>

          <!-- 初始余额（仅创建时） -->
          <div v-if="!isEdit" class="flex flex-col gap-1.5">
            <Label class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              {{ t('admin.userFormDrawer.balanceLabel') }}
            </Label>
            <Input
              v-model="form.balance"
              type="number"
              step="0.01"
              min="0"
              placeholder="0.00"
            />
          </div>

          <!-- 并发上限 -->
          <div class="flex flex-col gap-1.5">
            <Label class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              {{ t('admin.userFormDrawer.concurrencyLabel') }}
            </Label>
            <Input
              v-model.number="form.concurrency"
              type="number"
              min="1"
            />
          </div>

          <!-- RPM 限速 -->
          <div class="flex flex-col gap-1.5">
            <Label class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              {{ t('admin.userFormDrawer.rpmLabel') }}
              <span class="ml-1 font-normal normal-case text-muted-foreground/70">{{ t('admin.userFormDrawer.rpmHint') }}</span>
            </Label>
            <Input
              v-model.number="form.rpm_limit"
              type="number"
              min="0"
              step="1"
            />
          </div>

          <!-- 备注（仅编辑时） -->
          <div v-if="isEdit" class="flex flex-col gap-1.5">
            <Label class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
              {{ t('admin.userFormDrawer.notesLabel') }}
            </Label>
            <Textarea
              v-model="form.notes"
              rows="3"
              :placeholder="t('admin.userFormDrawer.notesPlaceholder')"
              class="resize-y min-h-[72px]"
            />
          </div>

          <!-- 错误提示 -->
          <div v-if="errorMsg" class="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2.5 text-[12.5px] text-destructive">
            {{ errorMsg }}
          </div>

          <!-- 底部操作 -->
          <div class="flex justify-end gap-2 pt-2">
            <Button type="button" variant="outline" @click="$emit('close')">
              {{ t('admin.userFormDrawer.cancelBtn') }}
            </Button>
            <Button type="submit" :disabled="submitting">
              {{ submitting ? (isEdit ? t('admin.userFormDrawer.saving') : t('admin.userFormDrawer.creating')) : (isEdit ? t('admin.userFormDrawer.saveChanges') : t('admin.userFormDrawer.createUser')) }}
            </Button>
          </div>
        </form>
      </ScrollArea>
    </SheetContent>
  </Sheet>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { adminAPI } from '@/api/admin'
import type { AdminUser } from '@/types'
import { useAppStore } from '@/stores/app'
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { ScrollArea } from '@/components/ui/scroll-area'

const { t } = useI18n()

const props = defineProps<{
  open: boolean
  user: AdminUser | null
}>()

const emit = defineEmits<{
  close: []
  success: []
}>()

const appStore = useAppStore()
const submitting = ref(false)
const errorMsg = ref('')
const isEdit = computed(() => !!props.user)

const form = reactive({
  email: '',
  password: '',
  username: '',
  balance: '',
  concurrency: 1,
  rpm_limit: 0,
  notes: '',
})

// 同步 user prop → form
watch(() => props.user, (u) => {
  if (u) {
    form.email = u.email
    form.password = ''
    form.username = u.username || ''
    form.concurrency = u.concurrency
    form.rpm_limit = u.rpm_limit ?? 0
    form.notes = u.notes || ''
    form.balance = ''
  } else {
    form.email = ''
    form.password = ''
    form.username = ''
    form.concurrency = 1
    form.rpm_limit = 0
    form.notes = ''
    form.balance = ''
  }
  errorMsg.value = ''
}, { immediate: true })

// 每次面板打开时清错误
watch(() => props.open, (v) => {
  if (v) errorMsg.value = ''
})

function generatePassword() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$%^&*'
  let p = ''
  for (let i = 0; i < 16; i++) p += chars.charAt(Math.floor(Math.random() * chars.length))
  form.password = p
}

async function handleSubmit() {
  errorMsg.value = ''
  if (!form.email.trim()) { errorMsg.value = t('admin.userFormDrawer.validEmailRequired'); return }
  if (!isEdit.value && !form.password.trim()) { errorMsg.value = t('admin.userFormDrawer.validPasswordRequired'); return }
  if (form.concurrency < 1) { errorMsg.value = t('admin.userFormDrawer.validConcurrencyMin'); return }

  submitting.value = true
  try {
    if (isEdit.value && props.user) {
      const data: Record<string, unknown> = {
        email: form.email,
        username: form.username,
        notes: form.notes,
        concurrency: form.concurrency,
        rpm_limit: form.rpm_limit,
      }
      if (form.password.trim()) data.password = form.password.trim()
      await adminAPI.users.update(props.user.id, data as any)
      appStore.showSuccess(t('admin.userFormDrawer.userUpdated'))
    } else {
      const balanceStr = String(form.balance).trim()
      const payload: Parameters<typeof adminAPI.users.create>[0] = {
        email: form.email,
        password: form.password,
        username: form.username || undefined,
        concurrency: form.concurrency,
        rpm_limit: form.rpm_limit,
      }
      if (balanceStr !== '') payload.balance = Number(balanceStr)
      await adminAPI.users.create(payload)
      appStore.showSuccess(t('admin.userFormDrawer.userCreated'))
    }
    emit('success')
  } catch (e: any) {
    errorMsg.value = e?.response?.data?.detail || e?.message || t('admin.userFormDrawer.operationFailed')
  } finally {
    submitting.value = false
  }
}
</script>
